### ISSUE TITLE
Some bugs in FLUX pipeline

### ISSUE THREAD

**Issue by chenxiao111222** [huggingface/diffusers#10111]
### Describe the bug

1. missing self.theta in get_1d_rotary_pos_embed:
https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/embeddings.py#L961-L963
2. if prompt_embeds is None, pooled_prompt_embeds will never be computed:
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/flux/pipeline_flux.py#L348-L363

### Reproduction

.

### System Info

.

### Who can help?

@yiyixuxu @sayakpaul @DN6 @asomoza

**Comment by hlky** [comment]
`pooled_prompt_embeds` has to be passed when `prompt_embeds` is used so that's ok
https://github.com/huggingface/diffusers/blob/8421c1461bf4ab7801070d04d6ec1e6b28ee5b59/src/diffusers/pipelines/flux/pipeline_flux.py#L422-L425

Would you like to open a PR that passes `self.theta` to `get_1d_rotary_pos_embed`?
