### ISSUE TITLE
Low probability of throwing 'CLIPTextTransformer' object has no attribute 'device' exception

### ISSUE THREAD

**Issue by chinoll** [huggingface/diffusers#1100]
### Describe the bug

When running a pipeline, there is a probability that an exception will be thrown.
```
Traceback (most recent call last):
  File "/home/xxx/yyy/trainer.py", line 376, in main
    image = [pipe(prompt,negative_prompt=negative_prompt,width=h,height=w,max_embeddings_multiples=3).images[0] for i in batch['caption']]
  File "/home/xxx/yyy/trainer.py", line 376, in <listcomp>
    image = [pipe(prompt,negative_prompt=negative_prompt,width=h,height=w,max_embeddings_multiples=3).images[0] for i in batch['caption']]
  File "/home/xxx/anaconda3/envs/zzz/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/yyy/lpw.py", line 615, in __call__
    text_embeddings, uncond_embeddings = get_weighted_text_embeddings(
  File "/home/xxx/yyy/lpw.py", line 310, in get_weighted_text_embeddings
    prompt_tokens = torch.tensor(prompt_tokens, dtype=torch.long, device=pipe.device)
  File "/home/xxx/anaconda3/envs/zzz/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 213, in device
    return module.device
  File "/home/xxx/anaconda3/envs/zzz/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CLIPTextTransformer' object has no attribute 'device'
```
lpw module is [lpw_stable_diffusion](https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py)

### System Info

- `diffusers` version: 0.6.0
- Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.31
- Python version: 3.10.6
- PyTorch version (GPU?): 1.12.1 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.19.2
- Using GPU in script?: True
- Using distributed or parallel set-up in script?: <fill in>
- gpus: A100 80G PCIe*1

**Comment by patrickvonplaten** [comment]
Hey @chinoll,

Could you provide a reproducible code snippet for this?

**Comment by chinoll** [comment]
> Hey @chinoll,
> 
> Could you provide a reproducible code snippet for this?

```python
pipe = StableDiffusionLongPromptWeightingPipeline(
                text_encoder=text_encoder.transformer,
                vae=vae,
                unet=unet,
                tokenizer=text_encoder.tokenizer,
                scheduler=PNDMScheduler(
                    beta_start=0.00085, beta_end=0.012,beta_schedule="scaled_linear",skip_prk_steps=True
                ),
                safety_checker=None,
                feature_extractor=CLIPFeatureExtractor.from_pretrained("openai/clip-vit-large-patch14")
            )
images = pipe(prompt,negative_prompt=negative_prompt,width=h,height=w,max_embeddings_multiples=3).images[0]
```

**Comment by chinoll** [comment]
NVIDIA DRIVER VERSION:NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2

**Comment by keturn** [comment]
I've seen similar errors, and it looked like the relevant part was around here:

```
    prompt_tokens = torch.tensor(prompt_tokens, dtype=torch.long, device=pipe.device)
  File "/home/xxx/anaconda3/envs/zzz/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 213, in device
    return module.device
```

because `pipe.device` is very loosely defined. It just kinda rummages around until it finds _something_ that might be relevant and throws it back:

https://github.com/huggingface/diffusers/blob/bde4880c9cceada20b387d3110061c65249dabcc/src/diffusers/pipeline_utils.py#L228-L234

and, ya know, Python dictionaries usually tend to be ordered these days but there's no particularly strong guarantee here about what order those entries from `init_dict` are going to be iterated through.

and some of them are diffusers modules and some of them are transformers modules and some of them are, like, schedulers or something else that isn't a `torch.nn` module at all. And if you're using `accelerate` (which I guess we're doing a lot more often as of this release!), then maybe that device is `auto`, which works for some kinds of things but maybe not for copying some data in to a new tensor, and it's a bit of a shambles all around.

A more predictable alternative to `pipe.device` is to use the device of the most relevant sub-model: probably `pipe.text_encoder.device` or `pipe.unet.device` here, depending on where you're sending that tensor next.

except that _still_ has the problem where model.device may return `auto` and I don't know enough about how `accelerate` is supposed to be used to say what we're supposed to do about that.

**Comment by keturn** [comment]
and [torch.nn.Module](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module) doesn't actually have a `.device`, so line 231's `isinstance` there is only half-useful. That property is provided by the [transformers `ModuleUtilsMixin`](https://github.com/huggingface/transformers/blob/d447c460b16626c656e4d7a9425f648fe69517b3/src/transformers/modeling_utils.py#L676) or maybe [diffusers `ModelMixin`](https://github.com/huggingface/diffusers/blob/bde4880c9cceada20b387d3110061c65249dabcc/src/diffusers/modeling_utils.py#L611) or maybe something else because diffusion is all about _anarchy_ and you can't tell it what to do and how to depend on common interfaces we can use to understand the data types we're given! 

but hey, doesn't CLIPTextTransformer have that ModelUtilsMixin? so shouldn't it have `.device`?

well yeah probably except the implementation of `ModelUtilsMixin.device` **also** uses the "rummage around in a bag until you find something that might fit" technique, and if you happen to call it before the parameters for that module are actually loaded, it might not find anything, so ymmv.

**Comment by patrickvonplaten** [comment]
Hmmm, I actually cannot think of a better way at the moment to implement `.device` and I'm also not able to reproduce the error. 
In general, it's always good to use the device of the previous tensor input instead of `pipe.device` . Only for the very first random noise that's created we have to rely on the weights of the pipeline and there I'd suggest to rely on the weights that will first deal with the tensor, so maybe we should use `self.unet.device` instead
