### ISSUE TITLE
PNDM repeatedly calls the unet model

### ISSUE THREAD

**Issue by LuChengTHU** [huggingface/diffusers#1106]
### Describe the bug

https://github.com/huggingface/diffusers/blob/0b61cea347e9b464fb03506cb78a49d38e1c74ee/src/diffusers/schedulers/scheduling_pndm.py#L168-L175

plms_timesteps uses a repeated time step at the second and the third step, which leads to the pipeline computing the unet once again:

https://github.com/huggingface/diffusers/blob/cbcd0512f04064bb25206ad844ebc4a9a022cad1/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L381-L387

### Reproduction

Using 50-step PNDM for stable diffusion actually calls the unet 51 times.

### System Info

- `diffusers` version: 0.7.0.dev0
- Platform: Linux-4.15.0-169-generic-x86_64-with-glibc2.10
- Python version: 3.8.0
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.25.0.dev0
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
Hey @LuChengTHU,

Yes this is expected, PNDM needs some higher order scheduler steps in the beginning (1 to be exact when `skip_prk=True`)  which is why we have 51 model evaluations instead of 50 - it's the same in the original implementation. 

See how for the very first step we have two model evaluations here: https://github.com/CompVis/stable-diffusion/blob/69ae4b35e0a0f6ee1af8bb9a5d0016ccb27e36dc/ldm/models/diffusion/plms.py#L222

**Comment by patrickvonplaten** [comment]
This is actually solved now, we've updated the progress bar to correctly display the number of **inference steps** not **model evalutions** . 

cc @anton-l
