### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Limbicnation** [huggingface/diffusers#1409]
Hello, I get the error:

`IndexError: list index out of range`

when I run inference.py

```
from diffusers import StableDiffusionPipeline
import torch

model_id = "/mnt/data-ml/ML-Images2/models/diffusers/pixel-art-characters"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

prompt = "a pixel art character"
image = pipe(prompt, num_inference_steps=100, guidance_scale=7.5).images[10]
safety_checker=None,

image.save("pixel-art-character.png")
```

I want to generate 10 images.

Pleas help.

**Comment by pcuenca** [comment]
Hi @Limbicnation!

There are 2 ways to indicate the pipeline that you want to generate 10 images.

* Provide multiple prompts instead of just one:

```Python
images = pipe([prompt]*10, num_inference_steps=100, guidance_scale=7.5).images
```

* Use the additional argument `num_images_per_prompt` to request the number of images you want:

```Python
images = pipe(prompt, num_images_per_prompt=10, num_inference_steps=100, guidance_scale=7.5).images
```

Either way, the pipeline will return in `images` a list with all the results, so you can then iterate to do what you want with them:

```Python
for i, image in enumerate(images):
    image.save(f"image_{i}.png")
```

You also need to make sure that you have enough GPU memory to generate several images at once, as the process is rather memory intensive.

Hope that helps!

**Comment by Limbicnation** [comment]
@pcuenca that worked, thank you!
