### ISSUE TITLE
Diffusers->SD CKPT script doesn't work for V2 Model.

### ISSUE THREAD

**Issue by d8ahazard** [huggingface/diffusers#1528]
### Describe the bug

Extracting the V2-768 model with the current script (updated today) and then compiling again does not result in a working model.

### Reproduction

Extract the V2-768 checkpoint using [convert_original_stable_diffusion_to_diffusers.py](https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py)

Rebuild to ckpt with [convert_diffusers_to_original_stable_diffusion.py](https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py)

Load with automatic1111 and the vanilla v2-inference-v.yaml config file.

Use txt2img to generate...anything. Result for "a photo of a dog":

![image](https://user-images.githubusercontent.com/1633844/205364298-7f49db47-6916-433a-81f3-6502b61a2227.png)

### System Info

Diffusers version: 0.9.0
OS: Windows 11
GPU: RTX 3090

**Comment by WASasquatch** [comment]
It's a different architecture, that should be expected. Need a new script for v-prediction.

**Comment by thojmr** [comment]
> It's a different architecture, that should be expected. Need a new script for v-prediction.

Take a look at this merge first https://github.com/huggingface/diffusers/pull/1511

**Comment by d8ahazard** [comment]
> Please try my version posted here: [convert_diffusers_to_original_stable_diffusion_v2.py](https://github.com/lawfordp2017/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion_v2.py)

No such luck. Were you compiling diffusers from the hub, or extracted checkpoint.

**Comment by d8ahazard** [comment]
Ah, that could be my issue then. I'll double-check with the hub version and see if that creates a valid checkpoint. Then I've got at least half the battle won. ;)

**Comment by nerdyrodent** [comment]
Script worked here - thanks :)

**Comment by lawfordp2017** [comment]
I've updated so both directions should work now for the 768-v model.  Will add other models later.

**Comment by patrickvonplaten** [comment]
We'd be happy about a PR to add this new conversion :-)

**Comment by lawfordp2017** [comment]
I'll try to create one later today.

**Comment by patrickvonplaten** [comment]
Just merged your PR, sorry for the delay :pray: 

Super nice that you put in the effort @lawfordp2017 :-)

**Comment by salieri** [comment]
@lawfordp2017 Question -- applying your script (thanks -- it's awesome!) after training/fine-tuning SD2 works well with [webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui), but only when using [`--no-half`](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings) command line option. If I'm reading this correctly, it means that GPU calculations are done with `fp32`, which is slower.

Do you see any way to adjust the script so that it would support WebUI's half mode too? I tried using `fp16` and `bf16` precision during training, but that had no effect on how the converted checkpoint operates.
