### ISSUE TITLE
StableDiffusionMegaPipeline Not Working with stabilityai/stable-diffusion-2-base

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#1538]
### Describe the bug

custom_pipeline="stable_diffusion_mega" used with stable diffusion 2 not working

```
pipe = DiffusionPipeline.from_pretrained(
               "stabilityai/stable-diffusion-2-base", 
               custom_pipeline="stable_diffusion_mega",
                torch_dtype=torch.float16, revision="fp16"
            ).to("cuda")
```

It gives error :

ERROR:root:Error loading model Pipeline <class 'diffusers_modules.git.stable_diffusion_mega.StableDiffusionMegaPipeline'> expected {'scheduler', 'tokenizer', 'feature_extractor', 'vae', 'unet', 'safety_checker', 'text_encoder'}, but only {'scheduler', 'unet', 'tokenizer', 'vae', 'text_encoder'} were passed.

Many community pipelines has problems with new versions of diffusers and stable diffusion.
lpw_stable_diffusion is also not working, @patil-suraj @patrickvonplaten 

### Logs

```shell
ERROR:root:Error loading model Pipeline <class 'diffusers_modules.git.stable_diffusion_mega.StableDiffusionMegaPipeline'> expected {'scheduler', 'tokenizer', 'feature_extractor', 'vae', 'unet', 'safety_checker', 'text_encoder'}, but only {'scheduler', 'unet', 'tokenizer', 'vae', 'text_encoder'} were passed.
```

### System Info

Name: diffusers
Version: 0.9.0
Summary: Diffusers

**Comment by Skquark** [comment]
I'm having issues with SD2 using a few of the schedulers, but that error you got can be fixed by setting feature_extractor = None and it'll work, but I'd still call that a bug.  The other correction that needs to be made to all the community pipelines is in enable_attention_slicing to calculate slice_size.  To make a correction to the community pipelines, I found that it doesn't update from the git, so you need to upload the mega pipeline.py to your HuggingFace models and load it with custom_pipeline="name/stable_diffusion_mega" until the official ones get updated.  Had to do that with all 5 of the community pipes I was using.

**Comment by patil-suraj** [comment]
Thanks a lot for the issue. This is because the `safety_checker` is not included in the SD2. @patrickvonplaten we should add `requires_safety_checker`  to all community pipelines to make them work with SD2.


@Skquark what issues are you having with schedulers ? almost all schedulers now support v-prediction and should be compatible with all SD2 models. You'll need to install `diffusers` from `main` for that. These changes will be included in the next release. If you still have issues after updating diffusers to `main`. Feel free to open another issue :)

**Comment by patrickvonplaten** [comment]
Updating the "mega" pipeline!

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/pull/1561/files
