### ISSUE TITLE
Dimension of `encoder_hidden_state` in UNet2DConditionModel

### ISSUE THREAD

**Issue by AlienKevin** [huggingface/diffusers#1551]
I'm trying to train my own img2img pipeline guided by a custom text embedding. Currently, I'm using diffusion on pixel space directly. When I looked at the inputs to the [call function of the StableDiffusionImg2ImgPipeline](https://github.com/huggingface/diffusers/blob/6b02323a602a66841729c3a5d60844b24aa81ff2/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L593), I noticed that a `text_embedding` is passed as the `encoder_hidden_state` to the conditioned U net. After checking the [documentation on UNet2DConditionModel](https://huggingface.co/docs/diffusers/api/models#diffusers.UNet2DConditionModel.forward.encoder_hidden_states), it seems that `encoder_hidden_states` has the same dimension as the `sample` image, being (batch, channel, height, width). In my case, my images have the dimension of 128 by 128 pixels while my custom text embedding is a 1D array with length 130. How do I reshape the embedding to fit 128x128 when it has a much smaller dimension?

**Comment by pcuenca** [comment]
Hi @AlienKevin! There was actually a bug in the doc strings documentation for `encoder_hidden_states`, which has just been fixed in [this PR](https://github.com/huggingface/diffusers/pull/1554). The updated documentation is now [here](https://huggingface.co/docs/diffusers/main/en/api/models#diffusers.UNet2DConditionModel.forward.encoder_hidden_states) – you need to select `MAIN` in the dropdown list in the top left area of the window until we release a new PyPi version.

Hope that helps, and sorry for the trouble!

**Comment by AlienKevin** [comment]
Thanks! That really cleared up the image for me. If I understand correctly, the `feature_dim` would be 130 in my case and the batch size will be the same as the sample images. However, what does the `sequence_length` mean here?

**Comment by pcuenca** [comment]
In the case of Stable Diffusion, for instance, the `sequence length` is `77`, which is the fixed length of the tokenized string. The `feature_dim` is `768`, which is the size of the embedding vector for each of those tokens. So the shape is `(bs, 77, 768)`.

I don't know the semantics of your particular use case, maybe you could use something like `(bs, 1, 130)`?

**Comment by AlienKevin** [comment]
I see, that makes sense. Thank you.
