### ISSUE TITLE
Minor inconsistency for scheduler in the example for stable-diffusion-2-1

### ISSUE THREAD

**Issue by woctezuma** [huggingface/diffusers#1666]
In [the example for `stabilityai/stable-diffusion-2-1`](https://huggingface.co/stabilityai/stable-diffusion-2-1#examples), you mention that:

> if you don't swap the scheduler it will run with the default DDIM,
> **in this example we are swapping it to EulerDiscreteScheduler**

This also appears in a comment in Python code in the example.

```python
# Use the Euler scheduler here instead
```

However, in practice, you use the `DPMSolverMultistepScheduler`.

```python
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler

model_id = "stabilityai/stable-diffusion-2-1"

# Use the Euler scheduler here instead
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
```

It is a minor inconsistency, but it is slightly confusing: is `DPMSolverMultistepScheduler` recommended over `EulerDiscreteScheduler`? Indeed, for `stable-diffusion-2`, `stable-diffusion-2-base` and `stable-diffusion-2-1-base`, the scheduler is always swapped to `EulerDiscreteScheduler` [in the example](https://huggingface.co/stabilityai/stable-diffusion-2-1-base#examples). Why was it changed for this example specifically?

**Comment by pcuenca** [comment]
Hi @woctezuma! Thanks for reporting this, I just fixed the inconsistency in the model card.

I believe the reason for the confusion was that at the time of writing the model card, the Euler discrete scheduler did not yet support "v prediction", which is the training objective used by the 768x768 versions of Stable Diffusion. Therefore, it wouldn't work.

The Euler scheduler has since been adapted, so it should now work too. The use of a different scheduler is usually a matter of preference and experimentation. The advantage of DPMSolverMultistepScheduler is that it's one of the most recent schedulers and is capable of producing good quality results in fewer steps. We usually run it with 25 steps instead of the 50 used by default for other schedulers. (This is not shown in the model card example, though).

**Comment by woctezuma** [comment]
Thank you for the detailed reply! This is much appreciated!
