### ISSUE TITLE
Opt-in telemetry (or remove telemetry)

### ISSUE THREAD

**Issue by hlky** [huggingface/diffusers#1683]
Telemetry should be opt-in, or simply removed.

**Comment by patrickvonplaten** [comment]
I think #1685 is fixed - thanks a lot for spotting it.

Maybe some comments on telemetry. The only reason we have added this is to know what pipelines are actually used and what pipelines aren't. Pipelines that aren't used by anybody don't require as much care as pipelines that are heavily used. This is an extremely important signal for maintainers to build a library that stands the test of time and is most useful for the users. We're not logging any important information besides the pipeline class. I hope this makes sense.

That being said, if the majority of the diffusers community wants to have the telemetry disabled, then we can also remove this part of the code! Just want to make sure, people understand that this means => it's more difficult for maintainers to decide what pipeline is important => highly used pipelines might not be as actively maintained as they would have been otherwise.

cc @anton-l

**Comment by patrickvonplaten** [comment]
Ok let's roll this feature back then, seems like there is a major discontent and it's not crucial for the library.

Personally, I underestimated a bit the importance a feature addition like: #1461 has to the community - sorry :pray:

**Comment by patrickvonplaten** [comment]
Closing this as telemetry has been removed. Thanks @anton-l
