### ISSUE TITLE
Language support and contribution to docs

### ISSUE THREAD

**Issue by seriousran** [huggingface/diffusers#1779]
I would like to contribute to translating the documentation into Korean.

It seems that there is a version and language selection in the docs, but only EN is currently supported.

Please let me know if there is any possibility or way to contribute with translation.

**Comment by patrickvonplaten** [comment]
Hey @seriousran,

This would be very nice! Korean would then be the first external language we'd support :-) 

To do the change, we should add a folder structure here: https://github.com/huggingface/diffusers/tree/main/docs/source

just like we do in `transformers`: https://github.com/huggingface/transformers/tree/main/docs/source

So we could add two folder there then, one `en` and put all the existing docs there and then `ko` for Korean

The doc-builder/doc-viewer should be able to tackle this, otherwise I'm happy to help :-)
