### ISSUE TITLE
Is there a way when calling .from_pretrained() to download either the safetensor or original instead of both?

### ISSUE THREAD

**Issue by ethansmith2000** [huggingface/diffusers#1873]
Not a massive issue, but I'm pretty low on storage space on my device. I'm fine with either version, just both eats into my storage and internet plan quickly

**Comment by pcuenca** [comment]
Hi @ethansmith2000! There was a bug where both the safetensors and PyTorch files were downloaded if the repo contained safetensors versions of just some files, but not all. This should have been fixed in #1836, so everything should work fine if you install diffusers from github. Please, do let us know if that's the case :)

**Comment by patrickvonplaten** [comment]
Also a bit related to: https://github.com/huggingface/diffusers/pull/2123

**Comment by patrickvonplaten** [comment]
But since `diffusers >= 0.12.0` there should never be a case where both checkpoints are downloaded
