### ISSUE TITLE
DPM++ SDE variant

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#1889]
### Model/Pipeline/Scheduler description

It looks like there is a variant of the very nice DPM++ scheduler on k-diffusion, see here: https://github.com/crowsonkb/k-diffusion/blob/5b3af030dd83e0297272d861c19477735d0317ec/k_diffusion/sampling.py#L543 

It would be nice to add this one to `diffusers` as well.

Also gently pinging the author of DPM++ @LuChengTHU (have you played around with a stochastic variant of your scheduler as well?)

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by LuChengTHU** [comment]
Theoretically speaking, I don't think the implementation of the SDE-variant of DPM-Solver / DPM-Solver++ in k-diffusion is correct :(  It is not corresponding to the reverse diffusion SDE, though it can provide beautiful images (because diffusion models are "tolerant" to SDE solvers).

I've implemented the DPM-type SDE solver in this PR: https://github.com/huggingface/diffusers/pull/3344

**Comment by patrickvonplaten** [comment]
Perfect! Much nicer that we have the "official" version from you now @LuChengTHU :-)

**Comment by a-r-r-o-w** [comment]
Marking as closed because this is supported now, thanks :)
