### ISSUE TITLE
Reproducibility improvement of SD generation with xFormers

### ISSUE THREAD

**Issue by takuma104** [huggingface/diffusers#1997]
I wrote a patch related to #1339. This patch makes xFormers use Flash Attention as a priority. More details to see: [Generating (almost) reproducible pictures using Diffusers with xFormers](https://gist.github.com/takuma104/9d25bb87ae3b52e41e0132aa737c0b03)

![fig_xformers_flash_attention_seed_7](https://user-images.githubusercontent.com/10776/212374658-1975eb51-b6ad-412f-bd31-6beb2e9b83d1.png)

https://github.com/huggingface/diffusers/compare/main...takuma104:diffusers:force_xformers_flash_attention

I would like to get some feedback.
- Is it worth opening a PR?
- I have put an argument to enable_xformers_memory_efficient_attention() to specify if this patch is enabled or not, is there a better way to specify it?
- Any other advice?

**Comment by patrickvonplaten** [comment]
I think I would be fine with adding a "use_flash_attention=True/False" argument to `enable_xformers_memory_efficient_attention()` - @patil-suraj @pcuenca what do you think?

**Comment by patil-suraj** [comment]
I am fine with this, but I think instead of a boolean like `use_flash_attention` we could let the user directly pass the `xformers `op like `xformers.ops.MemoryEfficientAttentionFlashAttentionOp` or `xformers.ops.TritonFlashAttentionOp`, this way the user can choose whatever they want.  This will also keep the code simple. I have wip implem here https://github.com/huggingface/diffusers/compare/xformers-attenion-op-arg, feel free to use it and open a PR.

**Comment by takuma104** [comment]
Thank you for the advices and code! I’ll merge it and open a PR this weekend.
