### ISSUE TITLE
Is num_inference_steps the same as Sampling Steps?

### ISSUE THREAD

**Issue by athenawisdoms** [huggingface/diffusers#2065]
is `num_inference_steps` parameter of `StableDiffusionPipeline` refering to the same thing as in the "sampling steps" option in auto1111's?

I get much better results using 20 sampling steps in auto1111 than `num_inference_steps=20` in `StableDiffusionPipeline`

**Comment by pcuenca** [comment]
Hi @athenawisdoms, it's essentially the same thing, yes.

The quality of generation depends on the scheduler (or "sampler") you are using and on all configuration parameters. In order to compare results, it'd be helpful to try to use the same schedulers in both systems. What scheduler are you using in Automatic1111?
