### ISSUE TITLE
Is it possible to retrain again dream booth's result?

### ISSUE THREAD

**Issue by YJ-142150** [huggingface/diffusers#2148]
Hi, thank for your great work.
I trained stable-diffusion-2-1 four times in a row. Like, 
```
export MODEL_NAME="stabilityai/stable-diffusion-2-1"
export INSTANCE_DIR="teddy" --prompt "xyz"
export OUTPUT_DIR="save_model"
accelerate launch train_dreambooth.py
export MODEL_NAME="save_model"
export INSTANCE_DIR="apple" --prompt "wpz"
accelerate launch train_dreambooth.py
```
However, it seemed output of the serial train commands can only save last train like
```
export MODEL_NAME="save_model"
export INSTANCE_DIR="apple" --prompt "wpz"
accelerate launch train_dreambooth.py
```
Is it hard to train multiple types of images in a row with dream booth?

**Comment by patrickvonplaten** [comment]
Hey @YJ-142150, sorry I don't fully understand the question here - could you try to specific a bit? 

Also cc @patil-suraj

**Comment by YJ-142150** [comment]
I trained Dream booth for multiple times with different image sets for each training. 
For example, firstly, I trained stabilityai/stable-diffusion-v2-1 with teddy bear images. 
And then secondly, I trained the output model of dream booth, which is save_model, with apple images & different text prompt. 
After the trainings, I ran the save_model to generate teddy bear images with the prompt that I used for the first training. 
However, the result image showed only apple images, which was from second training. It seemed that dream booth memorizes only last training when I train for multiple times with same save_model(dream booth output directory).

**Comment by patil-suraj** [comment]
I think training in series like that might not work since we train the model on a specific set of images, it's highly possible that it could forget about previously learned dreambooth concepts. There are two other ways of doing this

- You could try this script which allows you to simultaneously train using multiple concepts https://github.com/huggingface/diffusers/tree/main/examples/research_projects/multi_subject_dreambooth
- Or you could use LoRA, which adds some new weights for each concept and only those specific weights are trained which only take ~3MB, so you could have different lora weights for different concepts and easily swap them during inference, more info can be found in docs https://huggingface.co/docs/diffusers/training/lora

**Comment by YJ-142150** [comment]
I didn't know that there was multi_subject_dreambooth. Thanks for answering the question!
