### ISSUE TITLE
Textual inversion captioning

### ISSUE THREAD

**Issue by jndietz** [huggingface/diffusers#2323]
In the examples, are we able to provide captions for textual inversion trainings or are we limited to the placeholder and initializer tokens?  If I put `<image-name>.txt` in the training folder are they used?  If not, is there any guidance or documentation on how to extend it?

**Comment by patrickvonplaten** [comment]
cc @williamberman

**Comment by williamberman** [comment]
hey @jndietz! That is correct, we provide the placeholder and initializer tokens as the means of image captioning, and no we don't do anything with file names to determine captions.

We try to keep the training scripts relatively simple and self contained rather than supporting a large variety of options so that they are manually modifiable if necessary. If you'd like to customize how image captions are selected (e.g. using the file name), that should be a small code change to the TextualInversionDataset

https://github.com/huggingface/diffusers/blob/9e8ee2ace16f485c0e4cb212af43f178d5f84522/examples/textual_inversion/textual_inversion.py#L368-L451

If we do see increased demand for alternative ways to provide captions to the textual inversion training script, we'd be more than happy to add some. In the meantime, if you'd like to add some yourself and think other community members would benefit, we're also open to merging script variations under examples/community or examples/research_projects :)

LMK if that answers your questions! :)

**Comment by jndietz** [comment]
Awesome, thanks a ton for the explanation!

**Comment by williamberman** [comment]
Of course, thank you for the issue 😁 !

**Comment by jndietz** [comment]
@williamberman  Can you give me a hint where I might change the vectors per token too?

**Comment by jndietz** [comment]
Also, this should work fine, right?

```python
        image_path = self.image_paths[i % self.num_images]
        image = Image.open(image_path)

        if not image.mode == "RGB":
            image = image.convert("RGB")

        # placeholder_string = self.placeholder_token
        # text = random.choice(self.templates).format(placeholder_string)
        filename = os.path.basename(image.filename)
        text = re.sub("(_[\d]*.png)", "", filename) # strip off an ending underscore and digits plus the .png extension
```

**Comment by jndietz** [comment]
Also would the captions from the filenames need to be tokenized with `tokenizer.convert_tokens_to_ids([...])`?
