### ISSUE TITLE
pytorch2.0 rocm torch.compile gives RuntimeWarning and generated black images

### ISSUE THREAD

**Issue by ttio2tech** [huggingface/diffusers#2758]
I was testing the https://huggingface.co/docs/diffusers/optimization/torch2.0 examples, 
The normal 'Accelerated Transformers implementation' was successful. 
But the torch.compile example:
pipe.unet = torch.compile(pipe.unet)
image = pipe(prompt).images[0]
gives warning:
pipelines/pipeline_utils.py:1023: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")
Resulting in black images.

**Comment by sayakpaul** [comment]
Does this happen for all prompts you tried so far?

@patrickvonplaten @pcuenca Cc.

**Comment by Stax124** [comment]
This bug happens in the UNet step and it differs from sampler to sampler. It takes input latent in correct format, but throws out tensor of the same shape full of NANs. From my testing, this happens quite often with DPM samplers, while EulerA is quite stable.

**Comment by sayakpaul** [comment]
Hmm. Could you ensure you're on the latest Torch 2.0 install?

**Comment by Stax124** [comment]
Im a VoltaML developer, we are using Stable release of Pytorch 2.0 with CUDA 11.8, in containerized environment, so nothing should interfere.

**Comment by sayakpaul** [comment]
I will let @pcuenca comment here.

**Comment by patrickvonplaten** [comment]
@ttio2tech ,

could you add a reproducible code snippet here?

**Comment by ttio2tech** [comment]
The code that caused the error:
# environment: ROCm 5.4.2 Pytorch 2.0
import torch
from diffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained("hakurei/waifu-diffusion", torch_dtype=torch.float16).to(
    "cuda"
)
pipe.unet = torch.compile(pipe.unet) # this step gave error

**Comment by sayakpaul** [comment]
Does it give warning or error?

If it's an error, it could be because of dependency problems. Could you post the error snippet?

**Comment by patrickvonplaten** [comment]
Also seeing this problem a bit now - @pcuenca , @patil-suraj did you ever encounter this?

**Comment by pcuenca** [comment]
I'm confused, the issue title and @ttio2tech mention a ROCm environment, but @Stax124 says they are using CUDA. Does this issue only apply to ROCm/AMD cards, or is this a general problem with torch 2?

I haven't seen it myself, but will test the model mentioned by @ttio2tech (on CUDA, unfortunately I have no AMD cards compatible with ROCm).

**Comment by onitake** [comment]
It's a bit hard to produce a minimal example due to the various dependencies involved, but I think I've been able to narrow the issue down a bit.
I'm running diffusers 0.16.1 with a custom build of PyTorch 2.1 against ROCm 5.5.0 (currently needed for gfx1100/RDNA3/RX7xxx support).
FP32 works fine in all cases, but with FP16 I get the NaN issue when using the model https://huggingface.co/waifu-diffusion/wd-1-5-beta2. With https://huggingface.co/hakurei/waifu-diffusion, FP16 is ok as well.

I've attached a dump of the pipelines and a diff here: https://gist.github.com/onitake/1534ea2eedecb5d346fc70ba2a278d81

What stands out to me is that the working pipeline (WD-1.4) uses `CLIPImageProcessor` while the non-working one (WD-1.5) uses `CLIPFeatureExtractor`, and that WD-1.4 sets `PNMDScheduler.prediction_type='epsilon'`, while in WD-1.5 it's `PNMDScheduler.prediction_type='v_prediction'`.

Does that help?

**Comment by onitake** [comment]
I traced a failed run through to https://github.com/huggingface/diffusers/blob/v0.16.1/src/diffusers/models/attention_processor.py#L743

This will produce some NaN values in the result, and as soon as that happens, they'll quickly propagate through the whole hidden_states tensor at the end of the iteration.

**Comment by onitake** [comment]
After experimenting with https://pytorch.org/docs/main/generated/torch.nn.functional.scaled_dot_product_attention.html a bit, I found that my Torch build only includes the C++ implementation. Maybe this is the problem.

Unfortunately, there doesn't seem to be a ROCm implementation of the [FlashAttention](https://github.com/HazyResearch/flash-attention) algorithm yet. AMD is still working on it: https://github.com/ROCmSoftwarePlatform/flash-attention/pull/1

**Comment by onitake** [comment]
In any case, I found that I can hide the issue by adding the following line after the `F.scaled_dot_product_attention()` call:
```python
hidden_states = torch.nan_to_num(hidden_states)
```
It didn't look like it had much of a performance impact on my machine. The algorithm ran at about the same speed as WD-1.4 without this line.

**Comment by sayakpaul** [comment]
Thanks for sharing your details insights here. If this issue comes up multiple times, I think we might fix with the following (referring users to this issue thread):

```python
torch.nan_to_num(hidden_states)
``` 

But if this behavior could be reproduced minimally with just vanilla PyTorch code on your setup, that'd probably be more helpful for the PyTorch to understand the lower-level reasons behind this.

**Comment by vedmant** [comment]
I have the same issue on M1 with https://huggingface.co/stabilityai/stable-diffusion-2-1 model
