### ISSUE TITLE
[UNet3DConditionModel] implement rest of the test cases (LoRA, Slow tests)

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#2789]
For the LoRA and other attention-block related tests, we need to have `attn_processors` implemented for the `UNet3DConditionModel`. 

`tests/models/test_models_unet_3d_condition.py` has sufficient comments about these.

**Comment by Pie31415** [comment]
I can work on these tests if no one else is taking it on atm.

**Comment by sayakpaul** [comment]
That would be awesome. Feel free to work on it :)

**Comment by Pie31415** [comment]
@sayakpaul 
I've copied over the LoRA tests for unet_2d_condition_py but have been getting errors related to undefined hidden_size from the below code (a snippet of one of the tests):
```python
init_dict, inputs_dict = self.prepare_init_args_and_inputs_for_common()

init_dict["attention_head_dim"] = 4

model = self.model_class(**init_dict)
model.to(torch_device)

with torch.no_grad():
    sample1 = model(**inputs_dict).sample
lora_attn_procs = {}
for name in model.attn_processors.keys():
    cross_attention_dim = None if name.endswith("attn1.processor") else model.config.cross_attention_dim
    if name.startswith("mid_block"):
        hidden_size = model.config.block_out_channels[-1]
    elif name.startswith("up_block"):
        block_id = int(name[len("up_blocks.")])
        hidden_size = list(reversed(model.config.block_out_channels))[block_id]
    elif name.startswith("down_blocks"):
        block_id = int(name[len("down_blocks.")])
        hidden_size = model.config.block_out_channels[block_id]

    lora_attn_procs[name] = LoRAAttnProcessor(hidden_size=hidden_size, cross_attention_dim=cross_attention_dim)
```
The problem seems to be that model.attn_processors.keys() returns some layers that aren't mid_block, up_block or  down_blocks but instead have a prefix of transfomer_in (i.e. transformer_in.transformer_blocks.0.attn1.processor, transformer_in.transformer_blocks.0.attn2.processor). I'm not quite sure what these layers are and how to treat them so I was wondering if you'd have some advice.

**Comment by sayakpaul** [comment]
@patrickvonplaten

**Comment by patrickvonplaten** [comment]
@Pie31415 should we discuss right away on #2824 ?

**Comment by Pie31415** [comment]
> @Pie31415 should we discuss right away on #2824 ?

Of course!

**Comment by sayakpaul** [comment]
Done with https://github.com/huggingface/diffusers/pull/2824/
