### ISSUE TITLE
ControlNet + OffsetNoise + LoRA

### ISSUE THREAD

**Issue by pure-rgb** [huggingface/diffusers#2868]
**Is your feature request related to a problem? Please describe.**
https://www.reddit.com/r/StableDiffusion/comments/11fsdtq/controlnet_offsetnoise_lora_stable_diffusion_30/

Diffusers doesn't support LoRA with control-net yet. And OffsetNoise anywhere.

[Illustration](https://preview.redd.it/bgxgf60ddhla1.png?width=2000&format=png&auto=webp&v=enabled&s=dbd58324131bfac5d92f82895cd6a8bf03b10c51)

**Comment by pure-rgb** [comment]
https://github.com/HighCWu/ControlLoRA

**Comment by pure-rgb** [comment]
@takuma104 thanks. what about OffsetNoise? Have it resolved also?

**Comment by takuma104** [comment]
The LoRA file format for Diffusers is specific to Diffusers. For LoRA weights not trained with Diffusers, we can use the script #2403 to apply the LoRA weights to a Diffusers model. 

Using this, I tried applying [the NoiseOffset LoRA weights](https://civitai.com/models/13941/epinoiseoffset) to [dreamlike-art/dreamlike-anime-1.0](https://hf.co/dreamlike-art/dreamlike-anime-1.0). The usage of ControlNet is the same as the general usage, with no significant differences.

```py
import torch
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel
from diffusers import EulerAncestralDiscreteScheduler
from diffusers.utils import load_image

canny = ControlNetModel.from_pretrained('lllyasviel/sd-controlnet-canny', torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained('dreamlike-art/dreamlike-anime-1.0', 
    torch_dtype=torch.float16,
    safety_checker = None,
    controlnet=canny,
)
pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)
pipe = pipe.to('cuda')

canny_cond = load_image('https://huggingface.co/takuma104/controlnet_dev/resolve/main/gen_compare/control_images/converted/control_vermeer_canny.png')
image = pipe(prompt="masterpiece, best quality",
    num_inference_steps=30, guidance_scale=7.5,
    generator=torch.manual_seed(0), width=512, height=512, 
    image=canny_cond).images[0]
image.save('generated.png')
```

The generated result:
<img width='256' src='https://user-images.githubusercontent.com/10776/228618341-268bff5c-90e8-4d65-b74e-88f351ecab2d.png'/>


By specifying the folder of the converted local model for `from_pretrained`, we can achieve the following results. It turns out quite cool, doesn't it! :)

<img width='256' src='https://user-images.githubusercontent.com/10776/228618378-f69c3105-b879-4533-937e-be4e9f77257a.png'/>

The script `alpha=` argument can be adjusted, and the default 0.75 seemed to have a slightly weak effect, so I set it to 1.5. The script will look like this:

```sh
$ python scripts/convert_lora_safetensor_to_diffusers.py --base_model_path dreamlike-art/dreamlike-anime-1.0 --checkpoint_path epi_noiseoffset.safetensors --dump_path /tmp/epi_noiseoffset_dreamlike --alpha=1.5
```

**Comment by takuma104** [comment]
> Also, this https://github.com/huggingface/diffusers/issues/2714 shows how to load lora weight but would it be possible to add this in training time, just [like](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py) ?

I'm not quite sure about the use case, but are you looking to apply LoRA while training the ControlNet?

If not, and you want to create a LoRA with NoiseOffset applied, we can follow [this blog post](https://www.crosslabs.org/blog/diffusion-with-offset-noise). We can modify [this part of the script](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py#L881)  as suggested in the blog.

**Comment by pure-rgb** [comment]
@takuma104 Thanks a lot. 

> .. are you looking to apply LoRA while training the ControlNet?

kind of, as it is stated id [doc](https://huggingface.co/docs/diffusers/main/en/training/lora#lowrank-adaptation-of-large-language-models-lora), 

> [Low-Rank Adaptation of Large Language Models (LoRA)](https://arxiv.org/abs/2106.09685) is a training method that accelerates the training of large models while consuming less memory.

Please redirect me if I've missed something.
