### ISSUE TITLE
segment anything model for text-guided image editing

### ISSUE THREAD

**Issue by feizc** [huggingface/diffusers#3019]
### Model/Pipeline/Scheduler description

Use recently release segment anything model (SAM) to support image editing. 
Specifically, SAM support click or text to segment the target region, which is used to create mask image for image editing.
Compared with plot-based, its interactive form is more intelligent and convenient. 

Code reference: 
https://github.com/feizc/IEA 
https://github.com/IDEA-Research/Grounded-Segment-Anything
https://github.com/facebookresearch/segment-anything

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by jasonborn0** [comment]
This is a cool idea. It looks like the first repo is using CLIP+SAM, and according to some anecdotal evidence, this architecture does not appear to work too well. I found https://github.com/IDEA-Research/Grounded-Segment-Anything (GroundingDINO+SAM), which claims the inpainting results are better.

**Comment by patrickvonplaten** [comment]
Hey @feizc,

The SAM model is really cool and it's great to see that https://github.com/IDEA-Research/Grounded-Segment-Anything uses it with `diffusers`. We could maybe add a community pipeline to showcase this pipeline. It might however be a bit too high-level to implement as a "core" pipeline. cc @sayakpaul

**Comment by whbzju** [comment]
> Hey @feizc,
> 
> The SAM model is really cool and it's great to see that https://github.com/IDEA-Research/Grounded-Segment-Anything uses it with `diffusers`. We could maybe add a community pipeline to showcase this pipeline. It might however be a bit too high-level to implement as a "core" pipeline. cc @sayakpaul

glad to here any new progressing?

**Comment by patrickvonplaten** [comment]
cc @sayakpaul would be nice to have such a community pipeline / hf agent tool

**Comment by sayakpaul** [comment]
I am not aware of a community pipeline yet. But it should be possible to extend [this notebook](https://colab.research.google.com/github/IDEA-Research/GroundingDINO/blob/main/demo/image_editing_with_groundingdino_stablediffusion.ipynb) to an HF agent tool.

**Comment by patrickvonplaten** [comment]
Hey @andysingal,

I really appreciate your motivation, but many of the issues that you post are far away from issue reporting, but sound more like seeking help for personal projects. 

The issue tracker of open-source libraries should ideally only be used for issue reporting so that the library can improve. At the moment your issues take too much attention way from the core maintainers (who have to review 200+ issues / comments every day) from issues that improve the library.

Could you please try to instead use the forum: https://discuss.huggingface.co/ or discord: https://discord.com/invite/G7tWnz98XR for such questions?
