### ISSUE TITLE
Create a Video ControlNet Pipeline

### ISSUE THREAD

**Issue by jfischoff** [huggingface/diffusers#3075]
**Is your feature request related to a problem? Please describe.**
Stable Diffusion video generation lacks precise movement control and composition control. This is not surprising, since the model was not trained or fine-tuned with videos. 

**Describe the solution you'd like**
By following an analogous extension process that gave Stable Diffusion more composition control with ControlNet, we can address this issue, extending the `TextToVideoZeroPipeline` with an additional ControlNet guidance image  _sequence_. 

Specifically, I believe this will involve creating `ControlNet3DModel` that extends to the `ControlNetModel` to provide the proper down and mid sample residuals to the a new `TextToVideoZeroControlNetPipeline`.

The `TextToVideoZeroControlPipeline` will extend the `TextToVideoZeroPipeline` so it can be initialized `ControlNet3DModel`. During the forward pass we will add an additional list of images (or 3D tensor) parameter. This will be passed to the `ControlNet3DModel` to create the residuals for the 3D U-Net. 

**Describe alternatives you've considered**
Alternative one can create special purpose pipelines to use additional guidance image sequences. An example of this process is the "Follow Your Pose" approach: https://follow-your-pose.github.io/

However, extending a Stable Diffusion video pipeline with a `ControlNet3DModel` opens the door to numerous possible other extensions without the need to make a new pipeline. For example:

- A sketch temporal ControlNet would let users turn sketches to colored animations
- A optical flow ControlNet could transfer movement in a similar way to EBSynth
- A pose ControlNet could precisely control the movement of characters in a video.

**Additional context**
This is idea is part of the JAX/ControlNet sprint for the "Stable Diffusion for Animation" project. I was hoping that our work could lead to a PR that is acceptable for the repo, so I wanted to get a conversation going on the approach. 

Tagging the maestro @takuma104 to get your thoughts as well.

**Comment by un1tz3r0** [comment]
Yes. I am all for this i think it's exactly what we need. Think even more flexible though. What if we had a framework for building controlnets with any number of distinct control channels, of arbitrary dimensionality. a 1d or 2d signal input for framerate would allow training a temporal controlnet on variable frame rates, and allow controlling the frame rate and motion of the generated images. 3d input control channels could provide windowed frames as outlined above, to learn to produce output that is more temporally stable. you could even train on spectral grains of audio tracks associated with training images taken from video datasets to produce lip-synched output directly from speech or rhythmic or otherwise sound-track synched animation coreography. i like where this is going, how would a flexible variable number of variable shape control channels all merged in one controlnet block that connects to the unet in the usual way work? @patrickvonplaten @jfioschoff @takuma104

**Comment by jfischoff** [comment]
Closing. I realize now how ControlNet's are meant to be used with this pipeline. It is in the doc but was not clear from the code.

**Comment by takuma104** [comment]
Hi! Applying ControlNet to videos sounds fun indeed! I haven't been able to keep up with the Text2Video trends, so I'll study more about it. The [Text2Video-Zero paper](https://arxiv.org/abs/2303.13439), seems to be considering the use of ControlNet. Is the discussion about implementing Chapter 3.4 of this paper?

Also, I'm not sure if it's relevant, but here's something I know about ControlNet+Video:

- [TemporalNet](https://huggingface.co/CiaraRowles/TemporalNet): It seems to be an application for Video2Video. I don't understand the mechanism ifself. The output is indeed impressive. https://twitter.com/CiaraRowles1

- Today, ControlNet v1.1 was released, and it seems that [the new InPaint model](https://github.com/lllyasviel/ControlNet-v1-1-nightly#controlnet-11-inpaint) is also designed with video applications in mind.
> This means the model can not only support the inpainting application but also work on video optical flow warping.
