### ISSUE TITLE
Custom encoder for conditioning instead of text-based encoder.

### ISSUE THREAD

**Issue by nanlliu** [huggingface/diffusers#3111]
**Is your feature request related to a problem? Please describe.**
Is there anyway that we can load custom encoder instead of text encoder?

**Describe the solution you'd like**
I guess essentially, we can potentially have an abstract class that people can build a custom encoder on top of that, for example, class embedder. Then we can utilize .pretrained method to load any arbitrary custom embedder.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gunshi** [comment]
Hi,
I had a clarifying question based off off the above question: If we didn't want to load the custom encoder _in place_ of the clip text encoder but alongside it, to be able to add some arbitrary input or embedding to the Unet, that _is_ currently supported right? I got the impression that it is from my reading of the code [here](https://github.com/huggingface/diffusers/blob/48664d62b8e9f70d03b1be4059c1464a3b167f85/src/diffusers/models/unet_2d_condition.py#L862) but please do correct me if that variable is meant for something else entirely.

I suppose here since this is expected as a dictionary key-value pair, we wouldn't load the encoder but precompute the encoding (for example if we wanted to additionally get BERT embeddings then we would compute those in the pipeline_xyz.py or the train.py script, and pass that into the forward method of the stable diffusion class, is that correct?
