### ISSUE TITLE
Training-Free Layout Control with Cross-Attention Guidance

### ISSUE THREAD

**Issue by nipunjindal** [huggingface/diffusers#3113]
### Model/Pipeline/Scheduler description

Hey Team,

I have added a [diffusers-based pipeline](https://github.com/nipunjindal/diffusers-layout-guidance) for [Training-Free Layout Control with Cross-Attention Guidance](https://arxiv.org/abs/2304.03373) based on original work [here](https://github.com/silent-chen/layout-guidance). The work is adapted from the original repo and AttendExcite pipeline. I'd be happy to add this as community pipeline/pipeline if others think so.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/nipunjindal/diffusers-layout-guidance
https://github.com/silent-chen/layout-guidance

**Comment by sayakpaul** [comment]
Thanks @nipunjindal! The [results](https://github.com/nipunjindal/diffusers-layout-guidance#image-examples) in your repository look really promising! 

I think adding this as a regular pipeline would be great. @patrickvonplaten WDYT? 

Out of curiosity, from the [example](https://github.com/nipunjindal/diffusers-layout-guidance#how-to-use-training-free-layout-control-guidance-tflcg):

```py
prompt = "A cat playing with a ball"
bboxes = [[0.55, 0.4, 0.95, 0.8]]
image = pipe(prompt, num_inference_steps=20,
             token_indices=[[2]],
             bboxes=bboxes).images[0]
image = pipe.draw_box(image, boxes)
```

What do we provide the `bboxes` for? Is it so that the subject is generated within that region?

**Comment by patrickvonplaten** [comment]
Happy to add it as a regular pipeline!
