### ISSUE TITLE
Loading Lora/Textual inversion and applying custom names to them

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#3155]
Hi, I want to prevent name conflicts so how can I update the name of the concept trained and load it in stable diffusion pipeline?

**Comment by JarvusChen** [comment]
Usually we train our embeding by using `<keyword>` instead of `keyword` to prevent conflict. If you are using this [script](--placeholder_token="<cat-toy>"), try to add the parameter `--placeholder_token` when training, for example:
```
--placeholder_token="<keyword>"
```
Otherwise, you can `load_textual_inversion` with customized token name. Here is the [document](pipe.load_textual_inversion("sd-concepts-library/cat-toy")).
```
pipe.load_textual_inversion("sd-concepts-library/cat-toy", token="<keyword>")
```

**Comment by patrickvonplaten** [comment]
It should yes :-)
