### ISSUE TITLE
Typo in code in documentation docs/source/en/using-diffusers/write_own_pipeline.mdx

### ISSUE THREAD

**Issue by ambisinister** [huggingface/diffusers#3159]
### Describe the bug

Docs has typo in step 6 of "Deconstruct a basic pipeline" https://github.com/huggingface/diffusers/blob/main/docs/source/en/using-diffusers/write_own_pipeline.mdx

image = Image.fromarray((image * 255)).round().astype("uint8")

should be 

image = Image.fromarray((image * 255).round().astype("uint8"))

### Reproduction

```
import numpy as np
from PIL import Image

image = Image.fromarray((np.random.rand(32,32,3) * 255)).astype("uint8")
image2 = Image.fromarray((np.random.rand(32,32,3) * 255).astype("uint8"))
```

### System Info

n/a (documentation)

**Comment by pcuenca** [comment]
Fixed by #3295.

**Comment by manzonif** [comment]
Same error here: https://huggingface.co/docs/diffusers/using-diffusers/write_own_pipeline

**Comment by pcuenca** [comment]
Hi @manzonif! That's the same issue, the problem is that no new release has been made since the fix. If you select `main` in the version popup, you'll see the latest version. By default, the documentation selects the stable version released in PyPi.

<img width="302" alt="Screenshot 2023-06-07 at 09 24 36" src="https://github.com/huggingface/diffusers/assets/1177582/e2383b74-bb8a-4412-8a7a-42bcd4593648">

(We are planning to do a release soon)

**Comment by manzonif** [comment]
I thought it could be like this... sorry.

**Comment by pcuenca** [comment]
No worries! Thanks for reaching out :)
