### ISSUE TITLE
Having a "scale" parameter for text encoder lora layers

### ISSUE THREAD

**Issue by abhijitpal1247** [huggingface/diffusers#3480]
**Is your feature request related to a problem? Please describe.**
No, not related to a problem

**Describe the solution you'd like**
A similar parameter to "scale" of unet lora layers, in case of text encoder lora layers

**Additional context**
This is an inference parameter that will determine the influence of text encoder lora layers on generation

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
This question has come before a few times. 

I am wondering about what would be the best option to support this currently. Here are some thoughts: 

* Pass an additional parameter called `text_encoder_scale` to `load_lora_weights()` as a kwarg. Note that we cannot do it during the runtime (e.g., `pipe("A pokemon with blue eyes.", cross_attention_kwargs={"scale": 0.5})` because of the way LoRA is implemented for the text encoder (using monkey-patching). 
* If the `text_encoder_scale` is passed, then the [monkey patch call](https://github.com/huggingface/diffusers/blob/2f997f30ab660472561f5e1b5232d4f116315b1b/src/diffusers/loaders.py#L950) will be modified maybe like so:

```py
...
text_encoder_scale = kwargs.pop("text_encoder_scale", 1.0)

def new_forward(x):
    return old_forward(x) + lora_layer(x, scale=text_encoder_scale)
```

^ should be fine since `LoRAAttnProcessor` supports the `scale` argument in its `call()`.
* Note that the current monkey-patching implementation has a bug which is fixed here: https://github.com/huggingface/diffusers/pull/3490. Cc: @takuma104 

WDYT @patrickvonplaten?

**Comment by patrickvonplaten** [comment]
Hmm yeah good question! I wonder whether we could do something ugly here: https://github.com/huggingface/diffusers/blob/d4197bf4d72f04d4927ff1e7be2f8ee46efebe47/src/diffusers/loaders.py#L949
```py
                def new_forward(x):
                    return old_forward(x) + lora_layer(x)

                # Monkey-patch.
                module.forward = new_forward
```

could be changed to

```py
                def new_forward(x):
                    return old_forward(x) + self.scale * lora_layer(x)

                # Monkey-patch.
                module.forward = new_forward
```

and then we add a `scale` property to: 
https://github.com/huggingface/diffusers/blob/d4197bf4d72f04d4927ff1e7be2f8ee46efebe47/src/diffusers/loaders.py#L745

```py
@property
def scale(self):
    return self._scale
```

and a scale setter function that we need to call from the `_encode_prompt` method. Could this make sense?

**Comment by sayakpaul** [comment]
Where does `self._scale` come from? The pipeline call?

**Comment by patrickvonplaten** [comment]
Yes `self._scale` is overwritten when calling the pipeline

**Comment by sayakpaul** [comment]
@patrickvonplaten sorry still a bit unclear to me. 

> Yes self._scale is overwritten when calling the pipeline

To enable this we still need to expose an argument corresponding to the text encoder LoRA scale, no?

**Comment by patrickvonplaten** [comment]
@sayakpaul would this help: https://github.com/huggingface/diffusers/pull/3626#issue-1734247255

**Comment by sayakpaul** [comment]
Thanks @patrickvonplaten! I left some comments there.

**Comment by sayakpaul** [comment]
Closing with https://github.com/huggingface/diffusers/pull/3626#issue-1734247255
