### ISSUE TITLE
Can I save just differences of weights between trained model by dreambooth and base model?

### ISSUE THREAD

**Issue by hosein-moayedi** [huggingface/diffusers#3665]
Hey guys!
I have a question.

When we are training a stable diffusion model by dreambooth script with a 15 images of new inctance (like human face), we will save a result that has about 2 or 4 gig size.

My question is, can we save just difference of weights as a result and when we want load that, we will make new stable diffusion pipline with applied this difference to base model?

if we can do it, we will save huge  of resources (storage)

**Comment by hosein-moayedi** [comment]
can you help me guys 😇🙏🏻

@sayakpaul @yiyixuxu @takuma104 @patrickvonplaten

**Comment by adhikjoshi** [comment]
You mean embeddings?

**Comment by hosein-moayedi** [comment]
> You mean embeddings?

no
embedding is concat some layers together however i mean merge all leyers of base model by trained model.
ex: base model is stable diffusion 1.5 that has unet with .bin format and contains layers and all weight with float 32. now we finished the training process by dreambooth and save the new unet in directory.

now I want compare weights of base model with this trained model and just save differences as a trIned model. like 

final weights = base model weight - trained models weights

**Comment by sayakpaul** [comment]
Thanks for posting this. 

Even if you just serialize the delta weights I don't think there will be any size reductions assuming that the number of layers from the model for which you would need to maintain the delta -- this will be the same as well as the numerical precision. 

Currently, we don't have any plans to support this design. Since this issue is not directly related to the codebase of diffusers, I am going to close this issue. Feel free to post this to our discussion forum: 
https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63

Also ccing @cloneofsimo to see if they have got any suggestions.

**Comment by cloneofsimo** [comment]
Thanks for ccing sayak. Ive tackled this exact problem here https://arxiv.org/abs/2305.18425, and working on the out-of-the-box implementation.
