### ISSUE TITLE
controlnet_guidance_start and controlnet_guidance_end is missing in StableDiffusionControlNetImg2ImgPipeline

### ISSUE THREAD

**Issue by Bochu3** [huggingface/diffusers#3758]
In the old community  controlnet img2img pipeline, there are controlnet_guidance_start and controlnet_guidance_end setting

https://github.com/huggingface/diffusers/blob/34d14d78489f82b4abebdb62d90545312171c033/examples/community/stable_diffusion_controlnet_img2img.py#L911-L920

However, controlnet_guidance_start and controlnet_guidance_end is missing in official StableDiffusionControlNetImg2ImgPipeline.
How can I control the starting point of the controlnet in official pipeline?

**Comment by satwiksunnam19** [comment]
Hello @Bochu3 @patrickvonplaten, i think we can add this snippet of code to solve this issue 

 A separed __call__ method overload with a start_conditioning_scale and end_conditioning_scale parameters 
 
class StableDiffusionControlNetImg2ImgPipeline(...):
...

    @overload
    def __call__(
        self,
        ...
        start_conditioning_scale: float,
        end_conditioning_scale: float,
        ...
    ) -> torch.Tensor:
        ...

    ...


pipe(
    # ...
    start_conditioning_scale=0.01,
    end_conditioning_scale=0.1,
    # ...
)

This might add the feature which you're looking for

**Comment by julien-blanchon** [comment]
We can centralize all the effort about conditioning control in this issues: https://github.com/huggingface/diffusers/issues/3759

The @satwiksunnam19 idea is almost like my third implementation idea. 
I personally like the idea of using `@overload` in my project because this make the typing easier and tend to produce simpler function. But this is not very pythonic and not well suported by every IDE. Plus this could be misleading for some people.

Let's continue the discussion on [3759](https://github.com/huggingface/diffusers/issues/3759), so we can figure out the best implementation and make a PR for this

**Comment by sayakpaul** [comment]
Agree with @julien-blanchon here. Would it be okay if we closed this issue and centralize the discussions on #3759, instead?

**Comment by Bochu3** [comment]
Sure, Let's continue this on #3759

**Comment by Bochu3** [comment]
Sure, Let's continue this on #3759
