### ISSUE TITLE
Question about: `ConfigMixin` vs `XYZConfig class`

### ISSUE THREAD

**Issue by mishig25** [huggingface/diffusers#383]
I see that [ConfigMixin](https://github.com/huggingface/diffusers/blob/d799084a9a7d5196ae708da72b46dd8e84604194/src/diffusers/configuration_utils.py#L38) & [@register_to_config](https://github.com/huggingface/diffusers/blob/d799084a9a7d5196ae708da72b46dd8e84604194/src/diffusers/configuration_utils.py#L300) are used to handle model configs:
```py
 class UNet2DConditionModel(ModelMixin, ConfigMixin): 
     @register_to_config

# there is no `UNet2DConfig` class (i.e. XYZConfig class)
```

comparing it to transformers (for example [here](https://github.com/huggingface/transformers/blob/02b176c4ce14340d26d42825523f406959c6c202/src/transformers/models/bert/modeling_bert.py#L737-L743)), there are explicit config classes such as [BertConfig](https://github.com/huggingface/transformers/blob/afe5d42d8d1d80af911ed980c2936bfe887078f6/src/transformers/models/bert/configuration_bert.py#L72) that inherit from [PretrainedConfig](https://github.com/huggingface/transformers/blob/0d0aada56444ad554021947addaa035feb55948f/src/transformers/configuration_utils.py#L46)

```py
class BertPreTrainedModel(PreTrainedModel):
    config_class = BertConfig
```

Why was `ConfigMixin` approach preferred over the `XYZConfig class`?

Thanks a lot! 🤗

**Comment by patrickvonplaten** [comment]
Good question! Think you can find most of the answers here:
https://github.com/huggingface/diffusers/issues/11

For me the big thing is the following:

By forcing the init to be `==` the configuration of the model class, we have a safety mechanism to not add parameters to model configs that shouldn't be there because the don't contribute to "instantiating" the model. E.g. in `transformers` we erroneously added some things like `max_length` for text-generation or `use_gradient_checkpointing` which are not related to training the model or configuring a model, but just for inference => the current design prevents us from adding such things to the config because they make no sense in a model config really

**Comment by mishig25** [comment]
oh I see 😊
closing the issue as it was previously discussed https://github.com/huggingface/diffusers/issues/11
