### ISSUE TITLE
ZeroscopeXL will not work as normal model

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#3937]
### Describe the bug

When using zeroscopeXL as a normal model I get this error: 
`TypeError: VideoToVideoSDPipeline.__call__() got an unexpected keyword argument 'height'`

(Also, Animov, which also comes in more trained sizes, can't be used for upscaling. Is vid2vid limited to use the zeroscopeXL model, currently?)

### Reproduction

```
                pipe = DiffusionPipeline.from_pretrained("cerspense/zeroscope_v2_XL", torch_dtype=torch.float16)
                pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
                video_frames = pipe(
                    prompt,
                    negative_prompt=negative_prompt,
                    num_inference_steps=movie_num_inference_steps,
                    guidance_scale=movie_num_guidance,
                    height=y,
                    width=x,
                    num_frames=duration,
                    generator=generator,
                ).frames
```

### Logs

```shell
TypeError: VideoToVideoSDPipeline.__call__() got an unexpected keyword argument 'height'
```

### System Info

Diffusers: 0.18.0
Win 11

**Comment by hysts** [comment]
Hi @tin2tin 

Regarding the first point, I don't think it's a bug. You can use the [XL model](https://huggingface.co/cerspense/zeroscope_v2_XL) as text-to-video model if you load it using `TextToVideoSDPipeline` like this:
```python
from diffusers import TextToVideoSDPipeline, DPMSolverMultistepScheduler

pipe = TextToVideoSDPipeline.from_pretrained("cerspense/zeroscope_v2_XL", torch_dtype=torch.float16)
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()
pipe.enable_vae_slicing()
```

My understanding is that the default pipeline for the XL model is set to `VideoToVideoSDPipeline` (see [here](https://huggingface.co/cerspense/zeroscope_v2_XL/blob/6934ce594c2a8b39eec8bfece9d630a7ec93f642/model_index.json#L2)) instead of `TextToVideoSDPipeline` because its main usage is to upscale output videos generated by the [576w model](https://huggingface.co/cerspense/zeroscope_v2_576w) as written in the model card:
![](https://github.com/huggingface/diffusers/assets/25161192/b25f23ff-409b-496f-be62-7bd6403b23f6)

**Comment by tin2tin** [comment]
Thank you. Closing.
