### ISSUE TITLE
StableDiffusionControlNetInpaintPipeline does not seem to support .safetensors?

### ISSUE THREAD

**Issue by hzhou17** [huggingface/diffusers#3974]
### Model/Pipeline/Scheduler description

I'd like to use Dreamshaper's inpaint model for StableDiffusionControlNetInpaintPipeline, I used the code of 

    pipe = StableDiffusionControlNetInpaintPipeline.from_single_file(
        "/home/heran/DreamShaper/DreamShaper_6.31_INPAINTING.inpainting.safetensors", controlnet=controlnet, torch_dtype=torch.float16
    ).to('cuda')

but I got the error that AttributeError: type object 'StableDiffusionControlNetInpaintPipeline' has no attribute 'from_single_file'

How can I load a .safetensors model with StableDiffusionControlNetInpaintPipeline?

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten

**Comment by patrickvonplaten** [comment]
We need to add `FromSingleFileMixin` to the class in order to load it. @hzhou17 could you provide a link to the checkpoint on the HF Hub? 

Note that the inpaint pipelines can have the same signature as the "normal" pipelines. We should actually add the mixin to both:
- https://github.com/huggingface/diffusers/blob/03d829d59e261b391455348cd145369077960745/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py#L156 
and 
- https://github.com/huggingface/diffusers/blob/03d829d59e261b391455348cd145369077960745/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py#L225

**Comment by patrickvonplaten** [comment]
@hzhou17 would you like to give this a try?

**Comment by hzhou17** [comment]
@patrickvonplaten Thank you sir for the support. The link to the inpaint model is 
https://huggingface.co/Lykon/DreamShaper/blob/main/DreamShaper_6.31_INPAINTING.inpainting.safetensors

I'd definitely like to give this a try, but I am not sure how to add FromSingleFileMixin to the class. Would you provide some guidance on that? Would much appreciate that.

**Comment by patrickvonplaten** [comment]
We need `from_single_file` inpainting support here - think we can solve this one while doing: https://github.com/huggingface/diffusers/issues/3907 (cc @yiyixuxu) :-)

**Comment by patrickvonplaten** [comment]
Hey @hzhou17 , 

Can you check if this works for you: https://github.com/huggingface/diffusers/pull/4084

**Comment by hzhou17** [comment]
Hi @patrickvonplaten, 

Thank you for your continuous help. But I still get this error:

"An error occurred during inpainting: type object 'StableDiffusionControlNetInpaintPipeline' has no attribute 'from_single_file"

diffusers version: 0.18.2

Is there something else that I need to update? I also posted this on #4084

**Comment by sayakpaul** [comment]
Replied there :-) 

Let's maybe try not to duplicate comments :)
