### ISSUE TITLE
[SD-XL] How to apply invisible-watermark for latent output

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#4054]
### Describe the bug

As a part of the license with SAI, we need to ensure the invisible watermark is applied across all images output by these models, including the Img2Img pipeline.

### Reproduction

```py
        # if xformers or torch_2_0 is used attention block does not need
        # to be in float32 which can save lots of memory
        if use_torch_2_0_or_xformers:
            self.vae.post_quant_conv.to(latents.dtype)
            self.vae.decoder.conv_in.to(latents.dtype)
            self.vae.decoder.mid_block.to(latents.dtype)
        else:
            latents = latents.float()
        if not output_type == "latent":
            image = self.vae.decode(latents / self.vae.config.scaling_factor, return_dict=False)[0]
        else:
            image = latents
            return StableDiffusionXLPipelineOutput(images=image)
```

the relevant portion of the img2img pipeline code.

in the XL pipeline, the latent output mode does not have the watermark applied - so, it is easily bypassed.

### Logs

```shell
N/A
```

### System Info

Git main branch.

### Who can help?

cc: @sayakpaul

**Comment by sayakpaul** [comment]
How would you propose we add watermarking to the latents? IIUC, the [watermarker](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion_xl/watermark.py) we use is only image-compatible.

**Comment by bghira** [comment]
it doesn't apply to the image output, the latents are only there for context.

i simply brought up the XL's lack of watermark on its latents output to clarify that it's not added at that level, either.

**Comment by sayakpaul** [comment]
> it doesn't apply to the image output in the img2img pipeline.

It does apply to the image:

https://github.com/huggingface/diffusers/blob/b9feed87958c27074b0618cc543696c05f58e2c9/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py#L887

> i simply brought up the XL's lack of watermark on its latents output to clarify that it's not added at that level, either.

If so, it might be better for a discussion on Stability AI's repo IMO.

**Comment by patrickvonplaten** [comment]
Hey @bghira, I renamed the issue title a bit here because I would like to differentiate between images and latents.

It is your responsibility as a user to apply the watermark to generated images if you want to share those images. To do so we by default add the watermark to all images (images != latents). If you want to circumvent this by returning the latents and then afterward decoding the latents without using the watermark you can do this but it goes against the license.  


=> Long story short please run the watermarker on **every** image (not latent tensor) that you want to share. This is **always** done by default in `diffusers` for the standard / recommended workflow.

I hope this clarifies things :-)
