### ISSUE TITLE
How to train text-to-image model based on SDXL?

### ISSUE THREAD

**Issue by EnzoWuu** [huggingface/diffusers#4150]
Can I use the train_text_to_image.py code directly?

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
You cannot. You will have to account for some of the SDXL specific changes:

* Handling the second text encoder (`CLIPTextModelWithProjection` type)
* Handling the additional conditional embeddings accepted by the UNet 
* Packing all of the above in the dataloader 

You can get an idea of how these changes could be incorporated by studying https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sdxl.py. 

Since the UNet is bigger in SDXL plus it uses two text encoders, we decided not to release a script for the vanilla fine-tuning. 


I hope that helps.

**Comment by AmericanPresidentJimmyCarter** [comment]
@EnzoWuu just use kohya trainer

https://github.com/Linaqruf/kohya-trainer/blob/main/kohya-trainer-XL.ipynb

I can train batch size 4 1024x1024 images per 3090
