### ISSUE TITLE
How is running locally requiring your tokenized access to ckpt file ? Is that really local ? How is that local ?

### ISSUE THREAD

**Issue by 1blackbar** [huggingface/diffusers#441]
### Describe the bug

this crap
https://discuss.huggingface.co/t/how-to-login-to-huggingface-hub-with-access-token/22498/5

So... just let us use our own path to our folders and ckpt file ok ? Like a local thing you know ?

### Reproduction

try it on miniconda, good luck !!!

### Logs

```shell
none
```

### System Info

win10 miniconda ldm env

**Comment by Inkorak** [comment]
You're can.

```
pipe = StableDiffusionPipeline.from_pretrained('path to weights on your computer')
pipe = pipe.to("cuda")
```

**Comment by 1blackbar** [comment]
I mean iyou should be able to just type in your tokenized acces code, if you really want peope to use it , its just doesnt work unless its not in conda, works in windows terminal but i dont want to run it under that.

**Comment by 1blackbar** [comment]
> You're can run locally.
> 
> ```
> pipe = StableDiffusionPipeline.from_pretrained('path to weights on your computer')
> pipe = pipe.to("cuda")
> ```

this in readme would save A LOT of time for a lot of people

**Comment by patrickvonplaten** [comment]
We need to make this indeed even clearer in the README then! 
@pcuenca @anton-l @patil-suraj - ideas what we can do here? 

It's written in Quickstart: https://huggingface.co/docs/diffusers/quicktour and some other places - but I'm wondering if we should make it the "default" way of using diffusers, by putting it first in most readmes. Wdyt?

**Comment by pcuenca** [comment]
I think it's a bit too much to put it first, as most people that visit the github project won't have the weights. I'd maybe do the following in the README file:

- Keep the first example the way it is, as it covers the most usual case.
- Just below it, add a section about downloading weights and using them locally. **This will be updated** when we have #491, as so many people seem to be getting their weights as checkpoints.
- Immediately below that one, link to the docs for people that are using other hardware (`mps`), as there has been some confusion about whether or not to use `autocast` in that case.

If this sounds ok I can open a PR to propose some specific wording and examples.

**Comment by sjkoelle** [comment]
I am also stuck on this... is it the case that only local paths in the huggingface cache are valid for from_pretrained?

```pretrained_model_name_or_path = "/home/ubuntu/stable-diffusion-v1-4"
pipe = StableDiffusionPipeline.from_pretrained(
    pretrained_model_name_or_path,
    local_files_only = True,
)```

generates ` No such file or directory: '/root/.cache/huggingface/diffusers/models----home--ubuntu--stable-diffusion-v1-4/refs/main'`

Maybe I am missing something simple - the documentation has

``` Activate the special ["offline-mode"](https://huggingface.co/diffusers/installation.html#offline-mode) to use  this method in a firewalled environment.```
 
 but the link is not working.  Any help appreciated.

**Comment by patrickvonplaten** [comment]
Thanks for the issue @sjkoelle ! I think the problem is the following, your directory `"/home/ubuntu/stable-diffusion-v1-4"` doesn't exist. 

What does this line give you:

```python
import os
print(os.path.isfile("/home/ubuntu/stable-diffusion-v1-4"))
```

If you pass a path to a local checkpoint, you don't need to set `local_files_only=True` because this if statement should be True:
https://github.com/huggingface/diffusers/blob/83a7bb2aba2d897ab95d96fb03eda10a624080e7/src/diffusers/pipeline_utils.py#L287

**Comment by ExponentialML** [comment]
To prevent running around in circles on this issue, this problem will remain unresolved until there is provided option to load a custom model / path (ckpt, pt, etc.) into the Diffusers pipeline.

As it stands currently, if you don't download it the HF way, you'll have to do some digging to get it working. You can run it locally, but it consists of messing with blobs in the `.cache` directory. However, this may possibly introduce edge cases due to how Diffusers works, so it may be best to use the original implementation until this is considered.

In my opinion, while the Diffusers pipeline is great, the friction introduced by streamlining things heavily creates too much friction. There should be more than one way to load things into the pipeline, rather than wait for a community based implementation from the original maintainers (which may or may not happen).

**Comment by sjkoelle** [comment]
Hmmm, yes it is a file not a folder, so false.  Thanks for the quick response, and also your ExponentialML which addresses the question behind the question.

**Comment by patrickvonplaten** [comment]
Hey @ExponentialML,

Thanks a lot for the feedback here - I think we haven't done a great job at showing how to easily download this model and run it locally. It's literally as easy as doing:

```
git lfs install
git clone https://huggingface.co/CompVis/stable-diffusion-v1-4
```

Followed by:

```python
generator = DiffusionPipeline.from_pretrained("./stable-diffusion-v1-4")
```

-> no need for an authentication token or cache or whatsoever. It's also explained here: https://huggingface.co/docs/diffusers/quicktour

Given that you're not the first to mention this problem, I'll open an issue now about providing better documentation.
