### ISSUE TITLE
Sample with Consistency Model

### ISSUE THREAD

**Issue by RossoneriZhao** [huggingface/diffusers#4414]
### Describe the bug

When I use diffusers to sample images with offered code by Consistency Model, I can't get an image that corresponds to the label at all: 
label 207 (Golden Retriever)
![0](https://github.com/huggingface/diffusers/assets/102647326/5b01b720-1c1f-4c98-afb9-89081a196e5e)

### Reproduction

I just used the officially offered code by Consistency Model:
https://github.com/openai/consistency_models

### Logs

```shell
python /home/dqwang/scratch/tutu/diffuser/check.py
unet/diffusion_pytorch_model.safetensors not found
Loading pipeline components...:   0%|                                                     | 0/2 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing UNet2DModel: 
 ['mid_block.attentions.0.group_norm.weight, mid_block.attentions.0.group_norm.bias']
Loading pipeline components...: 100%|█████████████████████████████████████████████| 2/2 [00:02<00:00,  1.11s/it]
/home/dqwang/mambaforge/envs/diffuser/lib/python3.7/site-packages/diffusers/configuration_utils.py:134: FutureWarning: Accessing config attribute `sigma_min` directly via 'CMStochasticIterativeScheduler' object attribute is deprecated. Please access 'sigma_min' over 'CMStochasticIterativeScheduler's config object instead, e.g. 'scheduler.config.sigma_min'.
  deprecate("direct config name access", "1.0.0", deprecation_message, standard_warn=False)
100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 14.55it/s]
```

### System Info

- `diffusers` version: 0.19.3
- Platform: Linux-5.15.0-25-generic-x86_64-with-debian-bookworm-sid
- Python version: 3.7.12
- PyTorch version (GPU?): 1.11.0+cu113 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: not installed
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by RossoneriZhao** [comment]
I have solved this problem, diffusers' source code misses a group norm layer in consistency model's mid_block init, which leads to a bad result.

**Comment by sayakpaul** [comment]
Would you be open to maybe opening a PR to fix the problem? 

Cc: @dg845 @ayushtues

**Comment by dg845** [comment]
My understanding of the issue is as follows: for some consistency model checkpoints like [`openai/diffusers-cd_imagenet64_l2`](https://huggingface.co/openai/diffusers-cd_imagenet64_l2), the [`UNet2DModel`](https://huggingface.co/openai/diffusers-cd_imagenet64_l2/blob/main/unet/config.json) should both use `resnet_time_scale_shift=scale_shift` and have a GroupNorm in the U-Net's mid block, but in the implementation of [`UNetMidBlock2D`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_blocks.py#L426) a GroupNorm is only added to the [`Attention`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention_processor.py#L36) block if `resnet_time_scale_shift == default`:

https://github.com/huggingface/diffusers/blob/816ca0048f7a38531a6f036299d2dd274abb5639/src/diffusers/models/unet_2d_blocks.py#L472-L478

The [conversion script](https://github.com/huggingface/diffusers/blob/main/scripts/convert_consistency_to_diffusers.py) correctly loads the mid block attention group norm weights from the original checkpoints, but since `unet.mid_block.attentions.0.group_norm` isn't created when the `unet` is initialized, we see the warning

```bash
Some weights of the model checkpoint were not used when initializing UNet2DModel: 
 ['mid_block.attentions.0.group_norm.weight, mid_block.attentions.0.group_norm.bias']
```

as above.
