### ISSUE TITLE
long weighted prompt support for SDXL?

### ISSUE THREAD

**Issue by evanferguson28** [huggingface/diffusers#4559]
The commmunity pipeline https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py supports long prompts that exceed the 77 tokens limit and weighted prompts such as "(((masterpiece)))", but it only works with sd 1/2, not SDXL, since SDXL has two sets of text encoders and tokenizers. Is there any plan to implement a lpw_stable_diffusion_xl pipeline, maybe?

**Comment by CoffeeVampir3** [comment]
This is something I'm looking into and I'd love some conversation on the topic. To start, I've implemented an experimental prompt weighting for SDXL here: [Prompt weighting](https://github.com/CoffeeVampir3/manual1111/blob/main/mechanisms/tokenizers_utils.py) but there's one fundamental difference between older SD's and SDXL, that being the pooling output. Let me ramble a bit on the topic because I've found no good answers here myself:

The pooling embedding used by SDXL is not of the same shape as the other tensors. This is a problem because how weighting currently works is by making an association between word and output vector:

`Fried (Banana)` can be weight as (Fried, 1) (Banana, 1.5) for example. How does this actually work is there's up to 75 inputs words to both clip models, 1 extra token is added at the start, one at the end. For a total of 77 tokens. So we get up to 77 words, and we have an output tensor with a shape:

`[1, 77, size]`

What you then do is multiply your weight value with that tensor index. If banana is index 2 for example:

`[1, 2, size] * 1.5`

and now you've weighted the banana embedding. However, the pooling output is a single tensor:

`[1, 1280]`

There's no obvious way to change the weighting on it. It does carry information, and you can prove this by setting all other encoder outputs to 0 other than the pooled output, and you will still see things resembling your prompt. What this means is that, if we're unable to weight to pooling output somehow, we have a minimum to how small the importance of a concept can get. This is sort of marginal, but it's a notable difference from the behaviour of other pipelines.

Okay, so what about extending the token limit? There's a ton of methods you can employ, basically every method runs max length chunks in isolation, so chunks of 75. If we have 3 chunks, you can do a simple approach and average them. The trade off here is information density, by averaging you're potentially a fair amount of information along the way. I'm very interested here in experimenting with alternative methods. It would also be nice if somebody could dig up the reference implementation in something like sd.next or automatic to compare against and have a baseline to measure from.

All that said, if I can find a satisfactory way to do this I'll look into contributing an SDXL community pipe. Cheers.

**Comment by bghira** [comment]
just don't mess too much with the pooled embeds. use the first one, and don't concat or truncate it. you end up with terrible results when you do this.

**Comment by bghira** [comment]
> Okay, so what about extending the token limit? There's a ton of methods you can employ, basically every method runs max length chunks in isolation, so chunks of 75. If we have 3 chunks, you can do a simple approach and average them. The trade off here is information density, by averaging you're potentially a fair amount of information along the way. I'm very interested here in experimenting with alternative methods. It would also be nice if somebody could dig up the reference implementation in something like sd.next or automatic to compare against and have a baseline to measure from.

this is generally why going past the clip token limit isn't officially supported by... anyone. the math breaks out. the author of Compel points this out.

the value of these operations is often in features that allow you to avoid CLIP bleed by parsing them separately

**Comment by sayakpaul** [comment]
We are happy to accept PRs for this but we don't have the cycles to support this officially.

**Comment by xhinker** [comment]
> We are happy to accept PRs for this but we don't have the cycles to support this officially.

I have a implementation of long prompt weighted prompt for SDXL,  it can accept any length of prompt and using A1111 weighted prompt format. 

Usage like this:
```python
prompt_embeds, prompt_neg_embeds,pooled_prompt_embeds, negative_pooled_prompt_embeds = get_weighted_text_embeddings_sdxl(
    sdxl_pipe
    , prompt = prompt
    , neg_prompt = neg_prompt
)
```
@sayakpaul  any guidance on the PR? like which folder, document and format  requirements?

**Comment by sayakpaul** [comment]
You add to: https://github.com/huggingface/diffusers/tree/main/examples/community.
