### ISSUE TITLE
fp8

### ISSUE THREAD

**Issue by maxpain** [huggingface/diffusers#4583]
Is it possible to utilize `fp8` of new nvidia ada lovelace GPUs?

**Comment by AmericanPresidentJimmyCarter** [comment]
fp8 is a work in progress for torch: https://github.com/pytorch/rfcs/pull/51

A third party module would be needed.

**Comment by sayakpaul** [comment]
Since it relies with PyTorh, I am going to close this. Also seeking @williamberman's thoughts here.

**Comment by williamberman** [comment]
Yeah I'm not familiar with the implications off the top of my head

**Comment by AmericanPresidentJimmyCarter** [comment]
We have tried fp8 now with pytorch, since it is in nightly. It works on 40xx cards but the results on 30xx cards are rough looking and we are unsure why. All the calculations are done in fp16/bf16 still as far as I can tell too, the weights are just stored in fp8.

Memory usage is way down. You can load SDXL CLIP+Unet+VAE in just 3GB.

**Comment by Metal079** [comment]
I would also like to know how to use fp8 if possible? Does it only improve memory usage or does it also increase inference speed?
