### ISSUE TITLE
Memory Leak in DiffusionPipeline when switching width/height in subsequent calls

### ISSUE THREAD

**Issue by Quasimondo** [huggingface/diffusers#4674]
### Describe the bug

Using the stable-diffusion-xl-base-1.0 pipeline on a 15 GB GPU everything works as expected as long as I do not try to change the output width and height in subsequent calls to the same model. Once I do that the machine runs out of memory after just a few successful runs. I tried to fix the problem by calling torch.cuda.empty_cache() and also attempted enable_model_cpu_offload(), but neither of them helped. The only way to do it seems to pick one size and stay with it.

### Reproduction

```
import torch
import numpy as np
from diffusers import DiffusionPipeline

base = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True, add_watermarker=False)
base.unet = torch.compile(base.unet, mode="reduce-overhead", fullgraph=True)
base.to("cuda")
sizes = [(1024,1024),(1152,896),(896,1152),(1216,832),(832,1216),(768,1344),(1536,640),(640,1536)]
prompt = "something pretty"
for i in range(1000):
    width,height = sizes[np.random.randint(len(sizes))]
    image = base(
                        prompt=prompt,
                        width=width,
                        height=height
                    ).images[0]
```
           

### Logs

```shell
CUDA out of memory. Tried to allocate 74.00 MiB (GPU 0; 14.58 GiB total capacity; 11.71 GiB already allocated; 26.38 MiB free; 13.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

diffusers 0.19.3
Python 3.9.12

### Who can help?

@williamberman

**Comment by sayakpaul** [comment]
On 15GB GPUs, the effects of `torch.compile()` often seem to diminish. 

Could you provide the code you're using with model offload? Have you tried using `enable_sequential_cpu_offload()`?

**Comment by williamberman** [comment]
You are re-compiling the model every run with the different sized inputs. I'm not sure if torch.compile assumes it's allowed to perma-allocate memory once it's called or maybe the compilation process itself is using memory that it isn't cleaning up.

Regardless, I'd just not compile the model if you're passing different sized inputs every time. You get no benefit of the compilation since you immediately throw it away.

I'm going to close the issue since I'm pretty confident it's related to the compilation and disabling should fix. Feel free to re-open if needed
