### ISSUE TITLE
[Core] shareable generation configs for pipelines

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#4734]
`transformers` has got a component called "generation config": https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig.  Here's how it's used:

```python
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, GenerationConfig

tokenizer = AutoTokenizer.from_pretrained("t5-small")
model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

translation_generation_config = GenerationConfig(
    num_beams=4,
    early_stopping=True,
    decoder_start_token_id=0,
    eos_token_id=model.config.eos_token_id,
    pad_token=model.config.pad_token_id,
)

translation_generation_config.save_pretrained("t5-small", "translation_generation_config.json", push_to_hub=True)

# You could then use the named generation config file to parameterize generation
generation_config = GenerationConfig.from_pretrained("t5-small", "translation_generation_config.json")
inputs = tokenizer("translate English to French: Configuration files are easy to use!", return_tensors="pt")
outputs = model.generate(**inputs, generation_config=generation_config)
print(tokenizer.batch_decode(outputs, skip_special_tokens=True))
```

Here are the references:

* [Reference docs](https://huggingface.co/docs/transformers/v4.32.0/en/main_classes/text_generation#transformers.GenerationConfig)
* [Short guide](https://huggingface.co/docs/transformers/v4.32.0/en/generation_strategies#default-text-generation-configuration)

I believe such a component could be beneficial for `diffusers` too. It could greatly improve the reproducibility of the generated results. 

The generation config could store all inference-time parameters (basically everything that's passed to a pipeline call). 

Here are some rough APIs I have in mind:

```python
sd_config = GenerationConfig(
    prompt="photo of my dog",
    num_inference_steps=25,
    guidance_scale=3.0,
)

pipeline = ...

images = pipeline(**sd_config).images
```

We could then introduce APIs for sharing this config (serialization, loading from Hub, etc.). 

```python
# Acess the config. It should change after each and every different pipeline call parameters. 
generation_config = pipeline.generation_config

# Save and push to hub. 
sd_config.save_pretrained("sayakpaul/generate-config-sd", push_to_hub=True)
```

WDYT? @williamberman @patrickvonplaten @pcuenca @yiyixuxu

**Comment by DN6** [comment]
This also feels like a really nice way for users to share prompts and settings. I'm wondering if it would be within scope to also save the pipeline information (model checkpoint name, pipeline name, controlnet info etc) and input (input images, or controlnet conditioning images) and output artifacts (generated images)

**Comment by williamberman** [comment]
This feels to me a smidge like over-engineering. I think this is essentially just serializing the arguments to the call function on the pipeline. I think you gain the reproducibility from just either sharing a code snippet or the arguments themselves?

**Comment by patrickvonplaten** [comment]
Interesting idea! I do see multiple use cases where this could be useful because:
- a) There are a lot of input values already for the call method and the default values don't always correspond to the best values
- b) Schedulers, seeds, ... can give very much different results
- c) It could actually be a nice way to share workflows via the Hub (e.g. we allow people to download worksflows from the Hub)
- d) Could greatly help with reducing issues

@sayakpaul instead of doing:

```py
sd_config = GenerationConfig(
    prompt="photo of my dog",
    num_inference_steps=25,
    guidance_scale=3.0,
)

pipeline = ...

images = pipeline(**sd_config).images
```

I think we could also include information about the scheduler etc.. in the workflow:

```py
pipeline = DiffusionPipeline.from_pretrained(...)
pipeline.load_workflow("path_to_hub", workflow_file)

images = pipeline().images  # the loaded workflow sets all arguments needed for `call`
```

The workflow file could maybe set both individual components and default values for `__call__`:
```py
workflow_config = {
"components": {"scheduler": {"class_name": DDIMScheduler, <kwargs>}},
"call": {"prompt": ..., "negative_prompt": ..., "guidance_scale": ..., "seed": ....}
}
```

We could also think about adding a `return_workflow` arg in `call` that returns the workflow of a given run. 

Would be very interesting to gather more feedback from the community here - I do like the idea!

Also @apolinario wdyt?

**Comment by patrickvonplaten** [comment]
Also cc @bghira @dg845 @camenduru here maybe do you think this could be useful / helpful?

**Comment by bghira** [comment]
absolutely, i've always meant to open a request for maybe a flag in the unet to tell it, for example the ideal guidance/rescale values. we have the scheduler config, but not the ability to hint the default num_inference_steps

**Comment by bghira** [comment]
if a model has a subdir of `workflows` and we can hint `workflow='artistic'` for example, a model author can provide some kind of style template. this could be interesting!

**Comment by williamberman** [comment]
I still think all of these benefits are maintained from sharing/documenting code snippets, and code snippets are more flexible if people want to make modifications to them. 

I think the cost benefit is:
benefit: we potentially save ~10-20 loc per code snippet
cost: we potentially lose flexibility in those shared code snippets and we introduce another serialization format to maintain

**Comment by bghira** [comment]
those hints i mentioned are all about getting valid results out of the model with default settings, so that every model card on HF Hub doesn't need to describe how to load and do inference on it.

it is placing a heavy burden on downstream applications/integrations to expect them to track the ideal settings for every single model. part of the hub's promise is its flexibility and drop-in nature, and this can really enhance that.

we don't need a whole new file for it, just adding these values to their respective model config.

**Comment by williamberman** [comment]
Could you provide an example of an official model which doesn't produce valid results with default settings? 

The description of the how to load and do inference still exists, just instead of being in the model card or docs which is ver transparent, it's in a serialized file which is harder to understand/change.

I'm not sure I really follow what the downstream burden is, we've essentially gone from 

```py
pipeline = PipelineClass.from_pretrained("<foo>")
images = pipeline(<at most 10 args?>).images
```

to 

```py
pipeline = PipelineClass.from_pretrained("<foo>")
pipeline.load_workflow("<bar>")
images = pipeline(<something less than 10 args?>).images
```
where now if I have a question about the workflow I have to look in the workflow file and look in the docs that describe how the workflow file works. This _really_ strikes me as un-necessary complexity and sounds like we possibly increase the burden on downstream users.

The increased complexity isn't in if the new config is in an existing file or a new file. The increased complexity is in maintaining the serialization format in source that has to update pipeline and save pipeline behavior from an external source.

**Comment by bghira** [comment]
well, i didn't realise that only official models have that kind of support. but my terminal SNR models end up incorrectly sampling because there's no way to tell it to use CFG rescaling or a higher guidance value without adding those parameters to the call args. i would like for that to be transparent to end-users.

many fine-tunes benefit from lower CFG than the default models.

50 steps is too many for a model that is configured to use DDIM, and can get away with 15 or 25 steps.

but i think my request is fundamentally different from having multiple workflows, and perhaps i should open a new request for that.

**Comment by williamberman** [comment]
I think these all sound super reasonable but solvable with docs along with the different use cases? Additionally, none seem to be more than 1-2 additional arguments.

I.e. does the fact that a custom model needs CFG rescaling require being completely transparent? I'm not sure I see the issue with a note in the docs for how to download and used

In fact, I'd generally always say it's better experience for the users to have these things be explicitly documented and require explicit passing because if not, they might not realize that those are additional constraints and then be confused if they try to change them without realizing they're hidden in a workflow file.

**Comment by bghira** [comment]
InvokeAI has a model hub that lets you load them from HF hub, and it doesn't have any way to hint to the user to change their settings.

My own Discord bot has a function allowing the use of any public model on HF hub, and if they could hint the correct inference values, it would make it easier for everyone.

**Comment by dg845** [comment]
I think the cases where having a serializable generation config is most useful might be

- when we load a "non-official" checkpoint using an official pipeline (such as someone loading a fine-tuned Stable Diffusion checkpoint using `StableDiffusionPipeline`), since it may no longer be the case that the default `__call__` parameters are good for this particular checkpoint (arguably, this can be solved by having a code snippet instead)
- when there are multiple use cases for a given checkpoint, as @bghira noted in https://github.com/huggingface/diffusers/issues/4734#issuecomment-1693720956: we could have multiple workflows like `workflow='artistic'`, `workflow='photorealistic'`, `workflow='cartoon'`, etc. I think having generation configs scale better than code snippets when the number of "qualitatively different" configs is large.

I think generation configs have more value the more complexity they subsume. Following this line of logic, I wonder if it might be a good idea for workflows to be a superset of pipelines, kind of like what @DN6 suggested in https://github.com/huggingface/diffusers/issues/4734#issuecomment-1689956224:

```python
# Loads a pipeline as well as generation args and maybe other stuff like LoRAs?
workflow = DiffusionWorkflow.from_pretrained("<foo>")

# Pipelines are a component of a workflow
pipeline = workflow.pipeline

# Generation arguments are a component of a workflow
generation_config = workflow.generation  # probably needs a better name
```

Under this design `DiffusionWorkflow` would be the highest level and least flexible API, and then users could use the lower level `DiffusionPipeline` API for more control over generation. The downside might be that this might take more effort to maintain than other designs.

Overall I think having generation configs would be a good idea, although I agree with @williamberman that we should be mindful of the ROI of supporting it.
