### ISSUE TITLE
[Feature Request] Add clip skip

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#4834]
I think it's time to add CLIP skip as described in: https://github.com/huggingface/diffusers/issues/3212#issuecomment-1691714105

Too many issues have been popping up: https://github.com/huggingface/diffusers/issues/3870 e.g.

Anybody interested in taking this one? 
@sayakpaul maybe since it's closely related to the `encode_prompt` PR?

**Comment by sayakpaul** [comment]
Happy to take a look.

**Comment by knoopx** [comment]
Compel does this among other features, not sure this needs to be part of diffusers as you can directly pass compel generated text embeds to any pipeline.

**Comment by alexblattner** [comment]
here's an easy way to do it @patrickvonplaten :
```
clip_layers = pipe.text_encoder.text_model.encoder.layers
if clip_skip > 0:
        pipe.text_encoder.text_model.encoder.layers = clip_layers[:-clip_skip]
```

Also, you can reset it like this:
`pipe.text_encoder.text_model.encoder.layers = clip_layers`

this should be very very to implement considering how it's only 3 lines of code.

if you have the time, I would appreciate if you considered some of the following:
1. Even though both you and sayakpaul adamently refused to consider this, I gave you a solution to your rigidity problem in diffusers here: https://github.com/alexblattner/RubberDiffusers
I think you and the diffusers team could accomplish far more with a similar approach. This code is far more flexible than diffusers, just as reproducible and far less complex. You can easily have pipeline that don't exist like controlnet+SAG+inpainting at the same time as a result.
2. I would appreciate if you implemented this: https://github.com/huggingface/diffusers/issues/5017 since it came out a few months ago and is considered a staple in A111
3. I have a solution for a bug but was ignored multiple times: https://github.com/huggingface/diffusers/issues/4988
4. this implementation of loras is supperior to diffusers in every way except 1 (lack of lycoris support): https://gist.github.com/takuma104/e38d683d72b1e448b8d9b3835f7cfa44 I would be great if you did something similar. The code is very elegant, easy to use, flexible and has more options than the one in diffusers. Usage example:
```
referance=pipe.apply_lora(i, 0.0).to('cuda') #this initiates the lora at weight 0, it can be whatever weight you want
referance.alpha=0.5 #this modifies the weight
```

We appreciate your efforts and contributions, but I believe that you guys focus too much on random new models that quite frankly aren't useful for the average user such as wuerstchen since it has no community support and isn't adding too much to the world compared to SD1.5. Every month I see plenty of quite useless things implemented that no one use. Lycoris, basic flexibility in loras (it's ridiculous that you can't use 2 loras without fusing them), contol mode for controlnet, prompt fusion, clip skip, etc... all those are supposed to be top priority if we look at this purely from a usefulness perspective. It's cool that you're trying new stuff, but please catch up to months old staples.

**Comment by bghira** [comment]
@alexblattner the suggested code you proposed is incorrect.

**Comment by alexblattner** [comment]
@bghira it literally is what invokeai is using. I'd like to point out that you will not get the same results that you get in A111 regardless of anything because of the structure. You can test this out on anything that doesn't use clip skip.

**Comment by bghira** [comment]
invokeai just kind of does whatever seems right, not necessarily a reference to look to. for the Diffusers implementation, see #4901
