### ISSUE TITLE
Invisible Watermarking and Inclusion as Default

### ISSUE THREAD

**Issue by ari-holtzman** [huggingface/diffusers#486]
Hi all,

Love the work y’all are doing!

The original [CompVis Stable Diffusion repo](https://github.com/CompVis/stable-diffusion) includes invisible watermarking so that images generated don’t end-up polluting newly scraped training data with automatically generated results, [as is already happening for text data.](https://arxiv.org/abs/2104.08758).

It'd be great to include invisible watermarking as a part of this repo and include it by default in all pipelines and examples.

Not sure if this has been discussed already, but I couldn't find anything and I tried posting in the forum first [here](https://discuss.huggingface.co/t/any-reason-invisible-watermarking-isnt-included-and-on-by-default/22977/2), sorry if I missed something.

**Comment by patrickvonplaten** [comment]
Hey @ari-holtzman,

Very good point - thanks for bringing this up here! I wonder whether it would be ok to add this optionally with a flag so that we don't break backwards compatibility. cc @apolinario @mmitchellai - ok if we don't make the watermark the default? It would really hurt the library in terms of backwards compatibility if we'd have to do this

**Comment by patrickvonplaten** [comment]
To not leave this issue unnoticed, @ari-holtzman do you have good libraries in mind for a watermark? Most libraries have too many dependencies and/or have watermark functionality that doesn't work well from what I've seen :-/
