### ISSUE TITLE
Inpaint: Choose starting point

### ISSUE THREAD

**Issue by rb-synth** [huggingface/diffusers#4900]
In A1111 you can choose what the inpainted region is initially filled with. E.g., original or latent nothing. Is there an example of this with diffusers?

**Comment by patrickvonplaten** [comment]
See: https://huggingface.co/docs/diffusers/v0.20.0/en/api/pipelines/stable_diffusion/inpaint#diffusers.StableDiffusionInpaintPipeline.__call__.strength 

`strength` defines how much noise should be added to the original image. If you have strength = 1.0 it's pure noise, otherwise it's the original image + some noise
