### ISSUE TITLE
MPS: scheduler indices must be in the same device as the indexed tensor

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#501]
Continuation of #239, but specific for `mps`. /cc @FahimF. Being fixed in #450.

**Comment by FahimF** [comment]
Since #450 is merged to the main branch, I installed the code from the main branch and ran a bunch of tests on all the Stable Diffusion pipelines and schedulers that I currently use under `mps`. I can confirm that all of them work correctly and that there are no issues :smile:

Here's what I can confirm works:
Pipelines: `StableDiffusionPipeline` and `StableDiffusionImg2ImgPipeline`
Schedulers: `LMSDiscreteScheduler`, `PNDMScheduler`, and `DDIMScheduler`
