### ISSUE TITLE
[Tests] Add tests for refiner architecture of SDXL

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#5031]
Currently we don't really test the refiner architecture in SDXL for StableDiffusionXLImg2Img, but only the case when xl-base is used for img2img. 

We should add a new fast testing class below here: https://github.com/huggingface/diffusers/blob/19edca82f1ff194c07317369a92b470dbae97f34/tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py#L42

**Comment by patrickvonplaten** [comment]
cc @DN6 can you maybe take care of this?

**Comment by DN6** [comment]
@patrickvonplaten there is a test for the refiner here:
https://github.com/huggingface/diffusers/blob/19edca82f1ff194c07317369a92b470dbae97f34/tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py#L162

Which sets the `text_encoder` key to `None` and runs the refiner model. 

This issue: #5026 was caused because of the `text_encoder` key was missing in the checkpoint on the hub. Instead of adding new testing class to SDXL Img2Img, maybe we add a test to `test_pipelines_common.py` to check for cases where the components on the hub, and in the pipeline class do not match up?

**Comment by DN6** [comment]
Or were you referring to adding slow test to SDXL Img2Img with the refiner model?

**Comment by patrickvonplaten** [comment]
> @patrickvonplaten there is a test for the refiner here:
> 
> https://github.com/huggingface/diffusers/blob/19edca82f1ff194c07317369a92b470dbae97f34/tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_img2img.py#L162
> 
> Which sets the `text_encoder` key to `None` and runs the pipeline as if it is the refiner model.
> 
> This issue: #5026 was caused because of the `text_encoder` key was missing in the checkpoint on the hub. Instead of adding new testing class to SDXL Img2Img, maybe we add a test to `test_pipelines_common.py` to check for cases where the components on the hub, and in the pipeline class do not match up?

The `text_encoder` key is not missing [here](https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/blob/93b080bbdc8efbeb862e29e15316cff53f9bef86/model_index.json#L12) - the refiner doesn't need a `text_encoder` (it's an optional component). 

Yes there is one test, but we should create a whole `FastTest` testing class that runs all of the common tests on a dummy pipeline that does **not** have a `text_encoder`. So instead of one test we should have 20+ tests including all the official ones

**Comment by patrickvonplaten** [comment]
I'm not referring to adding a slow test

**Comment by DN6** [comment]
Got it. Will add it shortly.
