### ISSUE TITLE
`LoRAAttnProcessor2_0` getting deprecated and consequences for Dreambooth training

### ISSUE THREAD

**Issue by rvorias** [huggingface/diffusers#5133]
**What API design would you like to have changed or added to the library? Why?**

I'm getting the following warning while running the dreambooth sdxl lora example:

> diffusers/models/attention_processor.py:1570: FutureWarning: `LoRAAttnProcessor2_0` is deprecated and will be removed in version 0.26.0. Make sure use AttnProcessor2_0 instead by settingLoRA layers to `self.{to_q,to_k,to_v,to_out[0]}.lora_layer` respectively. This will be done automatically when using `LoraLoaderMixin.load_lora_weights`

**What use case would this enable or better enable? Can you give us a code example?**

It is not clear how you would apply this to the dreambooth lora script in the examples:
https://github.com/huggingface/diffusers/blob/157c9011d87e52632113024c1dc5125426971556/examples/dreambooth/train_dreambooth_lora_sdxl.py#L777-L779

**Comment by patrickvonplaten** [comment]
Thanks for the issue @rvorias! 

We should probably update all these examples to create LoRA layers differently now that `LoRAAttnProcessor` is deprecated. @sayakpaul wdyt?

**Comment by sayakpaul** [comment]
Yeah will look into it. Makes sense to me.

**Comment by sayakpaul** [comment]
What issue?

**Comment by ridhoyp** [comment]
in SD A1111 GUI with dreambooth extension, when try to train in dreambooth , click use lora option and hit the train button, its get an error , i use the new a1111 1.7.0 version ,

this the error :

ValueError: The deprecation tuple ('LoRAAttnProcessor2_0', '0.26.0', 'Make sure use AttnProcessor2_0 instead by settingLoRA layers to `self.{to_q,to_k,to_v,to_out[0]}.lora_layer` respectively. This will be done automatically when using `LoraLoaderMixin.load_lora_weights`') should be removed since diffusers' version 0.26.3 is >= 0.26.0

**Comment by sayakpaul** [comment]
I am not well-versed with the A1111 way of training LoRAs. But from `diffusers`, we have fully deprecated the LoRA attention processors and no longer rely on them during training. We made sure to deprecate them with a long cycle. 

You need to install `peft` (which doesn't require any additional dependencies if you have already installed `diffusers`, `transformers`, and `accelerate`).
