### ISSUE TITLE
[Community] Add dropout to Flax UNet

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#522]
### Describe the bug

Flax UNet currently doesn't support dropout 

### System Info

Main

**Comment by MarkRich** [comment]
Hello @patrickvonplaten ! 

I assume this issue is still relevant? If so happy to help with it. Just for clarity: the task is to address the comments that patil had here: https://github.com/huggingface/diffusers/pull/502#pullrequestreview-1109050359, correct? i.e. that the flax UNet model does not actually perform dropout since it was originally intended just for inference?
