### ISSUE TITLE
custom CFG?

### ISSUE THREAD

**Issue by jtoy** [huggingface/diffusers#5291]
is it possible to Set CFG to zero after 40% of steps?
I see in this article he does it: https://www.baseten.co/blog/sdxl-inference-in-under-2-seconds-the-ultimate-guide-to-stable-diffusion-optimiza/

He has sample code, but I dont know how to incorporate it.
I couldn't find how to do this in the documentation. he is doing it with diffusors library.

**Comment by a-r-r-o-w** [comment]
I believe the code mentioned in the article is to be incorporated [here](https://github.com/huggingface/diffusers/blob/e46ec5f88fec23870538df782258c59271b010fd/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L846).

Essentially, to perform CFG, you need to duplicate the latents and prompt embeddings. In order to turn it off after a certain number of inference steps, like the article mentions, you remove the duplication of latents by setting `do_classifier_free_guidance=False` and halving the prompt embeds (which was initially duplicated [too](https://github.com/huggingface/diffusers/blob/e46ec5f88fec23870538df782258c59271b010fd/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L203)).

**Comment by patrickvonplaten** [comment]
We're working on supporting this! cc @yiyixuxu 

See: https://github.com/huggingface/diffusers/issues/4778
