### ISSUE TITLE
Possibility to set custom timesteps tensor in pipeline

### ISSUE THREAD

**Issue by TimothyAlexisVass** [huggingface/diffusers#5310]
**Is your feature request related to a problem? Please describe.**
I want to be able to manually define timesteps.

**Describe the solution you'd like**
```python
pipe = DiffusionPipeline.from_pretrained(...).to("cuda")
my_timesteps =  torch.tensor([901, 801, 701, 601, 501, 401, 301, 201])
pipe.scheduler.timesteps = my_timesteps

# This is essentially the same as
pipe("Cute kitten", num_inference_steps=10, denoising_end=0.8, output_type="latent")

# But when doing this
latents = pipe("Cute kitten", output_type="latent")
# It will override scheduler.timesteps with num_inference_steps (default 50)
 
```
**Describe alternatives you've considered**
Allow setting timesteps directly:
`latents = pipe("Cute kitten", output_type="latent", timesteps=my_timesteps)`
Setting `timesteps` should override `strength`, `denoising_start/_end` and `num_inference_steps`...

So we can do things like:
base_timesteps = torch.tensor([901, 801, 701, 601, 501, 401, 301])
refiner_timesteps = torch.tensor([201, 181, 161, 141, 121, 101, 81, 61, 41, 21, 1])

**I can create a PR if you point me to the files where this should be implemented and the docs where it should be added.**

**Comment by TimothyAlexisVass** [comment]
If this is already possible without deconstructing or creating a custom pipeline, I'm eager to know ;)

**Comment by patrickvonplaten** [comment]
Some pipelines offer this functionality such as IF and Wuerstchen: https://github.com/huggingface/diffusers/blob/bd72927c63447e46ebc595c91adb20a49bec4718/src/diffusers/pipelines/deepfloyd_if/pipeline_if.py#L547 .

The reason it's possible for IF is because IF only works with DDPM: https://github.com/huggingface/diffusers/blob/bd72927c63447e46ebc595c91adb20a49bec4718/src/diffusers/schedulers/scheduling_ddpm.py#L211 which allows custom timesteps to be passed to `set_timesteps`. So in order to allow this fucntionality for SD we would first make sure that all schedulers allow `timesteps` to be passed to the `set_timesteps` function
