### ISSUE TITLE
img2img for Latent Consistency Models

### ISSUE THREAD

**Issue by arcanite24** [huggingface/diffusers#5462]
**Is your feature request related to a problem? Please describe.**
Add support for img2img on the LCM pipeline

**Describe the solution you'd like**
img2img support

**Comment by a-r-r-o-w** [comment]
I would like to work on this if it's open for grabs. I believe most of the implementation will be similar to txt2img LCM pipeline, but instead of random latents, they are passed after vae encoding the image + noise addition based on a strength parameter (similar to how the standard img2img sd pipeline works).

**Comment by patrickvonplaten** [comment]
Sure would be great if you give this a try @a-r-r-o-w !

**Comment by nagolinc** [comment]
I think this PR closes this: https://github.com/huggingface/diffusers/pull/5477

**Comment by patrickvonplaten** [comment]
Img2Img works for all LCM modles
