### ISSUE TITLE
How to run stable diffusion pipeline using multithreading in fastapi ?

### ISSUE THREAD

**Issue by minkvirparia** [huggingface/diffusers#5709]
Hi.. I have created an stable diffusion API using Fastapi and it is working perfectly fine if sequential request are been made. I have tried to implement multithreading in the api to concurrently run multiple request, but the problem is every request output generation time is dependent on total number of request that are made. For Eg. if one request takes 5 secs to run, and if 5 request are made simultaneously then it will take 5*5 = 25 secs for every request to get output. After researching about these problem, I get know that GIL (Global Interpreter Lock) in python is allowing only one thread to execute per process. So we will get same output as single thread if we use multithreading in these purpose. Also, I have tried multiprocessing to overcome this issue but it is loading multiple instances of the same model for each process and its become very hard to load all model in 16 GB RAM.

Do you know how to get output in same time for every requests that are made. If 5 requests are made concurrently then every request should get output in 5 seconds only. Also do gpu configuration matters tp gets results in quick time based on number of request ?

GPU Configuration:
Nvidia 3050 8GB RAM

@sayakpaul @patrickvonplaten

**Comment by a-r-r-o-w** [comment]
Here's some suggestions based on my experience doing something similar:
- Don't load multiple instances of the model. As you mentioned, you will very quickly run out of memory.
- Maintain a task queue that can hold incoming requests. This task queue is used to dispatch requests for processing in batches of some pre-determined batch size. If there are more requests in the queue than batch size, the remaining requests simply wait for their turn until the current batch finishes processing. If there are less, we just process those. diffusers supports multiple prompts at once, and you can specify number of images per prompt as well, which is quite cool!
- Choose your batch size carefully in order to fully utilize the amount of vram you have available. From my experiments and iirc, with SD-1.5 (fp16) for 512x512 resolution in txt2img (1 image per prompt, DPMSolverMultistepScheduler, 20 inference steps), I have been able to process 26 requests at once on 16GB (Colab T4, ~40 seconds) and 42 requests on 24GB (RTX 3090, ~70 seconds) with no failure. Numbers might vary and perhaps more can be squeezed in. However, some cleanup is required after processing each batch otherwise you will get OOM. This works well for doing the same:
```py
import gc
import torch

def flush_memory():
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()
    with torch.no_grad():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()
```
- If you do the above by pushing the limits of max requests possible on your GPU, generation times will suffer. However, I've found that using batches of any size (I use 12), on my hardware, works faster than doing them one by one. Apologies for not having any public code available at the moment to back this up.
- You can lower the number of inference steps as it is the key factor in terms of time required to process. You can choose to use schedulers like `DPMSolverMultistepScheduler` or `UniPCScheduler` which can give good results in 5-10 steps.
- With the introduction of latent consistency models to diffusers, you can get really high quality images in just 2-4 steps as well. Awesome addition! I haven't ran many tests but it seems like you can generate ~60 images per minute easily. There's cool projects like [this](https://github.com/radames/Real-Time-Latent-Consistency-Model) with image generation in almost real-time!
- The most memory intensive operation is the VAE decode phase in the pipeline. For my purposes, I have written a custom diffusion pipeline which performs batch decoding based on a custom `decode_batch_size` parameter. With this, I can process more than 60 images at once on a RTX 3090 (haven't benchmarked the maximum) until the VAE decode phase starts. The decode still is limited by 42 images at a time as mentioned above.

I hope you'll find this helpful. Also, I'm not sure if this might not be the best way to go about it, but it worked pretty well for my use case and I thought it could be worth sharing. Hopefully others can share better ways of doing what you want.
