### ISSUE TITLE
Preprocessor: reference_only for ContolNet

### ISSUE THREAD

**Issue by zhuraromdev** [huggingface/diffusers#6062]
### Describe the bug

Hello,

I hope you are doing well. I have an issue with the preprocessor for Control Net. I am trying to transition from automatic to code-based workflow. I was attempting to create a ControlNet with the control type 'reference_only', but I haven't found a way to do it.

Thank you in advance for the help!

### Reproduction

Below you can see the flow, which was created in automatic

![Screenshot 2023-12-05 at 14 24 29](https://github.com/huggingface/diffusers/assets/78348856/d39c1577-e998-4f79-bdef-51d3f4b78c81)

### System Info

- `diffusers` version: 0.24.0
- Platform: macOS-13.6-arm64-arm-64bit
- Python version: 3.9.6
- PyTorch version (GPU?): 2.1.0 (False)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.33.2
- Accelerate version: 0.23.0
- xFormers version: not installed
- Using GPU in script?: no

### Who can help?

 @sayakpaul @yiyixuxu @DN6 @patrickvonplaten

**Comment by garychan22** [comment]
I think the reference_only preprocessor is identity in sd-web-ui since the model needs the features of the unet to keep the character the same. And, I have found the relevant code in the controlnet scripts for sd-web-ui in extensions\sd-webui-controlnet\scripts\global_state.py

![image](https://github.com/huggingface/diffusers/assets/108175311/e39de2a4-3039-4ad3-995e-2211e5e4882a)

If you want to extract the similar features as this, you can refer to the attend_and_excite pipeline.

**Comment by zhuraromdev** [comment]
Oh, didn't know about that pipeline. Thank you a lot!

**Comment by lingcong-k** [comment]
@patrickvonplaten do we have reference_only  for inpainting too?  I did not find anywhere. thanks :)
