### ISSUE TITLE
is there any pipeline for outpainting?

### ISSUE THREAD

**Issue by zhaoyun0071** [huggingface/diffusers#6080]
outpainting is very interesting 

does diffusers support it?

**Comment by Brembles** [comment]
@a-r-r-o-w  Hi, I am very interested in outpainting. Can you share it with me

**Comment by a-r-r-o-w** [comment]
> @a-r-r-o-w Hi, I am very interested in outpainting. Can you share it with me

Checkout the code and usage in my previous reply @Brembles :) It's doesn't support much but is good enough to get started I think. Will add more features if there's interest to add as community pipeline.

**Comment by Brembles** [comment]
> > @a-r-r-o-w你好，我对外画很感兴趣。你能和我分享一下吗？
> 
> 查看我之前回复中的代码和使用方法@Brembles:) 它支持不多，但我认为足够开始使用。如果有兴趣添加社区管道，将添加更多功能。
I discovered a problem. When the strength parameter is adjusted to any parameter other than 1, outpainting will be invalid, even 0.99.

**Comment by a-r-r-o-w** [comment]
@Brembles I've come across the issue too. The reason, I believe, is that when we're performing the outpainting, the transformations on the image is done on a black canvas (the example below is outpainting in backward direction).

![image](https://github.com/huggingface/diffusers/assets/72266394/ab049b2f-abc4-4740-a4f9-84d88fab5277)

This causes loss of information and results in bad quality unless the noise added is completely random (the case with strength=1). This implementation is a very rough combination of many ideas by others and there's a lot of room for improvement. I'm a bit busy this week but I'll try improving and having something better ready over the weekend.

One quick solution that seems to produce better results for other strength values is performing the transformations with the original image as canvas instead of the black background. Just modify the code for pasting transformed image on the original image in `_translate_image_and_mask`.

**Comment by Brembles** [comment]
> @Brembles我也遇到过这个问题。我认为原因是，当我们执行外画时，图像上的变换是在黑色画布上完成的（下面的示例是向后方向的外画）。
> 
> ![图像](https://private-user-images.githubusercontent.com/72266394/289832841-ab049b2f-abc4-4740-a4f9-84d88fab5277.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDM2OTMsIm5iZiI6MTcwMzE0MzM5MywicGF0aCI6Ii83MjI2NjM5NC8yODk4MzI4NDEtYWIwNDliMmYtYWJjNC00NzQwLWE0ZjktODRkODhmYWI1Mjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYTM1Y2M5N2JhYzc0Njg0NDE1N2I3OTUwM2QzYjM5ZTQ0Y2QxYzcxYzgxNTVkZmYxYTk4Y2RlZTk1NTk2OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rUxf-hJIgALo6rYK6jgRMZ1G3b6uDboH-8JY6WZGrzc)
> 
> 这会导致信息丢失并导致质量较差，除非添加的噪声是完全随机的（强度=1的情况）。这个实现是其他人的许多想法的非常粗略的组合，还有很大的改进空间。这周我有点忙，但我会尝试改进并在周末做好更好的准备。
> 
> 一种似乎可以为其他强度值产生更好结果的快速解决方案是使用原始图像作为画布而不是黑色背景来执行转换。只需修改 .txt 文件中将转换后的图像粘贴到原始图像上的代码即可`_translate_image_and_mask`。



Hi, if I don’t have the original image and it is a complete outpainting task, what should I do? I have tried some methods but the results are not ideal.

**Comment by a-r-r-o-w** [comment]
The current pipeline above is very basic and doesn't support XL. It should be quite easy to make it work with it though and can be done by deriving from SDXL and making necessary changes to __call__. I do plan on improving it but am quite busy with university and other contributions at the moment. It would be great if someone from the community could improve in this :)

**Comment by nanaj96** [comment]
> I have some code that I've been using for experimentation with outpainting from a few months ago. If it works for you, for the time being, it'd be awesome.

this is awesome can you tell me how can i use this code?

**Comment by a-r-r-o-w** [comment]
@sayakpaul @DN6 is this something that we could work on adding? There seems to a good amount of interest in diffusers supporting a infinite canvas outpainting pipeline similar to RunwayML's Infinite Image. I hope it'll be quite easy to replicate with high quality if done correctly.

**Comment by nanaj96** [comment]
here is only showing me the video code, and where are your image outpainting code and the main repository

**Comment by nanaj96** [comment]
i need to test it, if it works then i need you after this, we can discuss improving it

**Comment by DN6** [comment]
@nanaj96 @a-r-r-o-w This can be added as a community pipeline

**Comment by a-r-r-o-w** [comment]
> @nanaj96 @a-r-r-o-w This can be added as a community pipeline

Thank you. I'll take a better look and implement the SDXL versions as well very soon in an improved pipeline. There are many issues with what was shared above.

**Comment by sayakpaul** [comment]
I think this is not stale.

**Comment by a-r-r-o-w** [comment]
@sayakpaul Apologies for the delay here. I just haven't found time to get back to it. Most people use ComfyUI or other alternatives for outpainting but an example implementation, possibly as a community Mixin (because the changes are relatively simple) is something others from the community can work on if there's still a demand. So, maybe it'd be a good idea to add a contributions-welcome label for someone looking to get started with diffusers. Thanks

**Comment by sayakpaul** [comment]
@DN6 WDYT?

**Comment by sayakpaul** [comment]
CC: @asomoza

**Comment by asomoza** [comment]
We don't have an official outpainting pipeline but we do have three tutorials on how to do it with the current ones, they are in this [discussion](https://github.com/huggingface/diffusers/discussions/7750).

**Comment by yiyixuxu** [comment]
closing this for now! feel free to open a new issue if you have more questions
