### ISSUE TITLE
i2vgen-xl implement

### ISSUE THREAD

**Issue by zhw-zhang** [huggingface/diffusers#6186]
### Model/Pipeline/Scheduler description

I2VGEN-XL recently disclosed their training and testing codes for Wensheng videos and Tusheng videos. Does diffusers have any plans to integrate these models and codes?
Code:  [https://github.com/damo-vilab/i2vgen-xl?tab=readme-ov-file](url)

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by shauray8** [comment]
the link does not work, here's a new link - https://github.com/damo-vilab/i2vgen-xl

**Comment by sayakpaul** [comment]
We're happy to accept contributions for this.

**Comment by a-r-r-o-w** [comment]
@sayakpaul I'd be happy to try and take this up since I noticed it hasn't been picked up for a while. It seems a little difficult from first glance but I'm sure I'll be able to figure a neat way to merge into diffusers.

**Comment by sayakpaul** [comment]
Cc: @DN6

**Comment by cocktailpeanut** [comment]
+1 Really looking forward to this. This is a huge pain point for all ModelScope models, because they are all hosted in China and it's near impossible to download the file from outside of China (For example I tried for 24 hours yesterday, just to download the 5GB model file and failed in the end). Wrote a quick thread about the severity of this issue today actually: https://x.com/cocktailpeanut/status/1745152494320112082?s=20

Would be great if diffusers can build this into it and serve from huggingface, so people from outside China could play with Modelscope models.

**Comment by sayakpaul** [comment]
On our mind.
