### ISSUE TITLE
Does the IP Adapter support mounting multiple IP Adapter models simultaneously and using multiple reference images at the same time?

### ISSUE THREAD

**Issue by cjt222** [huggingface/diffusers#6318]

**Comment by sayakpaul** [comment]
Are you referring to something like so? 
https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/adapter#combining-multiple-adapters

I don't think we support the loading of multiple IP adapters at the moment. Cc: @yiyixuxu 

Do you have any convincing results from such a pipeline? Otherwise, it'd be hard for us to prioritize it.

**Comment by asomoza** [comment]
I would like to comment here since is something I'm currently looking at, multiple IP Adapters its useless if it doesn't support attention masking, but with that its really good, I don't have examples but you can watch the video of the developer that made the node for comfyui:

https://www.youtube.com/watch?v=vqG1VXKteQg&t=470s

this really opens up a lot of options for generation, also its good to use them when the images are big and you don't want to lose details, so you can divide the image and assign ip adapters to the portions of the image to make the final generation.

Finally its not that important to me since it can be done outside of diffusers, but the multiple images option is really popular right now and its better know as "instant-lora", where you feed multiple images to one IP-Adapter and they're combined in the attention layer.

**Comment by sayakpaul** [comment]
Thanks for the pointers. Would be great to have some code references if you have any.

**Comment by whiterose199187** [comment]
hi @sayakpaul 

Here are some relevant discussions I found:

https://github.com/tencent-ailab/IP-Adapter/issues/45
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/145#issuecomment-1867473832

**Comment by asomoza** [comment]
I have a couple of things to do before I can get into this but here's the invokeai implementation of the multiple adapters:

https://github.com/invoke-ai/InvokeAI/pull/4818/files

and here's the code for the ip-adapter node attention masks:

https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/ebd946f9477e3512d28f0203815a9d046c1fe05e

**Comment by asomoza** [comment]
I did a test in comfyui to get a better understanding:

|Image 1|Image 2|Mask|Image 3|
|---|---|---|---|
|![20231226020109](https://github.com/huggingface/diffusers/assets/5442875/c984dd34-968e-429c-b3b4-2cac7f228a59)|![20231226022943](https://github.com/huggingface/diffusers/assets/5442875/8e58427d-e992-46d2-9172-aa0c02415998)|![20231226025320](https://github.com/huggingface/diffusers/assets/5442875/683501aa-3ec6-4730-967a-4725cf4d851b)|![mask](https://github.com/huggingface/diffusers/assets/5442875/16b3e3e0-3994-4323-ad63-9bdd6c435724)
|||||

### Instant lora
Image 1 and image 2 at same weight
![normal](https://github.com/huggingface/diffusers/assets/5442875/8f5e9908-52ab-4cd7-878e-f0a3a9ccf344)
More weight image 1
![weight_2](https://github.com/huggingface/diffusers/assets/5442875/5430ed44-d31f-432e-a6bb-7056ca6b1102)
More weight image 2
![weight_1](https://github.com/huggingface/diffusers/assets/5442875/c184e8fb-01b3-4ac9-84b7-ed7320b05ff5)
All three images same weight
![three_images](https://github.com/huggingface/diffusers/assets/5442875/bc0c93d1-d65d-47b4-b201-fcdd171a9ca5)

### Multiple IP Adapters with attention masking
Using the mask for the people only (in comfyui you can assign a mask to a color) and the prompt "two women holding each other"

same weight for each adapter produces a "two faces" effect:
![full_weight](https://github.com/huggingface/diffusers/assets/5442875/44aff624-15ae-4557-8175-485cda0ff4bc)

lowering the weight of each ip adapter produces the desired effect:
![lower_weight](https://github.com/huggingface/diffusers/assets/5442875/be8f8089-4162-4284-8898-831e4fdcadec)

and using the third image as a background:
![ComfyUI_temp_hevgl_00083_](https://github.com/huggingface/diffusers/assets/5442875/85b96a1d-ce8d-4744-b47d-82119ebb4828)

hope it helps to better understand how do they work together.

**Comment by whiterose199187** [comment]
Hello folks,

Is there any plan to support this capability in diffusers?

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu

**Comment by yiyixuxu** [comment]
I think code wise it's pretty straightforward to support multiple ip-adapters. 

However, I'm trying to understand if it makes sense to support this for every single pipeline? i.e. text2img, img2img, inpaint, controlnet? 

@asomoza said it does not work great without the mask -  this makes me think maybe we just need one community text2img pipeline that supports multiple ip-adapter, along with the mask. Let me know what you think!

**Comment by thibaudart** [comment]
> I think code wise it's pretty straightforward to support multiple ip-adapters.
> 
> However, I'm trying to understand if it makes sense to support this for every single pipeline? i.e. text2img, img2img, inpaint, controlnet?
> 
> @asomoza said it does not work great without the mask - this makes me think maybe we just need one community text2img pipeline that supports multiple ip-adapter, along with the mask. Let me know what you think!

yes, often when we worked on some image we used:
- ipadater for style (with multiple reference images)
- another one for face
- some controlnet too

we generate a first image then we work on it using img2img and inpainting.

**Comment by asomoza** [comment]
Multiple IP Adapters without masks won't do any harm though, but IMO is just the more or less the same as one with multiple images (weighted).

I always though that diffusers pipelines were just examples so a community pipeline as an example would be sufficient and people can use it as a reference for their own. But personally I use them with controlnet and/or t2i adapters and masks all the time and almost never use them alone.

The same as a mask, I did an example with just one mask but it would be better to be able to provide each adapter with its own mask.

Probably the list for use them in a community pipeline that would be useful is

- Multiple IP Adapters with masks
- Multiple weighted images with each adapter
- Negative noise for each image (it really makes a difference)
- Controlnet and T2I Adapters
- Start and end in steps or % for each adapter

I don't see that much use for them in img2img or inpainting but I must admit I haven't tested them that much for that tasks.

**Comment by thibaudart** [comment]
no multi ip adapters without mask are so helpful:
one for style
one for face (using a different checkpoint)

**Comment by asomoza** [comment]
no worries, its just my experience, but in my tests the face adapter also interferes with the style so for me its better to use a mask for the face too.

**Comment by thibaudart** [comment]
i generally use weight 30% for face and 70% for style.

**Comment by yiyixuxu** [comment]
I think we can:
1. support MultiIPAdapter for all the pipelines without mask
2. add a community pipeline for the masking capability 

what do you guys think? 

cc @vladmandic for his insights too

**Comment by vladmandic** [comment]
@yiyixuxu thanks for looping me in - and i think you're spot on.

Big value of ipadapters is their ease-of-use. and having multiple ipadapters does come up quite often.
(ipadapters are basically a fancy embeddings (done using different clip models depending on the adapter) with fixed vector count)

On the other hand, as soon you have masking of any kind in the picture, the user intention is far more manual process and its totally fine to have separate pipeline.

A bit off-topic - having separate pipelines in diffusers for features is somewhat cumbersome, especially since pipeline inheritance is less than ideal (e.g. why doesn't StableDiffusionImage2ImagePipeline inherit from StableDiffusionPipeline so I cannot check current model type easily?) and AutoPipeline is does not have full coverage and `.from_pipeline` even less.

IMO, we need a cleaner way to switch pipelines for already loaded pipeline - right now I'm instantiating it manually using loaded pipeline components, but it does cause issues with model offloading and things like that).

Especially using community pipelines - I cannot load from scratch just to run one generate. I want to switch to it when I want to use specific feature and then switch back.

**Comment by asomoza** [comment]
yeah, I'm targeting a more professional use case (like photoshop) and no a so creative, automated or simple one, that's why I was just telling my opinion, masking without a UI is not a use case I would think people would use a lot if is not done automatically which us not the case here, also lowering the IP Face adapter to a 30% just to make it work with other adapters is not ideal for me too.

@yiyixuxu anything that could be added to the core diffusers and not pipelines works for me, right now to use them I had to monkey patch the attention processor and the unet forward method which is not ideal, the less I have to do that the better. Just the addition of multiple IP adapters would help a lot.

@vladmandic  what you're commenting is the core reason I don't use pipelines, they're too rigid to be able to use them in UIs were people need the freedom to add or remove any features they want, you would need to make a pipeline for all the possible combinations or a huge one with everything in it, but I really like the design of them since they're really easy to follow and understand as a starting point.

Just another two cents here, I don't think they need to be added to diffusers but if you want to make it easier to use for people, you could add an automated negative noise image to the pipeline, here's an example of the difference:

|source image| without noise| with noise|
|---|---|---|
|![woman](https://github.com/huggingface/diffusers/assets/5442875/a01319f3-460f-405c-9d58-5ec253309dbe)|![20240110100258](https://github.com/huggingface/diffusers/assets/5442875/0fc64c33-ca87-4147-a427-81320a0a5135)|![20240110100319](https://github.com/huggingface/diffusers/assets/5442875/7a9f8e6f-a485-4830-aaaf-826f3bc5c934)|

Thanks for taking our opinions into account.

**Comment by yiyixuxu** [comment]
Cool! I will put out an issue. If no one picks it up quickly, I will work on it.

Also, I just looked into the mask-related code a little bit more https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/ebd946f9477e3512d28f0203815a9d046c1fe05e. 

I think maybe we can allow IP-Adapter masks to be optionally passed in `cross_attention_kwargs` and handle it from the attention processor class. My main concern is that we do not want to over-complicate the pipelines. If we can get away with not adding any additional code to the pipelines we are happy to support the IP adapter mask as well.

**Comment by hipsterusername** [comment]
FWIW Invoke has supported both multiple IP adapters and images for a while now - We implemented our support before it was in Diffusers, so aren't leveraging the diffusers pipeline, but it may be useful to use as reference since we're leveraging Diffusers underneath.

**Comment by sayakpaul** [comment]
Links to relevant pieces of code would be much appreciated.

**Comment by asomoza** [comment]
I post them before but this are the PRs from InvokeAI:

Multi-Image IP-Adapter: https://github.com/invoke-ai/InvokeAI/pull/4882/files
Support multiple IP-Adapters (workflow editor only): https://github.com/invoke-ai/InvokeAI/pull/4818/files

I learn from them too, very cool project.

**Comment by yiyixuxu** [comment]
I'm starting to work on this now. We opened a discussion here too https://github.com/huggingface/diffusers/discussions/6544. 

It would be very nice if any of you can provide an example that I can play with that includes:
1: IP-adapter model checkpoints you used and their respective scale weights 
2. input images and other inputs needed, i.e. prompts etc
3. expected outputs from either ComfyUI or invoke

**Comment by thibaudart** [comment]
> I'm starting to work on this now. We opened a discussion here too #6544.
> 
> It would be very nice if any of you can provide an example that I can play with that includes: 1: IP-adapter model checkpoints you used and their respective scale weights 2. input images and other inputs needed, i.e. prompts etc 3. expected outputs from either ComfyUI or invoke

of course:

here's my comfyUI workflow: https://github.com/fictions-ai/sharing-is-caring/blob/main/workflow_controlnet_ipadapter.json 
an archive for style: https://github.com/thibaudart/dreambooth-768/raw/main/style_ziggy.zip 

For models, I used SDXL versions:
https://huggingface.co/h94/IP-Adapter/blob/main/sdxl_models/ip-adapter-plus-face_sdxl_vit-h.safetensors
https://huggingface.co/h94/IP-Adapter/blob/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.safetensors

**Comment by yiyixuxu** [comment]
hi @thibaudart 
in addition to the style images, would you be able to provide the face image input, prompt, and maybe an expected output? it will be super helpful. 

I started the PR here https://github.com/huggingface/diffusers/pull/6573. The test example I used did not have very meaningful results

**Comment by thibaudart** [comment]
input portrait: ![ComfyUI_temp_axfqk_00001_](https://github.com/huggingface/diffusers/assets/103603084/ab6ca776-30d7-4a21-a29d-67c73d753eff)
prompt: wonderwoman
Face weight: 0.3 
Style weight: 0.7
Result: ![image](https://github.com/huggingface/diffusers/assets/103603084/6f9140f8-159b-4af3-b721-828ac56dbbad)

**Comment by yiyixuxu** [comment]
@thibaudart thanks!

so cool !! 🤩

**Comment by thibaudart** [comment]
@yiyixuxu my pleasure.

**Comment by sayakpaul** [comment]
@yiyixuxu has a done great job of adding its support in https://github.com/huggingface/diffusers/pull/6573. Look out for the merge :)

**Comment by asomoza** [comment]
Thank you for your hard work @yiyixuxu.

**Comment by yiyixuxu** [comment]
@asomoza I'm not too familiar with the "negative noise" feature you pointed out here. 
can you provide some reference?

**Comment by asomoza** [comment]
no problem @yiyixuxu , the IP Adapters allow to pass a negative image which is rarely used, in fact in the diffusers code, the implementation it's just to create a zero filled tensor for each image:

https://github.com/huggingface/diffusers/blob/093a03a1a1f0b10ed1b2cd64056bb436534c3e26/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L538-L540

What I do and thanks to the developer (@cubiq) of the ComfyUI IPAdapterPlus Node (I saw this there and nowhere else) is to instead pass a noisy image created from the original image, for this I just use the same code:

```python
    image = image.permute([0,3,1,2])
    torch.manual_seed(0) # use a fixed random for reproducible results
    transforms = TT.Compose([
        TT.CenterCrop(min(image.shape[2], image.shape[3])),
        TT.Resize((224, 224), interpolation=TT.InterpolationMode.BICUBIC, antialias=True),
        TT.ElasticTransform(alpha=75.0, sigma=noise*3.5), # shuffle the image
        TT.RandomVerticalFlip(p=1.0), # flip the image to change the geometry even more
        TT.RandomHorizontalFlip(p=1.0),
    ])
    image = transforms(image.cpu())
    image = image.permute([0,2,3,1])
    image = image + ((0.25*(1-noise)+0.05) * torch.randn_like(image) )   # add further random noise
```

https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/46241f3ba5401f076f8d90c2aa85f2194910e1a9/IPAdapterPlus.py#L170

Where `noise` is the parameter I control with the UI for each image in each IP Adapter, so for example in the case of just one image:

IP Adapter
|Source|zero filled negative|0.05 noise|0.2 noise|1 noise|
|---|---|---|---|---|
|![woman](https://github.com/huggingface/diffusers/assets/5442875/7f9fc7e8-62a5-40b2-9538-ef7921a39c48)|![20240201055830](https://github.com/huggingface/diffusers/assets/5442875/3a0d7968-7e4f-4b9c-9d59-1c69d6f48719)|![20240201060009](https://github.com/huggingface/diffusers/assets/5442875/49d940b0-ad3d-437e-8bd0-d69c79c8d1e8)|![20240201060345](https://github.com/huggingface/diffusers/assets/5442875/6dd725fa-e0e7-45a9-af73-e17228b5b46b)|![20240201060441](https://github.com/huggingface/diffusers/assets/5442875/dcd3d233-fa25-4ad0-8adb-66a7e883a6f3)

IP Adapter PLUS
|zero filled|0.05 noise|0.2 noise|1 noise|
|---|---|---|---|
|![20240201060829](https://github.com/huggingface/diffusers/assets/5442875/8d3126d2-204e-43a7-8a3d-1d68aff1f5fa)|![20240201060943](https://github.com/huggingface/diffusers/assets/5442875/361cbf11-f558-4554-9ffb-925760b8d206)|![20240201061006](https://github.com/huggingface/diffusers/assets/5442875/fea0e59a-db8d-4b6e-983c-2f7d168e8026)|![20240201061053](https://github.com/huggingface/diffusers/assets/5442875/d4267f71-772d-4a19-a908-4b8b0d85a993)

What it does is that it allows more freedom to the generation so it can add more details or you can change more the image with a prompt, for example, the same image with the prompt "white background" and a t2i line art adapter:

|zero filled|0.2 noise|1 noise|
|---|---|---|
|![20240201061954](https://github.com/huggingface/diffusers/assets/5442875/5ffa5369-27b2-4dcc-b04d-7e351e859b82)|![20240201062159](https://github.com/huggingface/diffusers/assets/5442875/6c8c2917-7026-482a-8cbf-78f7f58b1e8c)|![20240201062011](https://github.com/huggingface/diffusers/assets/5442875/cefc3928-4f0d-4381-a365-0382f9259764)|

This is also good for styles, for example if we take the same example we were using of the "wonder woman"

|zero filled style|1 noise style|
|---|---|
|![20240201062808](https://github.com/huggingface/diffusers/assets/5442875/1595a067-54ed-46e7-b980-1c7092cbb2e6)|![20240201062905](https://github.com/huggingface/diffusers/assets/5442875/eb8ed77b-9458-4968-89ff-f121beaac0e8)|

so at the end, is just another parameter you can use to control the generation, IMO it makes them better but sometimes I need the details so the zero filled tensor also works. The ComfyUI Node implements the noise at the Adapter level which means that all the images of the same adapter have the same amount of noise (makes more sense for diffusers) and I for more control implemented this on each image.

I really don't know if this should be implemented in diffusers since I think most people don't want to make too much effort in the generations and it might become too cumbersome without a user interface.

**Comment by cubiq** [comment]
you can create custom noise and send it to the negative image. It also works very well with mandelbrot noise.

![img](https://raw.githubusercontent.com/cubiq/Diffusers_IPAdapter/main/assets/cover.webp)

**Comment by asomoza** [comment]
thanks @cubiq, I tested it with mandelbrot noise and indeed it works nice, specially for the normal IP Adapter. I will add it too, and also test more kind of noise algorithms.

Just for the fun of it I linked the noise slider with the iterations.

|Zero|10 iterations|50 iterations|100 iterations|
|---|---|---|---|
|![20240201114241](https://github.com/huggingface/diffusers/assets/5442875/2c0857cb-a25e-4dd3-b3cc-0b26162ddfa9)|![20240201114300](https://github.com/huggingface/diffusers/assets/5442875/c3a67ec4-cb3e-4de9-8267-b9291247ce1c)|![20240201114702](https://github.com/huggingface/diffusers/assets/5442875/e412e72a-c0d6-4724-aaa3-6d73a7061e07)|![20240201114713](https://github.com/huggingface/diffusers/assets/5442875/e1a38357-09d5-4816-90fd-29024ee75c53)|

**Comment by cubiq** [comment]
nice! you probably need to lower the CFG or use some kind of CFG rescaling strategy

**Comment by yiyixuxu** [comment]
@asomoza @cubiq 

I think maybe we can just create a nice section on our doc about this!! no? We introduced the `ip_adapter_image_embeds` arguments now thanks to @sayakpaul. We can just create the image embedding with the negative noise and pass it to the pipelines as `ip_adapter_image_embeds`. We don't need to add any code to diffusers this way 

let me know what you think! 
cc @stevhliu here too

**Comment by asomoza** [comment]
I'm having my doubts about the negative noise being useful in diffusers, you need to fiddle with it a lot to get the results you want, this is easy with UIs but to run the entire pipeline again to see if the output gets any better is not very practical. 

I added and tested 6 types of noise and each of them gives different results which makes it even more harder to test in a pipeline.

Maybe this would be better in the new `tips and tricks` section you're thinking about adding with a basic example. If people are interested or use it, then maybe we can expand on it.

**Comment by sayakpaul** [comment]
Closing this as it seems we have added support for the feature from many different angles. Feel free to reopen if that's not the case.
