### ISSUE TITLE
ControlNet Annotators to ONNX

### ISSUE THREAD

**Issue by jdp8** [huggingface/diffusers#6412]
**Is your feature request related to a problem? Please describe.**
At the moment I am able to use [Canny Edge Detection](https://github.com/dakenf/diffusers.js/pull/8), [Pose Estimation and Semantic Segmentation](https://github.com/dakenf/diffusers.js/pull/11) (all in JavaScript) in [diffusers.js](https://github.com/dakenf/diffusers.js) for the annotation (pre-processing) of images that are used as input for various ControlNets. These are the only ones that I've managed to implement so far but there are more Annotator models such as Scribble, HED, M-LSD, etc that I have not found a JavaScript implementation for. It would be useful to have these models in ONNX format so they can be called the same way as an UNET, VAE or other model.

**Describe the solution you'd like.**
A script that can convert the Annotator models to ONNX format or the models directly in ONNX format so they can be used in diffusers.js. I believe the original implementation is [controlnet_aux](https://github.com/patrickvonplaten/controlnet_aux) by @patrickvonplaten.

**Describe alternatives you've considered.**
I've tried using JavaScript to annotate images and so far I have Canny Edge Detection, Pose Estimation and Semantic Segmentation thanks to [OpenCV.js](https://docs.opencv.org/4.x/d5/d10/tutorial_js_root.html).

**Additional context.**
N/A.

**Comment by sayakpaul** [comment]
It's outside the scope of `diffusers`.

**Comment by xenova** [comment]
Although this might be of interest to the [Optimum](https://github.com/huggingface/optimum) team (regarding conversions to ONNX; cc @fxmarty), I see that you've already opened up a new request [here](https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16/issues/52), and I believe they will be able to provide you with the assistance you need. 😇 

I will close the issue for now (since this is unplanned and out of scope), but feel free to respond with questions (or tag us in the other thread).
