### ISSUE TITLE
[consistency distillation] LoRA scripts omits EMA update

### ISSUE THREAD

**Issue by jon-chuang** [huggingface/diffusers#6505]
### Describe the bug

Consistency distillation scripts omit EMA update of teacher unet

I think that this will limit the quality in the training limit, as the teacher will not be updated to produce better one-step denoising.

I think the idea of EMA is that it can mimic something like progressive distillation, which in itself is shown to improve few-step diffusion over baseline.

### Reproduction

Check the scripts

### System Info

main

### Who can help?

cc @shuminghu regarding whether EMA was necessary to achieve high quality results for LCM.

**Comment by dg845** [comment]
The LCM distillation scripts should do an EMA update of `target_unet` here (e.g. for SD 1.X/2.X):

https://github.com/huggingface/diffusers/blob/a551ddf928f02419432263f39dc0109b74f004f7/examples/consistency_distillation/train_lcm_distill_sd_wds.py#L1344-L1346

Note that `teacher_unet` never gets modified during distillation. The script maintains online and target `unet` models during distillation, following the [original consistency models (CM) paper](https://arxiv.org/pdf/2303.01469.pdf) and the [LCM paper](https://arxiv.org/pdf/2310.04378.pdf); I believe the reasoning is that if we used only one student `unet` the consistency distillation target value would depend on the same parameters we want to optimize (since it will also be calculated using `unet`), causing training instability (see Section 4 of the CM paper).

Note that the LCM-LoRA distillation scripts do not maintain a separate `target_unet` since we found this to be unnecessary during training.

cc @luosiallen, @patil-suraj

**Comment by shuminghu** [comment]
@jon-chuang  You might have misunderstood teacher_unet. As @dg845  mentioned, teacher_unet is never modified. It's used to get [x_prev](https://github.com/huggingface/diffusers/blob/a551ddf928f02419432263f39dc0109b74f004f7/examples/consistency_distillation/train_lcm_distill_sd_wds.py#L1306) with DDIM solver to feed into target_unet(which is an EMA update of unet) in the distillation script linked above.

**Comment by jon-chuang** [comment]
Sorry guys, my observation was limited to the LoRA scripts only.

I figured out a way to apply EMA as follows:

```python
@torch.no_grad()
def update_ema(target_params, source_params, rate=0.99):
    """
    Update target parameters to be closer to those of source parameters using
    an exponential moving average.

    :param target_params: the target parameter sequence.
    :param source_params: the source parameter sequence.
    :param rate: the EMA rate (closer to 1 means slower).
    """
    for targ in target_params:
        src = None
        while (src is None or src.shape != targ.shape):
            src = next(source_params, None)
            assert src is not None
        targ.detach().mul_(rate).add_(src, alpha=1 - rate)
    assert next(source_params, None) is None
```

I also do the following:

```python
unet.fuse_lora()
update_ema(teacher_unet.parameters(), unet.parameters(), rate=0.99)
unet.unfuse_lora()
```

> Note that teacher_unet never gets modified during distillation.

I see, so I guess this above usage is wrong, I need to maintain an additional `target_unet`.

> Note that the LCM-LoRA distillation scripts do not maintain a separate target_unet since we found this to be unnecessary during training.

I see. Did you find conversely that EMA was unnecessary for non-LoRA as well? Maybe it wasn't that important after all.

**Comment by jon-chuang** [comment]
> causing training instability 

Btw, you know what guys, I've seen a lot of training instability for my LCM-LoRA runs, so it may be important after all, just saying.

**Comment by shuminghu** [comment]
> Btw, you know what guys, I've seen a lot of training instability for my LCM-LoRA runs (leading to results that resemble overly high CFG), so EMA may be important after all, just saying.

Interesting. LoRA has much fewer number of params need to be updated. It is likely more stable than full FT?

By the way, Improved training on CM [paper](https://arxiv.org/abs/2310.14189) removed EMA for CT and presents "_a theoretical argument indicating that the EMA decay rate for the teacher network should always be zero for CT, although it can be nonzero for CD_".  Upon re-inspecting the paper, I also realized where the confusion in naming is from. "teacher network" from the paper correponds to `target_unet` not `teacher_unet` in current code space.

**Comment by dg845** [comment]
I have opened a PR to allow a target model to be optionally used in the LCM-LoRA scripts at #6537.
