### ISSUE TITLE
Better mechanism for getting values to attention processors

### ISSUE THREAD

**Issue by spezialspezial** [huggingface/diffusers#6601]
I think it would be nice to generally have some better infrastructure/mechanism for getting values to attention processors.

At the moment the main means of transportation seems to be cross_attention_kwargs but they are finally expanded as function arguments and have to match ALL function signatures that receive them. That's why there is a lot of dict gymnastics before the call. Just further passing the dict via reference where every processor may pick what it needs not bothering with other items would be more flexible imo.

In my mind pipeline and processors should be the malleable 'loose ends' to modify and swap with infrastructure in between rarely in need of adjustment.

**Comment by sayakpaul** [comment]
Great discussion start! Do you have any API design blocks in mind? 

Cc: @patrickvonplaten @DN6

**Comment by spezialspezial** [comment]
Other than the mentioned I'm not versed enough to talk about unet architecture but a pre-unet-evaluation callback inside the inference loop would probably help not having to modify all pipelines in some cases. BTW I really liked the `callback_kwargs[k] = locals()[k]` construct for the step_end_callback. Very elegant solution covering most needs. Maybe if the output would be generalized too it could be easily reused in other places.

**Comment by sayakpaul** [comment]
@yiyixuxu WDYT?

**Comment by asomoza** [comment]
I would also like to support this issue, for example for IP Adapters we can just pass the image embeds in the `cross_attention_kwargs` and manage them inside the IPAttentionProcessor but you seem to be against this since for this to happen you need to enable the pass of the `**kwargs` in the attention processors, but in this comment it clearly states that you're not in favor of this:

https://github.com/huggingface/diffusers/pull/6573#discussion_r1458607198

So the implementation right now is that you concatenate the the image embeds with the encoder_hidden_states like this:

```python
image_embeds = added_cond_kwargs.get("image_embeds")
image_embeds = self.encoder_hid_proj(image_embeds).to(encoder_hidden_states.dtype)
encoder_hidden_states = torch.cat([encoder_hidden_states, image_embeds], dim=1)
```

and then in the attention processor, you revert it to get the image_embeds:

```python
# split hidden states
end_pos = encoder_hidden_states.shape[1] - self.num_tokens
encoder_hidden_states, ip_hidden_states = (
    encoder_hidden_states[:, :end_pos, :],
    encoder_hidden_states[:, end_pos:, :],
)
```

this forces me to monkey patch the unet forward method and implement my own version of the AttentionProcesors just to be able to manage the `image_embeds`.

**Comment by asomoza** [comment]
I prefer to write here instead of the IP Adapters PR since this is more of a general design issue and not specific to IP Adapters, but now I understand the reasoning behind not using  `**kwargs` with the comment from @patrickvonplaten in https://github.com/huggingface/diffusers/pull/6573#discussion_r1463072069. For me it works whatever method you decide is best for diffusers that allows to pass values directly to the attention processors.

Most systems that reuse the inputs for multiple generations, like UIs or node systems (a good node system doesn't run nodes that haven't changed), can have a noticeable speed up if we just pass the values, in this case `ip_hidden_states`, directly to the attention processors without the dict (or tensor) gymnastics as @spezialspezial mentioned.

P.S.: The recent refactor of the `unet` made it so I don't need to monkeypatch the forward method anymore so thanks for that.

**Comment by sayakpaul** [comment]
I think this can be safely closed?

**Comment by yiyixuxu** [comment]
fixed in https://github.com/huggingface/diffusers/pull/6915
