### ISSUE TITLE
is save_state necessary for lora training scripts?

### ISSUE THREAD

**Issue by philhatgames** [huggingface/diffusers#6632]
### Describe the bug

For examples/text_to_image/train_text_to_image_lora.py and examples/text_to_image/train_text_to_image_lora_sdxl.py:
During training checkpointing accelerator.save_state(save_path), is used to save a full pytorch_model.bin (could be a couple GBs),
Whereas after training is finished, just pipeline.save_lora_weights() is used to save the lora weights

### Reproduction

N/A

### System Info

N/A

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by asomoza** [comment]
Is not necessary if you don't want to resume the training later, the "save state" saves the model and the optimizer state at that point of the training so you can do a "real" resume later. Kohya has a resume option without it and its really bad, most people won't ever use the resume because it's like you're starting from scratch with a partially bad trained model.

The last step of the training doesn't save the state since it assumes you're done with training.

**Comment by philhatgames** [comment]
I see, maybe a possible feature would have updated save_state/load_state that saves optimizer and other states, but can handle the lora/other use cases, so that the model doesn't need to be saved
