### ISSUE TITLE
stabilityai/stable-diffusion-2-1 is missing diffusion_pytorch_model.fp16.safetensors

### ISSUE THREAD

**Issue by githubGr1** [huggingface/diffusers#6652]

**Comment by a-r-r-o-w** [comment]
If possible on your end, you can create a local copy of the fp16 safetensors:

```py
import torch
from diffusers import DiffusionPipeline

model_id = "stabilityai/stable-diffusion-2-1"
pipe = DiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.save_pretrained(model_id, variant="fp16")
```

This will create a folder with vae, unet, etc. with the files saved in safetensors format. To convert to a single safetensors file in the original SD format, you can run [this](https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_sdxl.py) for SDXL and [this](https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py) for SD1.5. I'm not sure if the latter would work with SD2.1 as well because of different model architecture. If it doesn't, maybe you can ping someone from the diffusers team.
