### ISSUE TITLE
multi device inference of stable diffusion

### ISSUE THREAD

**Issue by zhangvia** [huggingface/diffusers#6679]
stable diffusion pipeline is typically composed of multiple Torch models. Many users employing this pipeline may not have high-end GPUs, leading to out-of-memory (OOM) issues when generating high-resolution results or using more models. So, why not load different models onto different GPUs, allowing the entire pipeline to run on servers with multiple GPUs with smaller vram? However, I anticipate that implementing this feature may require significant code modifications. Do you have any suggestions on how to support that?

**Comment by asomoza** [comment]
@zhangvia for splitting the models on multiple GPUs they're working on it, see #6396 

For using multiple models on different GPUs, since diffusers is a very flexible library, there's no limitation on that part, you can load multiple models, move them to whatever device you want and then move it back for inference in the pipeline, see: https://huggingface.co/docs/diffusers/using-diffusers/loading#swap-components-in-a-pipeline

If your referring to a method like `cpu_offload` or `sequential_cpu_offlload` that does the same with multiple GPUs, I don't know if they're going to make that, but IMO is not necessary since most of the people that use this library for APIs or UIs, will still need to implement our own solutions that fit our specific needs.

**Comment by zhangvia** [comment]
> @zhangvia for splitting the models on multiple GPUs they're working on it, see #6396

i thik this pr is working on split single model on different gpus. am i right?

> For using multiple models on different GPUs, since diffusers is a very flexible library, there's no limitation on that part, you can load multiple models, move them to whatever device you want and then move it back for inference in the pipeline, see: https://huggingface.co/docs/diffusers/using-diffusers/loading#swap-components-in-a-pipeline

i know this feature. but what i want is executing the pipeline on multiple gpus. for example, load the unet and controlnet to gpu 0, the rest of models on gpu1. and when use text2img pipeline. the pipeline will encode the prompt on gpu1, run the denoise iterations on gpu0 and decode the latents on gpu1. but now, i can only execute pipeline on single gpu. think about this, i load two controlnets and a whole text2img pipeline. i want to generate 1024*1024 image, that may need more than 20g vram, but i have two 12g vram gpus. i don't want to load the model to cpu, that will slow down the inference. now my solution is moving the varainces to the model device when some model need to use it in the pipeline. that is naive. so i'm finding some elegant solutions

**Comment by asomoza** [comment]
yes, that PR is for a single model, I wasn't sure what you were asking. I now see what you meant, I don't use diffusers pipelines but  for what you want you'll need to do a custom pipeline, it shouldn't be that hard but I'm not sure if you would have much more performance gain with that instead of just using `cpu offload`, @sayakpaul could have more insights about this.

**Comment by zhangvia** [comment]
> yes, that PR is for a single model, I wasn't sure what you were asking. I now see what you meant, I don't use diffusers pipelines but for what you want you'll need to do a custom pipeline, it shouldn't be that hard but I'm not sure if you would have much more performance gain with that instead of just using `cpu offload`, @sayakpaul could have more insights about this.

i did write my custom pipeline to load models to different gpus, i just feel that my custom pipeline was not so flexible. i just move the variables to the right device before the model inference. so i'm seeking some more flexible solution

**Comment by sayakpaul** [comment]
We have the following resources for multi-GPU inference:

* https://huggingface.co/docs/diffusers/main/en/training/distributed_inference (cc: @muellerzr)
* https://huggingface.co/docs/diffusers/main/en/api/pipelines/paradigms

We're [adding support](https://github.com/huggingface/diffusers/pull/6396/) for `device_map` too. Currently, it's being incorporated on a model-level. Once that's done, we will extend it to pipeline-level. Cc: @SunMarc

**Comment by zhangvia** [comment]
> We have the following resources for multi-GPU inference:
> 
> * https://huggingface.co/docs/diffusers/main/en/training/distributed_inference (cc: @muellerzr)
> * https://huggingface.co/docs/diffusers/main/en/api/pipelines/paradigms
> 
> We're [adding support](https://github.com/huggingface/diffusers/pull/6396/) for `device_map` too. Currently, it's being incorporated on a model-level. Once that's done, we will extend it to pipeline-level. Cc: @SunMarc

i see that. but is that can only used by setting the device_map=auto or {0:6GB,1:10GB}? i comment a test case in #6396,how can i use device map to inference like that?

**Comment by sayakpaul** [comment]
> how can i use device map in pipeline inference like that?

I think I mentioned it before a few times but right now the `device_map` support is not there for pipelines. In order to get there, we need to add support of `device_map` to the models which is what is being done in https://github.com/huggingface/diffusers/pull/6396. 

I have replied to the comments, a bit.

**Comment by sayakpaul** [comment]
Not stale.

**Comment by sayakpaul** [comment]
Closing because I think we support performing inference with multiple GPUs. For context-parallel inference, we are currently brainstorming things. But other repositories allow it already:

* https://github.com/chengzeyi/ParaAttention
* https://huggingface.co/docs/diffusers/main/en/optimization/xdit
