### ISSUE TITLE
[IP-Adapter] Adding IP-adapter masking feature

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#6802]
We just added multi-adapter and multi-image support for IP-Adapter https://github.com/huggingface/diffusers/pull/6573

Anyone interested in adding an IP adapter masking feature? It will allow you to divide the image and assign different ip-adapter to the specified portion of the image.

more information on the feature 
* a video about the feature in ComfyUI https://www.youtube.com/watch?v=vqG1VXKteQg&t=470s
* relevant code from ComfyUI https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/ebd946f9477e3512d28f0203815a9d046c1fe05e

notes on the design

* We can add community pipelines (text-to-image and ControlNet) that use multi-ip-adapter with mask 
* or, we can integrate this feature into core diffusers if we can add this feature without adding additional code to our pipelines. Some thoughts on how to achieve this:
   1. we can add utility functions to pre-process IP-adapter mask to our image processor class https://github.com/huggingface/diffusers/blob/c3369f56734beef9c4768d04cce490fdcc1c9162/src/diffusers/image_processor.py#L39
   2. the pre-processed masked can be passed down to `IPAdapterAttnProcessor/IPAdapterAttnProcessor2.0` via `cross_attention_kwargs`
   3. modify the `IPAdapterAttnProcessor/IPAdapterAttnProcessor2.0` so it can handle mask https://github.com/huggingface/diffusers/blob/c3369f56734beef9c4768d04cce490fdcc1c9162/src/diffusers/models/attention_processor.py#L2126

**Comment by yiyixuxu** [comment]
cc @asomoza

**Comment by fabiorigano** [comment]
hi @yiyixuxu thanks for mentioning me, I would be happy to contribute to this feature :)
I'll try adding it to core without changing the pipelines.

**Comment by asomoza** [comment]
I'm also implementing it in my code, so I can help in the PR if the need arises.

**Comment by Bhavay-2001** [comment]
Hi @yiyixuxu, can I work on this issue as well if it requires contributions from multiple people. If not, can you suggest me some other issue to work on? Thanks

**Comment by asomoza** [comment]
@yiyixuxu @fabiorigano I'm done with my implementation (not with a diffusers pipeline), but I'm kind of curious on how do you (or are going to) manage the masks and hopefully  it somewhere similar so I don't have to monkey patch more classes and methods from diffusers.

I did it like this, since I have an UI is what makes more sense to me:

The first part it's exclusively for my app, but I will show it here so you understand the context, I use a background image where I want to draw the masks, so in this case is this one which I generated in ComfyUI:

![ComfyUI_00021_](https://github.com/huggingface/diffusers/assets/5442875/578c4b43-1e25-4ae5-8cf3-a1bfc11fc607)

then I generate the masks drawing on top of it, in my case the colors don't matter, I use the alpha channel to create the mask later, the mask is a layer on top so everything that's not painted is transparent.

|image one|image two|
|---|---|
|![alpha_mask_one](https://github.com/huggingface/diffusers/assets/5442875/126c7161-7d5c-4b35-acff-eaf45be9bd9e)|![alpha_mask_two](https://github.com/huggingface/diffusers/assets/5442875/a54a1ed0-fa20-4b4d-8a8c-0ff0e8868b9f)|

In the next step I convert the alpha channel to a binary mask:
|mask one|mask two|
|---|---|
|![processed_mask_20240202101749](https://github.com/huggingface/diffusers/assets/5442875/330ba86a-c987-4b1e-a281-b6b9a4ac040b)|![processed_mask_20240202101757](https://github.com/huggingface/diffusers/assets/5442875/9fb27caf-7c90-4b00-aef4-58c6a25d3daf)|

So this two masks are the ones that diffusers could use, with this my results are like this:

|source one|source two|
|---|---|
![20240202170318](https://github.com/huggingface/diffusers/assets/5442875/cfd564f3-811a-4cd3-af9e-e4161bc66800)|![20240202170421](https://github.com/huggingface/diffusers/assets/5442875/442570c2-f1e6-4909-ad49-d9b61c903b9d)|

|result 1|result 2|result 3|
|---|---|---|
|![20240202170522](https://github.com/huggingface/diffusers/assets/5442875/d24e2aa0-4240-4de2-afd5-03d52649ccb6)|![20240202170559](https://github.com/huggingface/diffusers/assets/5442875/54446306-7f34-49a9-8b78-84bc472fb981)|![20240202170731](https://github.com/huggingface/diffusers/assets/5442875/995f1d56-ceda-40b0-8bab-3d0f0e687d48)|

I think it's so cool that we can mix styles like anime and 3D, anyway does this masks make sense to you or would it better to use the RGB approach that ComfUI uses? 

As for the implementation, for what I see the only code that should be added to the pipeline is the generation of the latent mask since we need the vae scale factor.

**Comment by yiyixuxu** [comment]
Thanks so much. This looks so cool! 
I don't have a very good idea how it is going to work yet. But we would very much like to have your input once the PR is up. 

@fabiorigano 
If you feel like you need to add the code for generating latent mask to the pipeline, feel free to add to one pipeline as an example, and we can refactor and try to move it out later

**Comment by scarbain** [comment]
Hi everyone, thanks for this very useful development for IP-Adapter. Is it possible to do the same for ControlNet ? Having multiple controlnets guiding different parts of the generation by giving masks for each conditions ?

**Comment by asomoza** [comment]
@scarbain I'm interested in this, I remember I saw that one of the UIs added support for it but don't remember which one. Can you open an issue with this and maybe post an example or a use case?

**Comment by hasini244** [comment]
can we combine more than two people under masking?

**Comment by asomoza** [comment]
yeah sure, but it gets really complex really fast, but there's no limit to this.

In this image, everyone has a mask and an IP Adapter associated to it.

![20240716052349](https://github.com/user-attachments/assets/17e813c4-9919-43e3-89d5-6ee0665ca62e)
