### ISSUE TITLE
Deteriorated Quality for DPM++ 2M Generations 

### ISSUE THREAD

**Issue by hipsterusername** [huggingface/diffusers#7331]
### Describe the bug

In Invoke's 3.6.3 version, we updated to the latest Diffusers available at the time (.26) for the benefit of the scheduler fixes.

A user has provided documentation/testing demonstrating that these updates seems to have resulted in some worsened quality for certain schedulers (tested evidence is for DPM++ 2M)

Below --

Pre .26
![32f59ecb-c909-4a96-9d6b-2523b933ce29](https://github.com/huggingface/diffusers/assets/31807370/2ccbbdb7-a2b2-4302-9504-61ad494f4d87)
![b7ae3ea8-95db-44af-a04e-210a08517419](https://github.com/huggingface/diffusers/assets/31807370/7a04d50c-5ec1-47b5-a407-0fe1335155ea)

.26
![9d8389f7-4f7c-4af2-a416-29b860176524](https://github.com/huggingface/diffusers/assets/31807370/ee802903-8636-4aca-bb1b-e8d7e1ace5ad)
![89e840ea-0611-4250-ac07-26d57a1cf79f](https://github.com/huggingface/diffusers/assets/31807370/b07b62d4-6f61-485c-a446-3db24cd5ccf2)

### Reproduction

Gen an SD1.5 image pre .26 and post .26 with DPM++ 2M

### System Info

Diffusers .27

### Who can help?

@sayakpaul @yiyixuxu

**Comment by yiyixuxu** [comment]
@hipsterusername 
hey can you provide a reproducible script?

**Comment by sayakpaul** [comment]
Maybe @asomoza has some suggestions here?

**Comment by asomoza** [comment]
I would need more information, like the prompt, steps and cfg to do some tests.

Also this is kind of subjective, probably it was because the user was used to the results before the schedulers fix. I'm not that used to the results of SD 1.5 but for me the pre .26 have more artifacts and also a black spot which makes them more real but that kind of artifacts were the ones that were fixed.

Also the results post .26 look more plastic which for me is the normal kind of result with SD 1.5 and they don't have the artifacts from before so they look more clean but at the same time more fake.

AFAIK this change can be reverted with the scheduler config, just need to change the `final_sigmas_type` configuration and the user should get the results from before but can check if I don't have generation info.

**Comment by yiyixuxu** [comment]
Closing this for now since we don't have the bandwidth & it is relatively low-prior 
will re-open if needed!
