### ISSUE TITLE
apple: support for MLX quantized linear in diffusers

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#7675]
**Is your feature request related to a problem? Please describe.**

As an Apple MPS user, it always feels somewhat like we're second-class citizens with respect to the latest and greatest optimisations that only happen for other platforms. The biggest deal is likely xformers/bitsandbytes which remain CUDA-only, but the outcome is more important than the codepath used to get there.

**Describe the solution you'd like.**

I've discovered Apple has some [MLX examples](https://github.com/ml-explore/mlx-examples/blob/main/stable_diffusion/txt2image.py) for T2I inference on SDXL and other SD models that allow AoT quantization of the unet and text encoders.

**Describe alternatives you've considered.**

There is [metal-flash-attention](https://github.com/philipturner/metal-flash-attention) but it would require writing integrating custom Metal kernels, which feels out of scope for Diffusers.

We also have a couple forks of bitsandbytes which aim to improve portability, but there's nothing actionable yet.

**Additional context.**

I haven't tried to implement it yet, it would probably require a bit of monkeying around.

**Comment by yiyixuxu** [comment]
cc @pcuenca here

**Comment by awni** [comment]
Diffusers MLX back-end? 👀 

That would be very cool

**Comment by bghira** [comment]
yes especially with larger models and apple themselves kinda dropping the ball repeatedly over multiple years on pytorch support. MLX is their bread and butter. it's so good that it should probably even be used by default on MPS instead of pytorch.

**Comment by guptaaryan16** [comment]
I am thinking about picking this issue up, as I have been recently reading about diffusion models a lot and wanna make it easy to use and finetune them using mlx similar to JAX backend in diffusers, any advice for the same @bghira @awni. Also is this issue available for open contributors?

**Comment by bghira** [comment]
this might be a bit much for a newcomer since tensors are not compatible between diffusers and mlx and memory copy between the libraries will be slow. if it can be done at all. you will have to abstract tensors in a way torch compile might not be happy with

**Comment by guptaaryan16** [comment]
@bghira Well I am familiar with the MLX cpp API and have experimented with `torch.compile` issues too, let me try this issue and ask any problems to you and if it felt too much for me, I will probably leave it for something else, does that seem okay?

**Comment by bghira** [comment]
no worries i waant sure how new, just wanted to clarify its not a copy paste thing but you sound equipped to take charge of this PR

**Comment by guptaaryan16** [comment]
hey @bghira I apologise for not keeping you in loop with what I have been working on, but seems like I was able to port some part of the schedulers in mlx along with the testing infra [here](https://github.com/guptaaryan16/mlx-diffusers/tree/mlx), it did took a good time to understand the diffusers codebase, now working on implementing the sd2 and sdxl in mlx based backend APIs [here](https://github.com/guptaaryan16/mlx-diffusers/tree/mlx_unet_tests), let me know if you like the implementation and any problems with it, I am planning to complete it ASAP

**Comment by bghira** [comment]
thanks for the update, nice work so far!

**Comment by guptaaryan16** [comment]
Finally got something working, the famous example from "CompVis/stable-diffusion-v1-4" repo generated below using MLX pipline. So the `MLXDDIMScheduler`, `MLXAutoencoderKL`, and `MLXUNet2DConditionModel` are ready and I have written a crude test script for running the above model (the stable diffusion 1-2 family) [here](https://github.com/guptaaryan16/mlx-diffusers/blob/stable_diffusion_1_exp/tests/pipelines/stable_diffusion/test_mlx.py). As for the benchmark time, it took me around 6 minutes (50 inference steps) to generate the image on Apple M1 macbook which I feel can be optimized further as all the pipeline parts get into the mlx as well as some more optimizations.
You guys can install the repo from the branch `stable_diffusion_1_exp` using `pip install -e ".dev"`  to test this.

The core idea of the port was to keep maximum similarity of PyTorch and MLX code so that it is pretty easy to convert and use code and model weights from PyTorch to MLX, thus making it easy for me and outside contributors.

And the model loading for PyTorch weights (right now only from safetensors) is easy with just some weights that need to be adjusted for the  `NHWC` format of MLX for 3d operations, and you can see the model loading file [here](https://github.com/guptaaryan16/mlx-diffusers/blob/stable_diffusion_1_exp/src/diffusers/models/modeling_mlx_utils.py). (I have tried my best to avoid any name changes in the weights from pytorch to MLX so that its very predictable and easy to debug rather than looking at individual weights for the "correct" ones)
Note: I have kept a flag `from_pt=True` for weights that are from PyTorch world and needs to be converted to MLX; i.e. their 3d format is NCHW to NHWC;  for now.

The next steps would be to write some more tests for the above pipeline portions and complete the `MLXStableDiffusionPipline` (maybe add the `MLXCLIPTextModel` like `FlaxCLIPTextModel` to transformers). Also I have to now work on making a common loading class for all `MLXStableDiffusionPipline` parts similar to PyTorch and Flax API. Finally I also want to experiment with metal flash attention and other parts that make the code really optimized.

![astronaut_rides_horse](https://github.com/user-attachments/assets/9022395c-e468-4ba8-83cf-ac80060a19c1)

Thanks @bghira for keeping the issue alive in discussion so that I got a chance to work on it, and hopefully we will have all the models from Stable Diffusion and Flux family be supported in mlx-diffusers soon !!!
Also thanks @awni @angeloskath for the MLX examples on stable diffusion which really helped in this port.

**Comment by bghira** [comment]
yes!! that is so cool. super glad to hear you kept up with the efforts (unlike my tinygrad equivalent 🤭) and that it is producing the expected results. cant waitnfor metal flash attn which is realy what draws me and others to metal direct extensions. again, congratulations on your success.

**Comment by pcuenca** [comment]
Amazing work @guptaaryan16! 🙌

**Comment by guptaaryan16** [comment]
Thanks @bghira @pcuenca really glad that you liked the work, its been a really good learning opportunity for me, and hopefully it will be ready for use for everyone pretty soon!!!
