### ISSUE TITLE
How to get config of single_file

### ISSUE THREAD

**Issue by suzukimain** [huggingface/diffusers#7740]
Hi,
Is there any way to get the equivalent of model_index.json from a single_file?

**Comment by standardAI** [comment]
[Is this what you are looking for?](https://huggingface.co/docs/diffusers/main/en/api/loaders/single_file#diffusers.loaders.FromSingleFileMixin.from_single_file.original_config_file)

**Comment by asomoza** [comment]
The `original_config_file` is just for each specific checkpoint though, the `model_index.json` file has this:

```
{
  "_diffusers_version": "0.26.0.dev0",
  "scheduler": [
    "diffusers",
    "EulerDiscreteScheduler"
  ],
  "text_encoder": [
    "transformers",
    "CLIPTextModel"
  ],
  "text_encoder_2": [
    "transformers",
    "CLIPTextModelWithProjection"
  ],
  "tokenizer": [
    "transformers",
    "CLIPTokenizer"
  ],
  "tokenizer_2": [
    "transformers",
    "CLIPTokenizer"
  ],
  "unet": [
    "diffusers",
    "UNet2DConditionModel"
  ],
  "vae": [
    "diffusers",
    "AutoencoderKL"
  ]
}
```

This is a `diffusers` config file, the other UIs except for InvokeAI don't have this and don't use it, I think most of them hard code the configurations and detect the models on load time, that's why diffusers can support a lot more models than the libraries that only use single file checkpoints.

So if you're asking that, the answers is no, you'll need to detect each model and load the configuration for each of them, in diffusers you can learn about this from this file:

https://github.com/huggingface/diffusers/blob/main/src/diffusers/loaders/single_file_utils.py

**Comment by suzukimain** [comment]
I see.I appreciate your kind response during your busy time.
