### ISSUE TITLE
[ONNX] Loading textual inversion .bin/.pt embeddings

### ISSUE THREAD

**Issue by GreenLandisaLie** [huggingface/diffusers#805]
I tried to follow this guide:
https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_conceptualizer_inference.ipynb
But OnnxRuntimeModel does not have any of the necessary functions that CLIPTextModel has and since I'm no dev I couldn't figure out how to get this working.
If this is already possible then I guess this issue is just about the lack of documentation on this subject, else this is something that should be added eventually.
Also, it would be cool if we could have a simple single function within the pipelines for this purpose.

**Comment by anton-l** [comment]
Hi @GreenLandisaLie! Unfortunately there's no way to seamlessly support ONNX models for textual inversion examples, since they modify the model itself, and the onnx graph is fairly static in its current implementation. 

I guess you could try loading the embeddings into a pytorch model first, save it, and then export it to ONNX with the default conversion script. But you'd have to do that for each learned concept :sweat_smile: 

Another alternative is to try updating the onnx model with the new embedding weights, similar to this discussion: https://github.com/onnx/onnx/issues/2978

**Comment by GreenLandisaLie** [comment]
Thank you @anton-l for looking into this. 
Its was silly of me to not have thought about taking advantage of the conversion scripts.
With that information I can probably get it working on my end. Still its something that needs to be considered in the future once ONNX gets past its experimental stage so I'll leave this issue open.
