### ISSUE TITLE
Community pipeline to run Stable Diffusion with k-diffusion

### ISSUE THREAD

**Issue by BurguerJohn** [huggingface/diffusers#854]
**Describe the solution you'd like**
I'm making a pipeline to use k-diffusion with Diffusers.
The code run from start to finish, but it's giving pretty bad outputs.
I did try to undestand both codes and I'm currently stuck in what could be possible wrong. Perhaps someone can shed some light  of what is wrong with my code? Once is ready, will make a pull request.

https://github.com/BurguerJohn/diffusers/tree/k_diffusion_community_pipeline

**Comment by keturn** [comment]
I think if you've got it far enough that it runs, you could open a PR with `[WIP]` in the title and in _Draft_ status. It'd be easier to comment on the code that way.

**Comment by BurguerJohn** [comment]
Alright, I'm not that used to git/github so was not sure how to proceed with this correctly.

**Comment by patrickvonplaten** [comment]
Hey @BurguerJohn, 

That's a great idea! Generally, the `k-diffusion` and `diffusers` API is a bit different as `k-diffusion` expects the model to be passed to the sampler which is not really possible with our native API, but it should definitely be possible in a community pipeline! 

It'd be super nice if you could open a WIP - also feel free to tag me and/or @anton-l so that we can help you. 
Also I think it could be a nice addition directly to the k-diffusion library to make the schedulers compatible with `diffusers` there. E.g. you could add a wrapper to `diffusers` here: https://github.com/crowsonkb/k-diffusion/blob/f4e99857772fc3a126ba886aadf795a332774878/k_diffusion/external.py#L131 . Think @crowsonkb would also be happy about such a PR :-)

**Comment by patrickvonplaten** [comment]
Ah PR is already here: https://github.com/huggingface/diffusers/pull/857 very cool!

**Comment by BurguerJohn** [comment]
> Hey @BurguerJohn,
> 
> That's a great idea! Generally, the `k-diffusion` and `diffusers` API is a bit different as `k-diffusion` expects the model to be passed to the sampler which is not really possible with our native API, but it should definitely be possible in a community pipeline!
> 
> It'd be super nice if you could open a WIP - also feel free to tag me and/or @anton-l so that we can help you. Also I think it could be a nice addition directly to the k-diffusion library to make the schedulers compatible with `diffusers` there. E.g. you could add a wrapper to `diffusers` here: https://github.com/crowsonkb/k-diffusion/blob/f4e99857772fc3a126ba886aadf795a332774878/k_diffusion/external.py#L131 . Think @crowsonkb would also be happy about such a PR :-)

Thanks for the feedback. As soon as I write the example code to call the pipeline and fix the style will see if they can give me some help with this =)
