### ISSUE TITLE
Differential Diffusion with SD3

### ISSUE THREAD

**Issue by exx8** [huggingface/diffusers#8577]
**Is your feature request related to a problem? Please describe.**
One might wish to soft inpaint or edit pictures with differential diffusion with SD3.

**Describe the solution you'd like.**
I believe we can port diff-diff to SD3, by adding a new pipeline for it.

**Describe alternatives you've considered.**
Diff-diff is already supported with XL.
Traditionally, diffusers supported inpainting via a custom checkpoint. 
I am not sure if SAI plans to release such a checkpoint for SD3.
 A port of differential diffusion for SD3 might fill this gap as well.

**Additional context.**
If I understand correctly, ComfyUI might already support diff-diff with SD3.

**Comment by asomoza** [comment]
I did a quick test to see if it worked in comfyui with diff-diff, I can't really tell if it works or not because I don't see the really good results I got with SDXL and diffusers. Maybe I'm doing something wrong with comfyui.

|source|without|with|
|---|---|---|
|![ComfyUI_00225_](https://github.com/huggingface/diffusers/assets/5442875/ad87dc69-8882-4572-8495-cf0649b25425)|![ComfyUI_00249_](https://github.com/huggingface/diffusers/assets/5442875/6063e10b-6550-4c13-b3ac-c0692e8af121)|![ComfyUI_00248_](https://github.com/huggingface/diffusers/assets/5442875/b53e7ed7-5918-4c26-9d5a-72a0e3663eff)|

I agree that diff-diff will fill the current lack of an inpainting model. I did the pipeline for SDXL but currently I won't have the bandwidth to do the SD3 one anytime soon. Are you willing to open a PR with it?

**Comment by exx8** [comment]
Hi,

I need to see the workflow to understand what you have tried so far. Currently, I do not have the capacity to open a PR according to the standards of diffusers.

I am considering adding a new release for my repo, which will hopefully support some or all of the new diffusion models, including SC, PixArt-Σ, SD3, and Hunyuan-DiT. I also need to consider how to support this research in the long run, as it is becoming increasingly demanding to support all these models.

Thanks!

**Comment by asomoza** [comment]
The images have the workflows in them, you can just drag them into comfyui.

It's fine if you don't have the time, maybe later we can ask the community to do them and just guide them though it.

The mask I used was simple but it worked fine with SDXL.

![mask](https://github.com/huggingface/diffusers/assets/5442875/5b04ce52-5059-43b8-8fcb-58e48620a57c)

**Comment by vikm2o** [comment]
I am facing an issue while adpting Diffrential Diffusion for SD3 . https://github.com/exx8/differential-diffusion/issues/28

prepare_latents in SD3 Pipeline produces latents of this shape `torch.Size([1, 16, 80, 120]) ` in this line https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3_img2img.py#L646

In SD2 its `torch.Size([101, 4, 80, 120])` for 100 steps.

**Comment by asomoza** [comment]
@vikm2o did you find a solution to your problem?

I had a little time today and did a quick custom pipeline for SD3, this is my example of the apple to pear I use for testing:

|source|mask|diffusers|comfyui|
|---|---|---|---|
|![20240623154600_1573149544](https://github.com/huggingface/diffusers/assets/5442875/1dba4f22-70a2-4332-9801-0c6303c690d3)|![gradient_mask](https://github.com/huggingface/diffusers/assets/5442875/ab375296-c7cf-4a85-8297-69e131923918)|![20240623192624_3869791386](https://github.com/huggingface/diffusers/assets/5442875/8538f796-f4df-4952-b241-e446bf60576b)|![ComfyUI_00264_](https://github.com/huggingface/diffusers/assets/5442875/bb642066-4b53-4f9e-8bb1-9154fb9a3418)|

I used another mask for comfyui because it doesn't work with normal grayscale masks. When I have more time I'll test with a real inpainting but it seems to work.

I had to make some core modifications so I'll sort those out first before sharing, diff-diff doesn't work without doing some changes in the scheduler (that's why you are getting the first dimension with 1 instead of the steps)

**Comment by vikm2o** [comment]
@asomoza amazing! Please share when you are ready. I would love to try.

**Comment by asomoza** [comment]
@vikm2o I opened the PRs to be able to use it. I didn't know if you wanted to open a PR for the community pipeline, if you want to do it, just tell me and I'll close mine.

**Comment by asomoza** [comment]
Also I did the same example with the dog, I think it works really well most of the time:

|original|result 1|result 2|
|---|---|---|
|![ComfyUI_00225_](https://github.com/huggingface/diffusers/assets/5442875/dcca1fbc-710f-42ad-8396-dfde66e62f4e)|![20240624025353_960321792](https://github.com/huggingface/diffusers/assets/5442875/d8ba2f6a-ce23-4251-a2ea-3865ddbafeac)|![20240624025718_7680293](https://github.com/huggingface/diffusers/assets/5442875/0c9afcd3-290a-47c1-babc-dbdb61877cff)|

**Comment by vikm2o** [comment]
> @vikm2o I opened the PRs to be able to use it. I didn't know if you wanted to open a PR for the community pipeline, if you want to do it, just tell me and I'll close mine.

It's fine @asomoza . Mine wasn't ready for PR anyway !
