### ISSUE TITLE
getting bug on diffuser example 

### ISSUE THREAD

**Issue by xalteropsx** [huggingface/diffusers#8638]
![image](https://github.com/huggingface/diffusers/assets/103671642/3c5f4d95-2f8b-40dc-b18a-b98d99d567b6)

modelp is  "dreamshaper_8Inpainting.safetensors"
https://huggingface.co/docs/diffusers/v0.29.0/en/api/pipelines/controlnet_sdxl#diffusers.StableDiffusionXLControlNetInpaintPipeline

tried compel as well it failed 
![image](https://github.com/huggingface/diffusers/assets/103671642/6b5ffff9-dfdc-4aab-9720-d2216dffb37e)

using diffuser 0.29.0

**Comment by haofanwang** [comment]
`dreamshaper_8Inpainting.safetensors` is not a SDXL model?

**Comment by asomoza** [comment]
Hi, can you please post the code as text and not as an image, it makes it a lot harder to read and to test.

**Comment by asomoza** [comment]
I learned the hard way that almost never is the same code, that's why we kindly ask for the same minimal reproducible code you can share for the issues.

For example, just out of the box, you're using pillow and `from_single_file` and the example does not.

Nevertheless I tested it with the same model and with one that I know it worked before and I can reproduce this issue, it seems this happens with the `from_single_file` refactor and the single file inpaint checkpoints. Pinging @DN6 for this.

Probably this won't be resolved fast so I suggest you use a diffusers format one like [this](https://huggingface.co/GraydientPlatformAPI/dreamshaper-turbo-inpainting-xl) one or install the [0.27.2](https://github.com/huggingface/diffusers/tree/v0.27.2) version of diffusers.

**Comment by sayakpaul** [comment]
Closing this as this seems to have been resolved. Feel free to reopen.
