### ISSUE TITLE
AutoEncoderKL only works for 2D shaped inputs

### ISSUE THREAD

**Issue by DemyCode** [huggingface/diffusers#8757]
I wanted to use right off the bat the AutoEncoderKL class but to my surprise the Up and Down blocks are only for 2D data.
I want to use this class for 3D data.

A nice solution would be to adapt this code to make it work for 1D, 2D and 3D as well. (Higher might be overkill)

I wanted to write my own code for this but I think it would be smarter to adapt the code myself and give it to everyone :)
I also feel like sharing my work and bring a bit of code to the diffusers package if that's fine for you.

PS: I don't know about the PreConfiged ones and how it would behave if a model "from_weights" cannot be loaded into a differently shaped model.

PS2: Please let me know if there is a problem in terms of guidelines or code of conduct.

**Comment by DemyCode** [comment]
I guess another way to solve this problem is to create multiple classes AutoEncoderKL1D, AutoEncoderKL2D, AutoEncoderKL3D and so on just like UNet.

**Comment by DN6** [comment]
Hi @DemyCode generally we tend to add new model types to `src` when there is a widely used checkpoint that can be used with that model. 

Currently, I don't believe any popular checkpoints exist that needs a 3D AutoencoderKL? If you could point me to one, we can definitely consider adding this class. Otherwise it might be better to add it in the `community` or `research projects` section

**Comment by DemyCode** [comment]
Ok perfect thank you very much ! I will think about doing that :)

**Comment by pranayj77** [comment]
Hello Demycode, did you end up adding this anywhere?

**Comment by DemyCode** [comment]
Hi @pranayj77 no I didn't because it wasn't on my priority list sorry.
