### ISSUE TITLE
[Community Pipeline] Modified Cross-Attention - Structured Diffusion Guidance for Compositional T2I synthesis

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#878]
## Intro

Community Pipelines are introduced in `diffusers==0.4.0` with the idea of allowing the community to quickly add, integrate, and share their custom pipelines on top of `diffusers`. 

You can find a guide about Community Pipelines [here](https://github.com/huggingface/diffusers/issues/841). You can also find all the community examples under [`examples/community/`](https://github.com/huggingface/diffusers/tree/main/examples/community). If you have questions about the Community Pipelines feature, please head to the [parent issue](https://github.com/huggingface/diffusers/issues/841).

## Idea: Modified cross-attention mechanism

This pipeline aims to implement this paper to Stable Diffusion, improving interpretability of the prompts. Some results of the paper [Training-Free Structured Diffusion Guidance for Compositional Text-to-Image Synthesis](https://openreview.net/forum?id=PUIqjT4rzq7): 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/788417/196206850-24e267c8-fe5a-4a4d-b17a-8bb2636f1914.png">

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by apolinario** [comment]
Awesome @20RitikSingh! Feel free to share your progress with us and let us know if you have any challenges

**Comment by keturn** [comment]
This is a super interesting paper! Note that there _is_ a reference implementation included in the `.zip` of "supplementary material" on the paper submission. Also note that implementation is _not_ released under the Apache License, so I don't know if :hugs: can accept a PR that includes it. It might be safer to do a clean-room implementation from only the description in the text of the paper.

[I Am Not A Lawyer and I Am Not Your Lawyer, but the paper's authors are obligated to remain anonymous until the end of the ICLR 2023 review period, so they can't speak for themselves right now.]

If you do choose to use the code from the supplementary material, you may need to swap some things around to make it better fit `diffusers` instead of `ldm`.

**Comment by patrickvonplaten** [comment]
Also cc @patil-suraj here FYI

**Comment by patil-suraj** [comment]
Interesting! 

 @20RitikSingh , let us know you need any help or have any questions, happy to help :)

**Comment by shunk031** [comment]
Hi, I have built a pipeline with diffusers based on the reference implementation. Here is my implementation of the Structured Diffusion Guidance: https://github.com/shunk031/training-free-structured-diffusion-guidance. 

However, I am not confident in my implementation because some parts of the published implementation are missing (e.g., sampler; a new argument, `skip`, has been added, but the details of this argument are not clear). Also, my implementation assumes batch size = 1, so it does not support multiple batch sizes. My implementation seems to have a bug with this limitation as well. Thank you.

**Comment by keturn** [comment]
The paper has been submitted as https://arxiv.org/abs/2212.05032 and is no longer anonymous! https://weixi-feng.github.io/structure-diffusion-guidance/

MIT licensed code by @weixi-feng at https://github.com/weixi-feng/Structured-Diffusion-Guidance
