### ISSUE TITLE
there is no qk_norm in SD3Transformer2DModel. Is that right?

### ISSUE THREAD

**Issue by heart-du** [huggingface/diffusers#8906]
### Describe the bug

there is no qk_norm in SD3Transformer2DModel. Is that right?

        self.attn = Attention(
            query_dim=dim,
            cross_attention_dim=None,
            added_kv_proj_dim=dim,
            dim_head=attention_head_dim // num_attention_heads,
            heads=num_attention_heads,
            out_dim=attention_head_dim,
            context_pre_only=context_pre_only,
            bias=True,
            processor=processor,
        )

### Reproduction

1.

### System Info

29.2

### Who can help?

dukunpeng

**Comment by tolgacangoz** [comment]
The paper says that the RMS-Norm for Q and K **can be** added to stabilize training runs. And, they observed the instability caused by not normalizing Q and K **not fully but partly** -at the last transformer blocks of the network. Maybe for this reason, it wasn't added. AFAIU this is not a compulsory thing to use but is optional.

Btw, the code you shared is not the last version of it; see it in the repo.

**Comment by a-r-r-o-w** [comment]
Thanks for addressing @tolgacangoz! I think this can now be marked closed, but feel free to re-open @heart-du if something needs addressing
