### ISSUE TITLE
Improve the precision of our integration tests

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#914]
We currently have a rather low precision when testing our pipeline due to due reasons. 
1. - Our reference is an image and not a numpy array. This means that when we created our reference image we lost float precision which is unnecessary
2. - We only test for `.max() < 1e-2` . IMO we should test for `.max() < 1e-4` with the numpy arrays. In my experiements across multiple devices I have **not** seen differences bigger than `.max() < 1e-4` when using full precision.

IMO this could have also prevented: https://github.com/huggingface/diffusers/issues/902

**Comment by Lewington-pitsos** [comment]
I'm going to start work on this right now

**Comment by Lewington-pitsos** [comment]
ok so at this stage I am going to try and improve the loading function so that is uses a more precise image loader than PIL. This should allow us to load the existing images at the current URLs with greater precision, allowing for a more precise comparison at the end. Will update as I go.

**Comment by Lewington-pitsos** [comment]
@patrickvonplaten after some research I think I understand the issue. 

The images are currently stored in a low-precision format (e.g. png) which prevents us from testing with any greater precision than `1e-2`. Even if we convert the image into a numpy array this will not help since the image itself is missing precision.

What we need to do is store a numpy representation of the image, say somewhere inside `https://huggingface.co/datasets` which we can then download and use for comparison.

The way we could do this is by generating the test output, saving that output as a numpy image and uploading it. 

This is what I plan to do tomorrow.

This [stack overflow thread](https://stackoverflow.com/questions/68757768/python-save-images-in-three-channels-and-float-type-to-avoid-losing-precision) was very helpful in understanding the issue.

**Comment by Lewington-pitsos** [comment]
Hey, yes I am currently working on this in fact!

**Comment by Lewington-pitsos** [comment]
@patrickvonplaten I made a PR adding the files: https://huggingface.co/datasets/hf-internal-testing/diffusers-images/discussions/2

**Comment by Lewington-pitsos** [comment]
@patrickvonplaten hey I noticed that it looks like you just made a PR recently fixing this issue. I was waiting on someone to approve my database PR before submitting mine. 

Is there some way I can get in contact with the team more easily so that we can avoid doubling up like this in future?

**Comment by patrickvonplaten** [comment]
Thanks a mille @Lewington-pitsos for making this very important improvement-of-life PR! Leaving this issue open as we still need to apply the same changes to:
- https://github.com/huggingface/diffusers/blob/main/tests/pipelines/stable_diffusion/test_stable_diffusion_img2img.py
and
- https://github.com/huggingface/diffusers/blob/main/tests/pipelines/stable_diffusion/test_stable_diffusion.py
