### ISSUE TITLE
diffusers.FluxPipeline has no .from_single_file() function

### ISSUE THREAD

**Issue by lutusp** [huggingface/diffusers#9141]
### Describe the bug

At the moment one cannot use a **local** Flux1-dev or -schnell file for lack of an essential function "from_single_file()" in the diffusers.FluxPipeline library. The provided flag "local_files_only" for some reason doesn't solve this problem.

### Reproduction

```
pipe = FluxPipeline.from_single_file(
    'full path to local file, example /(full_path)/flux1-dev.safetensors',
    torch_dtype=torch.bfloat16,
    use_safetensors=True,
    local_files_only=True
    )
```

### System Info

$ diffusers-cli env

- 🤗 Diffusers version: 0.30.0.dev0
- Platform: Linux-5.15.0-113-generic-x86_64-with-glibc2.35
- Running on Google Colab?: No
- Python version: 3.10.12
- PyTorch version (GPU?): 2.2.2+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.5
- Transformers version: 4.41.1
- Accelerate version: 0.30.1
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: 0.0.25.post1
- Accelerator: NVIDIA GeForce RTX 4090, 24564 MiB
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: NO

**Comment by DN6** [comment]
@lutusp Are you trying to load just the transformer model or do you have the weights for the entire checkpoint saved in single file checkpoint?

**Comment by lutusp** [comment]
I guess my explanation wasn't clear enough. My point wasn't that the function created an unexpected outcome, it is that the function doesn't exist. There is no function with that name in diffusers.FluxPipeline.

But apart from that, it was this file: "flux1-dev.safetensors", from here: https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main .

**Comment by mlick** [comment]
I have a same question, i want to know how to load local model?

**Comment by DN6** [comment]
@lutusp Support for single file for Flux at the pipeline level hasn't been added yet because checkpoints that contain all the model components in a single file were only recently released. The checkpoint you shared contains just the transformer weights. 

Support for single file loading just the Transformer exists currently.

```python
transformer = FluxTransformer2DModel.from_single_file(
    "https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/flux1-dev.safetensors",
    torch_dtype=torch.bfloat16
).to("cuda")
pipe = FluxPipeline.from_pretrained(
    "black-forest-labs/FLUX.1-dev",
    transformer=transformer,
    torch_dtype=torch.bfloat16
)
```

**Comment by tomsin9** [comment]
for the FluxTransformer2DModel.from_single_file(),
when i change the path to local, it doesnt work:

OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

**Comment by sxy771** [comment]
> for the FluxTransformer2DModel.from_single_file(), when i change the path to local, it doesnt work:
> 
> OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

I'm also wondering how to handle above errors.

I tried to load flux model downloaded from civitai but the model didn't work showing OSError message.

**Comment by missionfloyd** [comment]
This isn't stale. Flux, like various other pipelines, still lacks single file support. 

Most models seem to be distributed as safetensors files, so I think that the ability to use them should be a higher priority, and that diffusers shouldn't be so helplessly dependent on huggingface.co.

**Comment by asomoza** [comment]
Hi, you're mixing a lot of stuff.

The first and most important answer is that Flux has `from_single_file` support, it was added with this [PR](https://github.com/huggingface/diffusers/pull/9243) and this [one](https://github.com/huggingface/diffusers/pull/9244) too, this was added over a month ago so I really don't understand why are you posting this now.

Also to help understanding some concepts if you want to read after the answer.

**safetensors** is a format saving the model weights, diffusers uses this format. Some old models and researches don't use the safetensors format and instead use the pickle format.

Diffusers is **not** _"helplessly dependent on huggingface.co"_ as you mention, we promote the use of it because it makes things a lot easier for everyone that works with a lot of models and doesn't have the time to track and download each model from different websites and also it helps testing and solving issues by a lot since we don't have to manually download what the users are using when they have problems. It also helps people that know how to use git to update with just a single 2 word command line instead of going to some random site and check if the model was updated and then manually download each version.

You can use `from_pretrained` with local `multi directory diffusers` models or use `from_single_file` with also local models, you don't have to download them from the huggingface hub.

We stated this before and I repeat it here, we are giving the same importance to single file support as the multi directory diffusers format. The only reason why Flux didn't have single file support was because the original release wasn't with a single file, BFL released just the transformer model and the AE, people needed to download the T5 separately to use it.

Later some people started using the single file format and not everyone uses it as you say, because it's a big waste of space to have a 10GB text encoder for every model when all of them use the same one.

**Comment by asomoza** [comment]
I removed the stale tag just in case if you have some problem with the `from_single_file`, but if there isn't a problem anymore, I will close this issue as it was solved with the aforementioned PRs.

**Comment by missionfloyd** [comment]
Sorry, I didn't _think_ I was being rude, but maybe I was. I was frustrated, trying to get flux to work, unsuccessfully.

I do have some thoughts, though.

> it's a big waste of space to have a 10GB text encoder for every model when all of them use the same one

Does "single file" necessarily have to mean _single_ file? We're already used to loading e.g., VAEs separately, so why not other components? That way, we could have only one copy of common components. Maybe this is already possible and I'm just not looking in the right places.

> Diffusers is **not** "_helplessly dependent on huggingface.co_"

It sort of is, though. In some ways. Even when using from_single_file, pipelines still have to download config files from huggingface. In the case of flux, from a gated repo, further complicating things. These are (relatively) tiny files that could be bundled, and as RunwayML showed us last month, they probably should.

**Comment by asomoza** [comment]
> Sorry, I didn't think I was being rude, but maybe I was. I was frustrated, trying to get flux to work, unsuccessfully.

No problem, I understand that and also I did want to answer in a friendly way, so take it like that please, I kind of understand the frustration some people have with the model files.

> Does "single file" necessarily have to mean single file? We're already used to loading e.g., VAEs separately, so why not other components? That way, we could have only one copy of common components. Maybe this is already possible and I'm just not looking in the right places.

Actually, in this case yes, single file refers to what people use in sites like civitai and webuis, where they bundle all the model weights into a single container, this is the famous single file. Probably there isn't a single diffusion model that it's only one file, in fact, if you have over a 20 or 30 SDXL model files, you probably have over 50 GB of repeated data (even if each model is contained in one file) which is a waste of space but people still like it more because they manually download  the files.

The second part it's what people are doing now because Flux and the other models that use the T5 are too big to keep saving the text encoder for every model. With diffusers you can do this from before, you can actually load each file separately and then pass them to the pipeline, for example, you can mostly change just the unet in SD 1.5 and SDXL. 

> Even when using from_single_file, pipelines still have to download config files from huggingface. In the case of flux, from a gated repo, further complicating things.

This part I understand completely but if you think more deeply, you're kind of blaming diffusers because BFL decided to gate the repo, you don't have this problem with completely open source models. There are other private models that force you to share personal information, login or even to use a discord bot, you can't blame a library for what the model owners decide to do with their models and is the users decision if they want to use them with the restrictions they imposed. 

Personally I don't know the legality of the other sites where they allow to download those models without any restriction but as a library we must complain with the model licenses and what the owners decide to impose as a restriction to use them.

> These are (relatively) tiny files that could be bundled, and as RunwayML showed us last month, they probably should.

We probably would support this but sadly is not our decision, people don't provide any configuration information when they save the models with the `single file` format, it would be really easy for us to detect the config from each file but people would need to edit all their models and share them again and also start doing it with the new ones, you can see that this won't happen. 

Most webuis just hardcode this information in their code which for a library that researchers and developers use would be really bad, they can do it because their end users are people that use their UI not their code.

The RunwayML incident was bad but no one expected that, open source models shouldn't be deleted by their owners and this will always bring consequences and backslash, for example, if Meta decides to delete all the llama models, a lot of stuff will break but people don't expect this to happen.

**Comment by missionfloyd** [comment]
Fair enough.

Anyway, I noticed you [posted](https://gist.github.com/sayakpaul/b664605caf0aa3bf8585ab109dd5ac9c) some stuff about this. I was able to get it to work on my RTX 4070 using your NF4 example.

**Comment by zhaowendao30** [comment]
I have solved it, you should add a param 'config' in FluxTransformer2DModel.from_single_file which is the transformer's config.json, like this `transformer = FluxTransformer2DModel.from_single_file("/flux-fp8/flux1-dev-fp8.safetensors", config='/flux-dev/transformer/config.json',  torch_dtype=dtype)`

**Comment by a-r-r-o-w** [comment]
@asomoza From what I gather from above conversation, I think this issue is resolved, yes?

**Comment by asomoza** [comment]
yeah, the issue was resolved with the PRs. This issue still has some really good points made by @missionfloyd which I will take note and try to something about it in the future.

For example I think that to make a bundle with all the different support files needed by diffusers (mostly configs) is a good idea, maybe not distribute it with the repo but make it available for download so people can use diffusers offline right out of the box.

If someone wants to further discuss this we can open a discussion about it.
