### ISSUE TITLE
Support FLUX nf4 & pf8 for GPUs with 6GB/8GB VRAM (method and checkpoints by lllyasviel)

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#9149]
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981

> Flux Checkpoints
> The currently supported Flux checkpoints are
> 
> [flux1-dev-bnb-nf4.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4.safetensors) Full flux-dev checkpoint with main model in NF4. <- Recommended
> [flux1-dev-fp8.safetensors](https://huggingface.co/lllyasviel/flux1_dev/blob/main/flux1-dev-fp8.safetensors) Full flux-dev checkpoint with main model in FP8.
> Basic facts:
> 
> (i) NF4 is significantly faster than FP8. For GPUs with 6GB/8GB VRAM, the speed-up is about 1.3x to 2.5x (pytorch 2.4, cuda 12.4) or about 1.3x to 4x (pytorch 2.1, cuda 12.1). I test 3070 ti laptop (8GB VRAM) just now, the FP8 is 8.3 seconds per iteration; NF4 is 2.15 seconds per iteration (in my case, 3.86x faster). This is because NF4 uses native bnb.matmul_4bit rather than torch.nn.functional.linear: casts are avoided and computation is done with many low-bit cuda tricks. (Update 1: bnb's speed-up is less salient on pytorch 2.4, cuda 12.4. Newer pytorch may used improved fp8 cast.) (Update 2: the above number is not benchmark - I just tested very few devices. Some other devices may have different performances.) (Update 3: I just tested more devices now and the speed-up is somewhat random but I always see speed-ups - I will give more reliable numbers later!)
> 
> (ii) NF4 weights are about half size of FP8.

**Comment by chuck-ma** [comment]
I think if NF4 is much better than FP8, maybe we can make it usable for all models. (Including SDXL)

**Comment by Ednaordinary** [comment]
@chuck-ma NF4 is better in some cases and worse in other cases compared to FP8 (hard to tell when though). NF4 is essentially FP4 (4 bits per weight) with some additional data that is calibrated to output closer to what the original model intended compared to FP4. FP8 is essentially casting down to 8 bits per weight without any sort of calibration, so it's faster to make but larger and different from NF4.

In addition, there's no real reason other models shouldn't support this since it doesn't rely on any flux specific quirk (flux just motivated the development of quantization techniques like this for image models)

**Comment by Swarzox** [comment]
It seems I can't get it work with diffusers, do you have any very simple example code to make it works?

Many thanks.

**Comment by Ednaordinary** [comment]
@Swarzox This is an issue, not a PR. The code to make this work in diffusers has not been contributed or created yet.

**Comment by Ednaordinary** [comment]
Please see #9165, #9174

**Comment by sayakpaul** [comment]
Both NF4 and llm.int8 can be done with some code changes ad-hoc: 
https://github.com/huggingface/diffusers/discussions/8746

Serialization and direct loading support will be done through the plan proposed in #9174. 

Directly loading the [said checkpoint](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4.safetensors) can lead to some problematic results because of the reasons explained in https://github.com/huggingface/diffusers/issues/9165#issuecomment-2287823072. 

If you want obtain the text encoders and VAE from that checkpoint, you can use the snippet from https://github.com/huggingface/diffusers/issues/9165#issuecomment-2287823072 and then use something like https://github.com/huggingface/diffusers/pull/9177 so that computations run in a higher-precision data-type while the params are kept in lower-precision data-type such as FP8. 

You can also do a direct llm.int8() or NF4 style loading of the bulky T5-xxl and use it within a diffusers pipeline. See: https://gist.github.com/sayakpaul/82acb5976509851f2db1a83456e504f1

There are many options to run things in a memory-efficient way. So, with a programmatic approach, we let you choose what's best for you :)

**Comment by lonngxiang** [comment]
how to use with diffusrrs？ any code

**Comment by lonngxiang** [comment]
> Please see #9165, #9174

The code appears to be complex, and the GPU usage far exceeds 8GB.

**Comment by Ednaordinary** [comment]
@lonngxiang 

I can't be sure of what you are doing, but I get 9 GiB with CPU offload and ~18 GiB without

CPU offload:
![image](https://github.com/user-attachments/assets/34808fa0-44d9-417f-9e71-a1fe51ba57d0)

GPU only:
![image](https://github.com/user-attachments/assets/a266edc9-3eef-4c9e-a71b-a6bf662842d3)


This may also get even better when #9174 is complete/has a working demo

**Comment by lonngxiang** [comment]
I am very much looking forward to it, hoping for an extremely simple implementation with just a few lines of code.

**Comment by dylanisreversing** [comment]
> @lonngxiang
> 
> I can't be sure of what you are doing, but I get 9 GiB with CPU offload and ~18 GiB without
> 
> CPU offload: ![image](https://private-user-images.githubusercontent.com/88869424/363366644-34808fa0-44d9-417f-9e71-a1fe51ba57d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjAwNTMsIm5iZiI6MTcyNTExOTc1MywicGF0aCI6Ii84ODg2OTQyNC8zNjMzNjY2NDQtMzQ4MDhmYTAtNDRkOS00MTdmLTllNzEtYTFmZTUxYmE1N2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDE1NTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NTVhNGNjNmRmZWVhYTg1OGJhNjliZGYyNmJjZThlYWU3ZWFiNTY5NWRjZWY1OTM4MjkwNDE3MDMxMGNiZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TjUz8eSqOABp9QrryiN4igP7KQuB6nojFJepUqCT3Sg)
> 
> GPU only: ![image](https://private-user-images.githubusercontent.com/88869424/363366735-a266edc9-3eef-4c9e-a71b-a6bf662842d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjAwNTMsIm5iZiI6MTcyNTExOTc1MywicGF0aCI6Ii84ODg2OTQyNC8zNjMzNjY3MzUtYTI2NmVkYzktM2VlZi00YzllLWE3MWItYTZiZjY2Mjg0MmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDE1NTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZTI4ZDM0YjgzYTI1MzU2ZTNhMzBlYjA0ZTI0MTg0NjFiN2NmMWFmODQ5YzA1NzRlYzU0ZTZkZGI1YTExYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pqtK3lLgXnAc1nUwH1OBN9ovNlkJ5X8wiNIu0FJFs_Q)
> 
> This may also get even better when #9174 is complete/has a working demo

Hey @Ednaordinary, I saw your comment on the other thread about the previous error you were encountering and wanted to know how/if you resolved it. I am talking about the _'Error in FluxImageGenerator initialization: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.'_

I am stuck on the same problem right now. Thank you!

**Comment by kanarch66** [comment]
NF4 is removed from comfyui latest update

**Comment by sayakpaul** [comment]
We have landed https://huggingface.co/docs/diffusers/main/en/quantization/bitsandbytes
