### ISSUE TITLE
Finetuning on dataset

### ISSUE THREAD

**Issue by ultiwinter** [huggingface/diffusers#9317]
dear @thedarkzeno and @patil-suraj 

Thank you so much for putting your work out there. I wanted to ask, how would the training be for training on a dataset and not a single instance image as mentioned in train_dreambooth_inpaint. And can I finetune models trained from https://github.com/CompVis/latent-diffusion repository?

Thanks in advance

**Comment by asomoza** [comment]
Hi, the reason why you didn't get an answer was probably because you tagged people that aren't the maintainers of diffusers anymore. 

We have [finetune scripts](https://github.com/huggingface/diffusers/tree/main/examples/text_to_image) you can read, learn and adapt them to your specific needs, most of them use datasets.
