### ISSUE TITLE
[Pipeline] MimicMotion

### ISSUE THREAD

**Issue by reallyigor** [huggingface/diffusers#9387]
### Model/Pipeline/Scheduler description

MimicMotion is a recent paper on Personalised Image2Video generation.
An input is a reference image and a driving video, motion from the driving video is taken to animate reference image. 

The results are really great!:
<img width="896" alt="image" src="https://github.com/user-attachments/assets/875bb2d7-69b2-45be-a0b1-0cb43aefc33a">

[Project page](https://tencent.github.io/MimicMotion/)
[License is Apache 2.0](https://github.com/Tencent/MimicMotion/blob/main/LICENSE)

I would like to add this pipeline to the diffusers.

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/tencent/MimicMotion
Authors: @gujiaxi 

cc. @DN6 @a-r-r-o-w

**Comment by a-r-r-o-w** [comment]
I believe they already provide a [Diffusers pipeline](https://github.com/Tencent/MimicMotion/blob/main/mimicmotion/pipelines/pipeline_mimicmotion.py) which means you can already load it with [custom pipelines](https://huggingface.co/docs/diffusers/v0.30.2/using-diffusers/custom_pipeline_overview) or directly copy and use. Usually, if a project already builds on top of Diffusers, we don't need to support it as a core pipeline. Maybe since this looks very promising and high usage (1.5k stars), it could be considered but better for @DN6 to decide on that

**Comment by reallyigor** [comment]
>Usually, if a project already builds on top of Diffusers, we don't need to support it as a core pipelin

Got it 👍
