### ISSUE TITLE
Could not load lora: PEFT backend is required for this method

### ISSUE THREAD

**Issue by FOSSEnjoyer69** [huggingface/diffusers#9670]
### Describe the bug

I am trying to use a lora with the StableDiffusion ControlNet Inpaint Pipeline but i am getting the error 'PEFT backend is required for this method.' even though PEFT is installed (globally and in the venv)

i am using 'path/to/lora' for the lora because the lora model does not matter, same error is thrown everytime

### Reproduction

```
pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
        inpaint_model_id, 
        controlnet=controlnet, 
        torch_dtype=torch.float16, 
        local_files_only=False)

try:
        pipe.load_lora_weights(path/to/lora)
except Exception as e:
        print(f"Could not load lora: {e}")
```

### Logs

```shell
Could not load lora: PEFT backend is required for this method.
```

### System Info

OS: Ubuntu 22.04 LTS

A1111: v1.10.1
peft: 0.13.1
diffusers: 0.30.3

### Who can help?

@sayakpaul

**Comment by asomoza** [comment]
HI, the error message you're getting is because the script doesn't detect that 'peft' is installed, is not something we can help within the library. 

You should probably do a simple test to check this, like a plain python script and import peft:

```python
from peft import get_peft_config
```

if it throws the same error (it probably will), then it doesn't have anything to do with diffusers but with your environment. I noticed you posted the auto1111 version, which is not needed for diffusers, maybe this is what's causing the problem for you.

**Comment by FOSSEnjoyer69** [comment]
yeah, nothing changed, I'll keep doing more tests, hopefully I'll find whats causing the problem
