### ISSUE TITLE
shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp, gate_mlp = emb.chunk(6, dim=1) ValueError: not enough values to unpack (expected 6, got 4)

### ISSUE THREAD

**Issue by LianShuaiLong** [huggingface/diffusers#9728]
### Discussed in https://github.com/huggingface/diffusers/discussions/9710

<div type='discussions-op-text'>

<sup>Originally posted by **LianShuaiLong** October 18, 2024</sup>
To save GPU memory during training, I pre-extracted the text embeddings. During the training process, I did not load the text encoders and directly used the embeddings for training. However, I encountered the following error:

```
shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp, gate_mlp = emb.chunk(6, dim=1)
ValueError: not enough values to unpack (expected 6, got 4)
```
Here is my feature extraction script and the modified training script. Could someone kindly help me identify where the issue might be?
</div>

**Comment by a-r-r-o-w** [comment]
Sorry about the delay in responding, but I don't think there is enough information here for us to be able to help. Providing code in a zip file is not ideal, so for any help, it is necessary that you create a repository with your code and provide a link to that instead.

Also, just for quick verification, `emb` should be the timestep conditioned norm scale/gates and not text embeddings. So if you're passing text embeddings to `emb` instead of `encoder_hidden_states`, that might be a cause for the problem.

This issue is however out of scope due to you using custom code, and it's not Diffusers-specific, so it might be that no one may respond - although I'll try if you were to create a public repo with your code. Marking this as closed for now. Feel free to re-open when there is a public repo and if you still need any help
