### ISSUE TITLE
Please update your tutorial

### ISSUE THREAD

**Issue by seetoclick** [huggingface/diffusers#9865]
Have you learned software design? Why you delete or change some API but you keep them in your tutorial? Why do not you keep old API alive and have a new name? You bring unnecessary brother to study and application.

**Comment by sayakpaul** [comment]
What documentation are you referring to?

**Comment by ayulockin** [comment]
> You bring unnecessary brother to study and application

"Left as an exercise for the reader."

**Comment by a-r-r-o-w** [comment]
Closing this because enough context is not provided. Please feel free to re-open but please also provide which tutorial are you referring to?

We sincerely apologise for any inconvenience caused and will try and do better in keeping tutorials that live in our `docs/` folder up-to-date with latest API.
