### ISSUE TITLE
Strength argument for StableDiffusionInpaintPipeline.__call__() in diffusers==0.6.0

### ISSUE THREAD

**Issue by mrgomdev** [huggingface/diffusers#992]
In previous inpainting pipeline(now StableDiffusionInpaintPipelineLegacy ) has the `strength` argument for set an offset, an independant argument from `num_inference_steps` . Is there any reason to remove that feature? Intuitively it could be different, small num_inference_steps vs large num_inference_steps x low strength, including noise from the starting timestep.

I've just thought, is it related to not calling scheduler.add_noise() in the newer pipeline.__call__()?

**Comment by patrickvonplaten** [comment]
Hey @mrgomdev, 

`strength` is not really removed -> the previous experimental pipeline was just moved to: https://github.com/huggingface/diffusers/blob/8332c1a6d956748db288d8edb7797ca38a5ea60e/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py#L152 

In the official inpainting pipeline this is however not needed because only the mask is ever filled and not the rest :-)

**Comment by mrgomdev** [comment]
I understood that I can use StableDiffusionInpaintPipelineLegacy with strength, or StableDiffusionInpaintPipeline with just num_inference_steps. Thanks!
I need to check out more detail of the recent official inapinting pipeline with the new model.

**Comment by aseemkhanduja** [comment]
> diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py

Hey @patrickvonplaten It's still useful for various other usecases, especially where you want to maintain color etc in mask area. Anyway we can enable it?
