### ISSUE TITLE
Question about CLIP-guided SD

### ISSUE THREAD

**Issue by KevinGoodman** [huggingface/diffusers#994]
In cond_fn of examples/community/clip_guided_stable_diffusion.py, we have
```python
# "predicted x_0" of formula (12) from https://arxiv.org/pdf/2010.02502.pdf
pred_original_sample = (latents - beta_prod_t ** (0.5) * noise_pred) / alpha_prod_t ** (0.5)

fac = torch.sqrt(beta_prod_t)
sample = pred_original_sample * (fac) + latents * (1 - fac)
```
I am confused that why not use *pred_original_sample* to get the image for CLIP guidance. Why do we need this extra conversion to get *sample*?

**Comment by patrickvonplaten** [comment]
Gently pinging @patil-suraj here

**Comment by patil-suraj** [comment]
Hi, I adapted this example from the clip guided GLIDE example by @crowsonkb
https://github.com/crowsonkb/glide-text2im/blob/main/glide_text2im/gaussian_diffusion.py#L293, 
I don't have good intuition about this, maybe @crowsonkb could share more :)

**Comment by KevinGoodman** [comment]
FYI, In another new paper [UPainting: Unified Text-to-Image Diffusion
Generation with Cross-modal Guidance](https://arxiv.org/pdf/2210.16031.pdf),I found similar operation:
![image](https://user-images.githubusercontent.com/43786278/200119571-47c89fc5-a9e8-482f-88c5-16d96ed5e314.png)

**Comment by patil-suraj** [comment]
Thanks @KevinGoodman , will take a look at this. Have you tried modifying the pipeline like this and see if it gives good results ? Curious to see the results :)

**Comment by KevinGoodman** [comment]
No, unfortunately I haven't got time to compare them but I think they should be on par with each other. For my use case, my prompts are generally long and quite complicated, and it seems that the CLIP-guided method implemented here does not bring much benefit as I hope

**Comment by patil-suraj** [comment]
I see, will look into implementing this when I get some time :) But if anyone here is interested feel free to open a PR

**Comment by yujianll** [comment]
@patil-suraj @KevinGoodman Thanks for the script and pointer to the paper.
Based on my understanding, I think the current script is doing exactly this step (eq 4)? I.e., ```sample``` at [line 146](https://github.com/huggingface/diffusers/blob/main/examples/community/clip_guided_stable_diffusion.py#L146) is the $x_{in}$ in eq4.
I wonder is there any experiments that compare doing guidance on $x_{in}$ versus $x_t$, and predicted $\hat{x}_0$.

**Comment by KevinGoodman** [comment]
I agree. In my case, this does not bring much improvement. More comprehensive experiments are needed but I have limited resources.

**Comment by yujianll** [comment]
I see, thanks!

**Comment by aluo-x** [comment]
From my experiments, using some form of 
```
pred_original_sample * (fac) + latents * (1 - fac)
```
helps immensely for convergence in clip guided diffusion (latent or otherwise). If you think about it, it is essentially computing an euler approximation of x_0 (the so called pred_original_sample), using that in a weighted average with the original x_t (the so called latents), and computing a gradient wrt. to latents. And recall that x_0 is a function of latents as well. x_0 is a natural image (or mostly natural), while latents is likely some very high noise and unnatural image. 

Its not clear that this weighting itself using fac and 1-fac is necessary, but it does introduce some noise back into the sample fed to CLIP compared to using pred_original_sample alone. Perhaps that is something that empirically helps with avoiding local minima, as I don't really see any theoretical justification for this. If anyone can point to a paper with a robust justification I'd be grateful.
